// ENGLISH locale: a flat map from the canonical Russian msgid to the English
// translation. A missing entry falls back to the Russian source (visible, honest).
// Game-DATA names (buildings/units/technologies/sectors/planet types — authored in
// English in game.ts) need no entry here; `tData()` shows them as-is on this locale.
// One language = one file.
export const en: Record<string, string> = {
  // --- STAFF-1 «Штаб героев» redesign -------------------------------------------
  'У вас пока нет героев.': 'You have no heroes yet.',
  'развёрнуто {a}/{c}': 'deployed {a}/{c}',
  '⚓ развёрнут': '⚓ deployed',
  резерв: 'reserve',
  'не ваша ветвь': 'not your branch',
  'чужая ветвь': 'other branch',
  'нужен: {n}': 'needs: {n}',
  Дерево: 'Tree',
  'Дерево пусто.': 'The tree is empty.',
  Общие: 'Common',
  способность: 'ability',
  пассивка: 'passive',
  'Нет способностей.': 'No abilities.',
  Фиттинги: 'Fittings',
  'Слоты · {u}/{n}': 'Slots · {u}/{n}',
  'У этого героя нет слотов фиттингов.': 'This hero has no fitting slots.',
  способностей: 'abilities',
  'узлов дерева': 'tree nodes',
  фиттингов: 'fittings',
  'Текущие бонусы': 'Current bonuses',
  актив: 'active',
  'Открывает способность': 'Unlocks an ability',
  'Даёт пассивку': 'Grants a passive',
  'Модификатор корпуса': 'Hull modifier',
  'дальность {r}': 'range {r}',
  'КД {h}ч': 'CD {h}h',
  Требует: 'Requires',
  Цена: 'Cost',
  // NB: `Изучить` is translated once, in the meta-progression block below ('Unlock')
  // — a second entry here would be silently shadowed by it.
  'Ставится навсегда — рефита нет': 'Installed for good — no refit',
  'Необратимо — установить': 'Irreversible — install',
  Каст: 'Cast',
  Делить: 'Split',
  'цель на карте': 'target on map',
  'на месте': 'in place',
  // --- TT-3.1 technology tree screen --------------------------------------------
  'Ветку курирует': 'Branch curated by',
  'Без лидера ветки — узлы с условием «учёный» закрыты':
    'No branch leader — “scientist”-gated nodes stay locked',
  'слоты {a}/{b}': 'slots {a}/{b}',
  ДЕНЬ: 'DAY',
  старт: 'start',
  день: 'day',
  Индустрия: 'Industry',
  Сенсоры: 'Sensors',
  Доктрины: 'Doctrines',
  Укрепления: 'Fortifications',
  Авиакрыло: 'Air wing',
  Арсенал: 'Arsenal',
  Связь: 'Signals',
  Автоматизация: 'Automation',
  производство: 'production',
  'скорость флотов': 'fleet speed',
  урон: 'damage',
  'радиус радаров': 'radar range',
  'открывает: {x}': 'unlocks: {x}',
  'способность: {x}': 'ability: {x}',
  'нужен учёный: {b}': 'needs a scientist: {b}',
  'любой ветки': 'any branch',
  'своих секторов: {n}': 'own sectors: {n}',
  'здание: {b} ×{n}': 'building: {b} ×{n}',
  'мир типа {p} ×{n}': '{p} world ×{n}',
  'юнит: {u} ×{n}': 'unit: {u} ×{n}',
  'особое условие': 'special condition',
  ИЗУЧЕНО: 'RESEARCHED',
  ИССЛЕДУЕТСЯ: 'RESEARCHING',
  ДОСТУПНО: 'AVAILABLE',
  ЗАКРЫТО: 'LOCKED',
  'Не хватает ресурсов': 'Not enough resources',
  Изучено: 'Researched',
  'Идёт — ≈ {n} ч': 'In progress — ≈ {n}h',
  'Откроется в День {n}': 'Opens on Day {n}',
  'Сначала изучите узел выше': 'Research the node above first',
  'Условие не выполнено': 'Condition not met',
  'с дня {n}': 'from day {n}',
  'Требует:': 'Requires:',
  Хранитель: 'Steward',
  // --- SPY-UX intel tab in diplomacy --------------------------------------------
  Шпионаж: 'Espionage',
  'Попытка: {c}¤ · шанс ~60% · окно интела 24ч · провал сжигает плату. Разведка мира — кнопка 🕵 на карточке вражеской планеты.':
    'Attempt: {c}¤ · ~60% chance · 24h intel window · a failure burns the fee. World recon — the 🕵 button on an enemy planet card.',
  'АКТИВНЫЕ ОКНА ИНТЕЛА': 'ACTIVE INTEL WINDOWS',
  'нет активных окон — добудьте интел операцией ниже':
    'no active windows — steal intel with an operation below',
  ОПЕРАЦИИ: 'OPERATIONS',
  'противников нет': 'no opponents',
  ЖУРНАЛ: 'JOURNAL',
  'попыток ещё не было': 'no attempts yet',
  '🗝 Успех: {what}': '🗝 Success: {what}',
  '✖ Провал против {who} — плата сгорела': '✖ Failed against {who} — the fee burned',
  // --- ONB-7 first-session goals checklist -------------------------------------
  'Цели первой сессии': 'First-session goals',
  'Построй шахту': 'Build a mine',
  'Захвати мир': 'Capture a world',
  'Набери 100 очков': 'Reach 100 points',
  '🏅 Все цели первой сессии выполнены! +{n} XP — ты готов к настоящему матчу.':
    '🏅 All first-session goals done! +{n} XP — you are ready for a real match.',
  // --- ONB-5 async intro + return digest ---------------------------------------
  'Мир идёт без тебя': 'The world runs without you',
  'Этот флот прибудет через часы реального времени — мир Void Dominion идёт непрерывно, даже когда ты офлайн. Можешь закрыть игру: приказы выполнятся сами, а к возвращению мы пришлём уведомление и покажем сводку «пока тебя не было».':
    'This fleet will arrive in real hours — the world of Void Dominion runs continuously, even while you are offline. You can close the game: your orders carry out on their own, and on your return we will send a notification and show a "while you were away" digest.',
  'Сводка возвращения': 'Return digest',
  'СВОДКА ВОЗВРАЩЕНИЯ': 'RETURN DIGEST',
  'Требуют внимания · {n}': 'Needs attention · {n}',
  'Пока тебя не было': 'While you were away',
  // --- ONB-3 just-in-time mechanic intros --------------------------------------
  впервые: 'first time',
  'Дерево технологий': 'Technology tree',
  'Здесь ты открываешь технологии — постоянные улучшения флота, экономики и обороны. Узел стоит ресурсов и времени; изучил — бонус действует до конца матча. Планируй ветку под свой стиль игры.':
    'Here you unlock technologies — permanent upgrades to your fleet, economy and defence. A node costs resources and time; once researched, the bonus lasts the rest of the match. Plan the branch to fit your playstyle.',
  'Сессионный рынок': 'Session market',
  'Торгуй ресурсами с другими игроками сессии: выставляй свои лоты и забирай чужие. Рынок сглаживает нехватку — обменяй излишек одного ресурса на тот, которого не хватает.':
    'Trade resources with the other players in the session: post your own lots and take theirs. The market smooths shortages — swap a surplus of one resource for the one you lack.',
  'Хранитель — ИИ на сон': 'Steward — AI on sleep',
  'Уходишь надолго? Передай оборону Хранителю — он будет держать твои миры по заданным правилам, пока тебя нет. Мир идёт 24/7, но базовая защита останется, даже когда ты офлайн.':
    'Away for a while? Hand your defence to the Steward — it holds your worlds by your rules while you are gone. The world runs 24/7, but a baseline defence stays up even when you are offline.',
  'Верфь — оснащение': 'Shipyard — loadouts',
  'Здесь ты собираешь корабли, эскадрильи, дивизии и героев из модулей. Лоадаут фиксируется при постройке — выбирай слоты заранее, переоснастить готовое нельзя. Вкладка «Герои» — штаб командиров.':
    'Here you assemble ships, squadrons, divisions and heroes from modules. The loadout is locked at build time — choose slots up front, a finished unit cannot be re-fitted. The «Heroes» tab is your commander HQ.',
  'Объявляй войну и мир, заключай пакты и союзы. Коалиция ограничена порогом силы — всех против одного не собрать. Следи за стойками сторон: союзник сегодня может стать соперником завтра.':
    'Declare war and peace, sign pacts and alliances. A coalition is capped by combined strength — you cannot gang everyone up on one player. Watch the stances: an ally today can be a rival tomorrow.',
  // --- ONB-8 social/meta-layer intros (corp cabinet + AvA wars tab) ------------
  'Корпорация — это твой отряд в общей сессии: общий склад, роли участников и совместные войны альянсов (AvA). Вступи в существующую или создай свою — вкладка «Войны» открывает доступ к вызовам между корпорациями.':
    'A corporation is your squad within the session: a shared warehouse, member roles, and joint alliance-vs-alliance wars (AvA). Join one or found your own — the «Wars» tab opens challenges between corporations.',
  'Войны альянсов (AvA)': 'Alliance wars (AvA)',
  'Здесь корпорации бросают друг другу вызов на организованную войну. Отметь готовность корпорации и свою личную — когда обе стороны готовы, можно принять вызов. Дальше — набор состава и сама война по расписанию.':
    'Here corporations challenge each other to an organised war. Mark your corporation ready and yourself ready — once both sides are ready, a challenge can be accepted. Next comes roster sign-up and the scheduled war itself.',
  // --- ONB-4 codex/help hub (chrome + glossary) --------------------------------
  Справочник: 'Codex',
  Справка: 'Help',
  СПРАВОЧНИК: 'CODEX',
  'Поиск: юнит, здание, термин…': 'Search: unit, building, term…',
  'Поиск по справочнику': 'Search the codex',
  'Ничего не найдено': 'Nothing found',
  механика: 'mechanic',
  Механики: 'Mechanics',
  'Асинхронный мир': 'Asynchronous world',
  'Мир идёт в реальном времени и продолжается 24/7 — даже когда ты вышел. Приказы занимают реальные часы: отдал курс, закрыл игру, вернулся к результату. Это не пошаговая игра — заходи, отдавай приказы, выходи.':
    'The world runs in real time and keeps going 24/7 — even after you leave. Orders take real hours: set a course, close the game, come back to the result. This is not turn-based — drop in, issue orders, drop out.',
  'Туман войны': 'Fog of war',
  'Ты видишь только то, что рядом с твоими силами и радарами; остальное скрыто туманом или показано по памяти (последнее, что ты там видел). Разведчики и радары раздвигают обзор — держи глаза открытыми.':
    'You see only what is near your forces and radars; the rest is hidden by fog or shown from memory (the last thing you saw there). Scouts and radar widen your view — keep your eyes open.',
  'Содержание (upkeep)': 'Upkeep',
  'Флоты и здания требуют ежедневной платы. Доход от шахт минус содержание = чистый баланс; уйдёшь в минус — казна опустеет. Строй экономику раньше армии.':
    'Fleets and buildings cost a daily fee. Mine income minus upkeep = your net balance; go negative and the treasury drains. Build economy before army.',
  'Орбита и высадка': 'Orbit and landing',
  'Захват мира — двухфазный. Сначала выйди на орбиту и подави оборону в космосе; если мир защищён гарнизоном — высади десант (наземную дивизию из трюма). Небо, потом земля.':
    'Capturing a world is two-phase. First enter orbit and beat the defenders in space; if the world holds a garrison, land troops (a ground division from the hold). Sky first, then ground.',
  'Звёздные трассы': 'Star lanes',
  'Флоты ходят не напрямую, а по звёздным трассам (лэйнам) между мирами — маршрут строится автоматически. Узлы на трассах можно перехватывать: встречный враг на пути — это бой.':
    'Fleets travel not in straight lines but along star lanes between worlds — the route is built automatically. Lane nodes can be intercepted: an enemy met on the way is a battle.',
  'Очки капают за то, чем ты владеешь: мир — 50, прочий сектор — 10, здания добавляют по уровню. Набери порог очков — победа. Другой путь к победе — уничтожение соперников или доминирование.':
    'Points accrue from what you hold: a world — 50, any other sector — 10, buildings add per level. Reach the score threshold to win. Other paths to victory: eliminating rivals or domination.',
  'Коалиционный порог': 'Coalition cap',
  'Дипломатия позволяет заключать пакты и союзы, но коалиция ограничена порогом совокупной силы — нельзя собрать всех против одного. Порог держит баланс сил и не даёт «снежному кому» задавить партию.':
    'Diplomacy lets you sign pacts and alliances, but a coalition is capped by combined strength — you cannot gang everyone up on one player. The cap keeps the balance of power and stops a snowball from crushing the game.',
  // --- ONB-0 first-run offer (hub) + «Ещё → Обучение» --------------------------
  'Впервые в Void Dominion?': 'New to Void Dominion?',
  'Короткое обучение покажет интерфейс и первый ход — пара минут.':
    'A short tutorial walks you through the interface and your first move — a couple of minutes.',
  'Начать обучение': 'Start tutorial',
  Пропустить: 'Skip',
  Обучение: 'Tutorial',
  // --- ONB-2 guided first match (firstMatchTour) -------------------------------
  'Это твой первый мир, командир. Проведу тебя по главному циклу — пара минут, спокойно, без соперников.':
    'This is your first world, commander. I will walk you through the core loop — a couple of minutes, calm, no rivals.',
  'Внизу — панель твоего домашнего мира: здания, гарнизон и стройка. Тапни свой мир, если панель пуста.':
    'Down here is your homeworld panel: buildings, garrison and construction. Tap your world if the panel is empty.',
  'Начни с экономики: построй Шахту — она даёт ресурсы, на них строится всё остальное.':
    'Start with economy: build a Mine — it produces the resources everything else is built from.',
  'Выбери свой флот (▲) и тапни соседний мир — задай курс. Флот пойдёт по звёздным трассам, и туман начнёт открываться.':
    'Select your fleet (▲) and tap a neighbouring world to set a course. It routes along the star lanes and the fog opens.',
  'Захвати нейтральный мир: выйди на орбиту, а если он защищён — высади десант. Захват двухфазный: сначала небо, потом земля.':
    'Take a neutral world: enter orbit, and if it is defended, land troops. Capture is two-phase: sky first, then ground.',
  'Мир взят — и счёт пошёл! Очки капают за миры и сектора; набери порог — и это победа.':
    'World taken — and the score moves! Points come from worlds and sectors; reach the threshold to win.',
  'Первая схватка выиграна! Ты прошёл весь цикл: добыча → стройка → движение → захват → счёт. Дальше — настоящий матч.':
    'First fight won! You ran the whole loop: produce → build → move → capture → score. Next up — a real match.',
  '✔ Обучение пройдено · +{n} XP — теперь сыграй настоящий матч!':
    '✔ Tutorial complete · +{n} XP — now play a real match!',
  // --- ONB-1 guide-marks (spotlight) — chrome + HUD orientation tour -----------
  'шаг {k} из {n}': 'step {k} of {n}',
  Далее: 'Next',
  Понятно: 'Got it',
  'Пропустить обучение': 'Skip tutorial',
  'Короткий тур по интерфейсу — на нём держится весь мир. «Пропустить обучение» доступно всегда.':
    'A quick tour of the interface — the whole game runs on it. «Skip tutorial» is always available.',
  'Мир идёт в реальном времени и продолжается, даже когда ты офлайн. Здесь — пауза и ускорение.':
    'The world runs in real time and keeps going even while you are offline. Pause and speed live here.',
  'Твоя казна: доход от шахт минус содержание флота. Следи, чтобы не уйти в минус.':
    'Your treasury: mine income minus fleet upkeep. Keep it out of the red.',
  'Инструменты командира: дипломатия, наука, верфь, рынок и сводки событий.':
    "The commander's tools: diplomacy, research, shipyard, market and the event log.",
  'Готово! Пора действовать: построй шахту, подними флот, отдай курс. Удачи, командир.':
    'Done! Time to act: build a mine, raise a fleet, set a course. Good luck, commander.',
  // --- placeholders / small fragments ------------------------------------------
  ' · потери: {tally}': ' · losses: {tally}',
  '+{n} десанта': '+{n} troops',
  '{a} и {b}: {stance}': '{a} and {b}: {stance}',
  '{a} объявил войну {b}': '{a} declared war on {b}',
  '{b} — улучшение': '{b} — upgrade',
  '{f} флот(ов) · {s} кораблей · {tr} десанта': '{f} fleet(s) · {s} ships · {tr} troops',
  '{n} (улучшаемо)': '{n} (upgradeable)',
  '{n} / уровень': '{n} / level',
  '{n} {r}/день': '{n} {r}/day',
  '{n} {r}/ч': '{n} {r}/h',
  '{n} ФЛОТОВ': '{n} FLEETS',
  // TGT-1: target-order composer
  Цель: 'Target',
  '◎ тапните цель на карте — соберём приказ': '◎ tap a target on the map — compose the order',
  '◎ цель не выбрана': '◎ no target picked',
  ПРИКАЗ: 'ORDER',
  'убрать шаг': 'remove step',
  'план пуст — добавь шаги': 'plan is empty — add steps',
  '⏱{n}ч': '⏱{n}h',
  '⏱ +1ч': '⏱ +1h',
  '🎯{n}ч': '🎯{n}h',
  'Выбрать+': 'Select+',
  'Деж. вылет': 'Scramble',
  'голод: −25% на земле': 'starving: −25% on the ground',
  'блэкаут: радары и ПВО −50%': 'blackout: radars and AA −50%',
  '⚔ авто-штурм включён — флот сам штурмует вражеский мир по прибытии':
    '⚔ auto-storm on — the fleet storms the hostile world it arrives at by itself',
  Ускорить: 'Boost',
  '⚡ форс-марш: +50% скорости, −5% прочности за час хода':
    '⚡ forced march: +50% speed, −5% hull per hour underway',
  '⊕ тапайте свои флоты — соберите группу и отдайте общий приказ':
    '⊕ tap your fleets — build the group, then give a common order',
  Сюда: 'Go here',
  Огонь: 'Fire',
  'снять приказ': 'clear the order',
  '{n} флотов': '{n} fleets',
  '◎ приказ поставлен — флот исполнит план сам': '◎ order set — the fleet will run the plan itself',
  'Осталось: {r}': 'Remaining: {r}',
  'В очереди — ещё не начато.': 'Queued — not started yet.',
  'По готовности пополнит гарнизон/флот планеты.':
    "Joins the planet's garrison/fleet once finished.",
  '{r}: {now}/ч сейчас → {final}/ч по готовности': '{r}: {now}/h now → {final}/h once finished',
  '{n} кораблей': '{n} ships',
  '{n} уч.': '{n} members',
  '{n} ч': '{n} h',
  '{n}м': '{n}m',
  '{n}ч': '{n}h',
  '{d}д {h}ч': '{d}d {h}h',
  '{p}% карты': '{p}% of the map',
  '{s} кораблей · {tr} десанта': '{s} ships · {tr} troops',
  '{s}/{c} игроков': '{s}/{c} players',
  '{what} — не вышло: {err}': '{what} — failed: {err}',
  '{what} — скоро': '{what} — coming soon',
  '{who} отклонил предложение: {stance}': '{who} declined the proposal: {stance}',
  '{who} предлагает — нажмите, чтобы принять': '{who} is offering — tap to accept',

  // --- fleet panel / command bar ------------------------------------------------
  АТК: 'ATK',
  Авиагруппа: 'Air wing',
  'Авиагруппа в гарнизоне': 'Air wing in garrison',
  'Автономная крепость, возведённая в астероидное поле: {d} к обороне и {hp} прочности. Превращает безликий перекрёсток в укреплённый узел с орбитой и ПКО':
    'A standalone fortress raised in an asteroid field: {d} to defense and {hp} structure HP. Turns a faceless crossroads into a fortified node with orbit and AA.',
  Агрес: 'Aggr',
  Атака: 'Attack',
  'Атака / Оборона': 'Attack / Defense',
  'Боевая единица.': 'A combat unit.',
  'Боевая проекция самого командующего — флагман во главе родного флота: {a} атаки и {hp} корпуса. Но решает не это: его присутствие держит эскадру в кулаке, давая {b} к атаке и обороне всем кораблям рядом. Падёт — командующий лишается проекции, пока та не отстроится заново на родном мире.':
    "The commander's own combat projection — a flagship leading the home fleet: {a} attack and {hp} hull. But that's not what matters: its presence holds the squadron together, granting {b} attack/defense to every ship nearby. If it falls, the commander loses their projection until it's rebuilt at the home world.",
  'Боевой счёт': 'War record',
  'Боты не вступают в коалиции': 'Bots do not join coalitions',
  'Буровая платформа вгрызается в планету и добывает {m}⬢ в час. Улучшение позволяет копать глубже, чтобы добраться до самых богатых жил. Основа для строительства флота.':
    'A drilling rig gnaws into the planet, mining {m}⬢ per hour. Upgrades dig deeper to reach the richest veins. The foundation for building your fleet.',
  'В ЛС игроку': "To a player's DM",
  'В архив': 'Archive',
  'В казне': 'In the treasury',
  'В чат коалиции': 'To the coalition chat',
  ВЫ: 'YOU',
  ВЫКЛ: 'OFF',
  'Верфь авиагруппы': 'Air wing shipyard',
  Владелец: 'Owner',
  Влияние: 'Influence',
  'Вместимость трюма': 'Cargo capacity',
  'Вне сенсорного охвата — последний скан (мог устареть).':
    'Out of sensor range — last scan (may be stale).',
  Войти: 'Join',
  Восстановить: 'Restore',
  Время: 'Time',
  'Время постройки': 'Build time',
  Все: 'All',
  'Войти через Apple': 'Sign in with Apple',
  'Войти через Google': 'Sign in with Google',
  'Вход через Apple — скоро · ты вошёл гостем':
    'Sign in with Apple — coming soon · you entered as a guest',
  'Вход через Google — скоро · ты вошёл гостем':
    'Sign in with Google — coming soon · you entered as a guest',
  'Выход в меню': 'Exit to menu',
  Вы: 'You',
  'Выбрать →': 'Select →',
  Выставить: 'List',
  'Гарнизон на момент скана': 'Garrison when scanned',
  'Казармы нужны для защиты вашего мира от захватчиков. Тут живут ваши доблестные защитники.':
    'Barracks defend your world from invaders. Home to your valiant defenders.',
  Глобальный: 'Global',
  Дальность: 'Range',
  День: 'Day',
  'День {n}': 'Day {n}',
  '{h}ч': '{h}h',
  '<1ч': '<1h',
  'вход ещё {dur}': 'joinable {dur}',
  'вход закрыт': 'entry closed',
  Пароль: 'Password',
  'пароль (аккаунт создастся сам)': 'password (account auto-creates)',
  'Введите пароль (мин. 8 символов)': 'Enter a password (min 8 chars)',
  'Аккаунт создан': 'Account created',
  'Неверный пароль': 'Wrong password',
  'Регистрация отклонена': 'Registration refused',
  'Слишком часто — подождите': 'Too many attempts — wait a bit',
  'Вход отклонён': 'Login refused',
  'Сессия истекла — введите пароль ещё раз': 'Session expired — enter the password again',
  'все места заняты': 'all seats taken',
  'не удалось войти': 'could not join',
  'Десант на борту': 'Carrying troops',
  Дивизии: 'Divisions',
  'Дивизии ⇄ трюм (своб. {n})': 'Divisions ⇄ hold (free {n})',
  Дипломатия: 'Diplomacy',
  Отношения: 'Relations',
  'Открыть карточку игрока': 'Open player card',
  'Добывающая платформа, вгрызается в спёкшуюся кору мёртвого мира. Там, где аннигиляция выжгла всё живое, обнажилась чистая металлическая руда — станция качает {m}⬢ в час. Улучшение увеличивает добычу.':
    "A mining rig gnawing into a dead world's scorched crust. Where annihilation burned away all life, raw metal ore lies exposed — the station pumps {m}⬢ per hour. Upgrades raise the yield.",
  'Ещё раз «Назад» — выход': 'Press Back again to exit',
  'Ждём, пока хост начнёт…': 'Waiting for the host to start…',
  ЗАКРЫТЬ: 'CLOSE',
  ЗАПУСК: 'LAUNCH',
  'ЗАПУСК В ОДИНОЧКУ': 'LAUNCH SOLO',
  ЗАЩ: 'DEF',
  'Загрузка погружает дивизию в трюм. Выгрузка высаживает её на этот мир.':
    'Loading takes a division into the hold. Unloading lands it on this world.',
  'Задача: ✦ {n} (мир — 50, сектор — 10) или уничтожение соперников.':
    'Goal: ✦ {n} (a world — 50, a province — 10) or eliminate your rivals.',
  'Закрепить размер и положение': 'Lock size and position',
  Закрыть: 'Close',
  Заявиться: 'Sign up',
  Здания: 'Buildings',
  Земля: 'Ground',
  'ИГРАТЬ СЕЙЧАС': 'PLAY NOW',
  ИИ: 'AI',
  Имя: 'Name',
  Исследовать: 'Research',
  История: 'History',
  Герои: 'Heroes',
  'Герои — командиры флота': 'Heroes — fleet commanders',
  'У каждого героя своё дерево навыков — тапни узел, чтобы увидеть, что он открывает, и изучи по требованиям и стоимости. Открытые узлы дают способности (активные, с дальностью и перезарядкой) или пассивки. Погибший герой возрождается на столице.':
    "Each hero has its own skill tree — tap a node to see what it unlocks, then learn it once its requirements and cost are met. Unlocked nodes grant abilities (active, with range and a cooldown) or passives. A fallen hero respawns at your capital.",
  'Истребительная эскадрилья': 'Fighter squadron',
  'Канал «{ch}» пуст.': 'Channel "{ch}" is empty.',
  Класс: 'Class',
  Коалиция: 'Coalition',
  'Командный бой: ВКЛ': 'Team battle: ON',
  'Командный бой: выкл': 'Team battle: off',
  'Компактный режим меню': 'Compact panel mode',
  'одна сторона — союзники': 'one side = allies',
  Командир: 'Commander',
  'Конвейер верфи': 'Shipyard conveyor',
  Корпорация: 'Corporation',
  'Корабли в гарнизоне': 'Ships in garrison',
  'Корабли — тап для характеристик': 'Ships — tap for specs',
  Корпус: 'Hull',
  Крейсер: 'Cruiser',
  Крылья: 'Wings',
  Купить: 'Buy',
  Курс: 'Move',
  'Лёгкий разведывательный корпус. Быстрый (ход {sp}) и почти неслышный (сигнатура {sig}) — чертит карту пустоты там, куда боится соваться линейный флот.':
    'A light recon hull. Fast (speed {sp}) and almost silent (signature {sig}) — it maps the void where a battle fleet fears to go.',
  'Маршрут проходит через миры <b>{names}</b>, с кем у вас <b>мир</b>. Мирного прохода нет — движение сюда объявит <b>войну</b>.':
    'This route crosses worlds held by <b>{names}</b>, with whom you are at <b>peace</b>. There is no peaceful passage — advancing here declares <b>war</b>.',
  'Медленный бронированный носитель ({hp} корпуса, трюм на {c}) — своих пушек почти нет, вся его сила в эскадрильях, что он несёт. Держите его позади и запускайте авиагруппу по цели кнопкой «🛩 Запустить эскадрилью».':
    'A slow armored carrier ({hp} hull, hold for {c}) — almost no guns of its own, all its strength is in the wing it carries. Keep it behind and launch the wing at a target with "🛩 Launch squadron".',
  'Мир типа «{pt}» — {mods}': 'A {pt} world — {mods}',
  'Тип: «{pt}» — {mods}': 'Type: “{pt}” — {mods}',
  'Нет дивизий.': 'No divisions.',
  'Суммарная атака дивизии.': "The division's total attack.",
  'Суммарная защита дивизии.': "The division's total defense.",
  'Суммарные очки здоровья дивизии.': "The division's total hit points.",
  'Конструктор дивизий': 'Division builder',
  'Редактор шаблонов: состав слотов и доктрина дивизий.':
    'The template editor: slot composition and division doctrine.',
  'Миров под контролем': 'Worlds held',
  'Мобильное оперативное соединение кораблей. Выберите его, чтобы отдавать приказы на манёвр, орбиту и удар по врагу.':
    'A mobile task force of ships. Select it to give maneuver, orbit and strike orders.',
  Модули: 'Modules',
  'НАСТРОЙКА СХВАТКИ': 'SKIRMISH SETUP',
  НАСТРОЙКИ: 'SETTINGS',
  'НЕТ ТЕЛЕМЕТРИИ': 'NO TELEMETRY',
  Назад: 'Back',
  МАТЧИ: 'MATCHES',
  'Нажмите «Курс» и тапните цель — все выбранные флоты пойдут туда (проложат маршрут и встанут). «Слить» сплавляет группу в один флот (дальние сначала подлетят). Shift- или Ctrl/⌘-клик по флоту добавляет его в группу; Shift-рамка по пустому месту выделяет несколько.':
    'Press "Move" and tap a destination — every selected fleet routes there and stops. "Merge" fuses the group into one fleet (distant ones fly in first). Shift- or Ctrl/⌘-click a fleet to add it to the group; Shift-drag empty space to box-select several.',
  'Наземная армия ⇄ гарнизон': 'Ground army ⇄ garrison',
  'Наземные части': 'Ground units',
  'Наземные части обороняют ваши миры. Их можно погрузить на флот для захвата вражеских миров.':
    'Ground units defend your worlds. Load them onto a fleet to capture enemy worlds.',
  'Наземный конвейер': 'Ground conveyor',
  'Налоговая управа имперского образца: сама ничего не добывает, но ставит на учёт население мира и поднимает его кредитный сбор на {b}.':
    "An imperial-style tax office: produces nothing itself, but registers the world's population and lifts its credit take by {b}.",
  'Напишите первое сообщение.': 'Write the first message.',
  Настройки: 'Settings',
  'Не исследовано — вне сенсоров и радаров. Содержимое неизвестно.':
    'Unexplored — outside sensor and radar range. Contents unknown.',
  Нейтрал: 'Neutral',
  'Нет дивизий — мобилизуй по шаблону ниже.': 'No divisions — mobilize from a template below.',
  'Нет лотов на покупку': 'No buy orders',
  'Нет лотов на продажу': 'No sell orders',
  'Носитель (◈) несёт эскадрильи (△). Запускайте авиагруппу из панели выбранного флота кнопкой «🛩 Запустить эскадрилью».':
    'A carrier (◈) holds squadrons (△). Launch the wing from the selected fleet\'s panel with "🛩 Launch squadron".',
  'ОБЪЯВИТЬ ВОЙНУ': 'DECLARE WAR',
  'ОБЪЯВИТЬ ВОЙНУ?': 'DECLARE WAR?',
  'Это мир дружественной фракции. Вы хотите объявить войну <b>{names}</b>?':
    "This is a friendly faction's world. Do you want to declare war on <b>{names}</b>?",
  ДА: 'YES',
  НЕТ: 'NO',
  '⚔ выберите чужой мир для штурма': "⚔ pick someone else's world to storm",
  '⚔ штурм невозможен: на борту нет десанта, а мир защищён — погрузите войска':
    '⚔ assault impossible: no landing force aboard and the world is defended — load troops',
  '⚔ внимание: на борту нет десанта — защищённый мир штурмом не взять':
    '⚔ warning: no landing force aboard — a defended world cannot be stormed',
  'Ждёт ресурсы: {c}': 'Waiting for resources: {c}',
  'Управление скоростью': 'Speed control',
  'панель времени в матче — пауза и множители ускорения (1× — реальное время)':
    'the in-match time bar — pause and speed multipliers (1× is real time)',
  'полчаса в секунду': 'half an hour per second',
  'час в секунду': 'an hour per second',
  'два часа в секунду': 'two hours per second',
  '⚔ штурмовать можно только чужой мир': "⚔ only someone else's world can be stormed",
  'Корабли: {s} · Десант: {tr}': 'Ships: {s} · Landing: {tr}',
  'Авто-штурм': 'Auto-storm',
  'ОПЕРАТИВНАЯ ГРУППА': 'TASK GROUP',
  ОТМЕНА: 'CANCEL',
  'Обновите данные флотом или радаром.': 'Re-scan with a fleet or radar to refresh.',
  Оборона: 'Defense',
  'Оборона гарнизона': 'Garrison defense',
  Обстрел: 'Barrage',
  'Обстрел — огонь с дистанции': 'Barrage — firing from range',
  'Флоты с артиллерией бьют по врагу издалека, ещё до сближения — сосредоточь огонь на одной цели или дай флоту выбирать её самому. Толстая броня артиллерии слабая, её место позади линии, а не на передовой.':
    'Artillery fleets fire on the enemy from afar, before closing the distance — focus fire on one target, or let the fleet pick one itself. Artillery has thin armor, so keep it behind the line, not on the front.',
  'Описание метки (необязательно)…': 'Marker description (optional)…',
  'Осадная платформа': 'Siege Platform',
  Ответ: 'Return',
  'Отделите корабли в новый флот — он останется в том же секторе. Хотя бы один корабль остаётся; десант в трюме остаётся с исходным флотом.':
    'Peel ships into a new fleet — it stays in the same sector. At least one ship stays behind; carried troops stay with the original.',
  'Отделяет эскадрильи в отдельный быстрый флот — уводите его на удар, а носитель остаётся в строю. Нужен хотя бы один не-эскадрильный корабль. Контрится орбитальным ПВО.':
    'Splits the wing off into its own fast strike fleet — send it in while the carrier stays put. Needs at least one non-squadron ship left behind. Countered by orbital AA.',
  Отмена: 'Cancel',
  Отменить: 'Cancel',
  'Отменить — вернёт часть ресурсов и поставит на паузу':
    'Cancel — refunds part of the cost and pauses it',
  'Убрать из очереди': 'Remove from the queue',
  'Приостановлено {n}%': 'Paused {n}%',
  'Возобновить — доплатить остаток': 'Resume — pay the remainder',
  'Перезапуск — к выбору ботов': 'Restart — back to bot selection',
  'Отметить выбранную провинцию пингом': 'Mark the selected province with a ping',
  'Отметьте провинцию и отправьте — метка станет кликабельной (↪ камера).':
    'Mark a province and send — the marker becomes clickable (↪ jump the camera).',
  Отношение: 'Stance',
  'Отступление — не бесплатно': 'Retreat is not free',
  Отправить: 'Send',
  'Отправьте флот к этой системе (или расширьте радар), чтобы обнаружить её.':
    'Send a fleet toward this system (or extend radar) to detect it.',
  'Отход стоит −40% ТЕКУЩЕГО корпуса и щита (израненный флот теряет 40% остатка — отход не добивает) и даёт рывок скорости для бегства. Десант в высадке отступить не может; с орбиты вне боя корабль уходит свободно.':
    "Retreat costs −40% of CURRENT hull and shield (a wounded fleet loses 40% of what remains — retreat never finishes it off) and grants a speed burst to flee. Troops mid-landing can't retreat; a ship in orbit outside battle leaves freely.",
  Очки: 'Score',
  'Очки победы': 'Victory points',
  ПВО: 'AA',
  ПОБЕДА: 'WIN',
  'ПОСЛЕДНИЕ ДАННЫЕ ✦': 'LAST KNOWN ✦',
  ПРОСТОЙ: 'IDLE',
  'Палубная эскадрилья: стремительная (ход {sp}) и больно бьёт ({a} атаки), но брони почти нет ({hp} корпуса). Отделяется от носителя в отдельный быстрый флот и наносит удар с дистанции {r}. Контрится орбитальным ПВО — не гоните её на прикрытую ПВО планету.':
    "A carrier-borne wing: fast (speed {sp}) and hits hard ({a} attack), but almost no armor ({hp} hull). Splits off the carrier into its own fast fleet and strikes from range {r}. Countered by orbital AA — don't send it against an AA-covered world.",
  Пассив: 'Passive',
  'Пассивные бонусы': 'Passive bonuses',
  'Переподключение не удалось — войди заново': 'Reconnect failed — sign in again',
  'Перерабатывающий комплекс, превращающий руду и логистику в ликвидные кредиты — {c}¤ в час. Топливо для имперской бюрократии, верфей и наёмных эскадр.':
    'A refining complex turning ore and logistics into liquid credits — {c}¤ per hour. Fuel for imperial bureaucracy, shipyards and mercenary squadrons.',
  Пинг: 'Ping',
  'Планетарное сооружение.': 'A planetary structure.',
  'Под фильтр никто не подходит.': 'Nobody matches the filter.',
  Подтвердить: 'Confirm',
  'Покинуть сессию': 'Leave session',
  Покупка: 'Buy',
  'Флот -ваше оружие и защита. Здесь вы можете заказывать корабли для пополнения флота.':
    'The fleet is your weapon and shield. Order ships here to reinforce it.',
  'Построить здесь': 'Build here',
  'Наведи на объект слева — здесь появится его досье.':
    'Hover an object on the left — its dossier appears here.',
  Постройки: 'Structures',
  Принять: 'Accept',
  Провинции: 'Provinces',
  провинций: 'provinces',
  'Суверены — донат-валюта': 'Sovereigns — the donate currency',
  Продажа: 'Sell',
  Продать: 'Sell',
  Прозрачность: 'Transparency',
  Производит: 'Produces',
  Прочность: 'Structure HP',
  'РАЗДЕЛЕНИЕ ФЛОТА': 'SPLIT FLEET',
  РЫНОК: 'MARKET',
  Рынок: 'Market',
  'Рабочая лошадь линейного флота: {a} атаки, {hp} корпуса и трюм на {c}. Универсальный боевой корабль, одинаково уверенный в обороне и в наступлении.':
    "The battle line's workhorse: {a} attack, {hp} hull and a hold for {c}. A general-purpose warship, equally solid on offense and defense.",
  'Радарная сигнатура': 'Radar signature',
  'Радиус радара': 'Radar reach',
  Разведчик: 'Scout',
  Развернуть: 'Expand',
  'Размер h,w': 'Size h,w',
  'Реальное время': 'Real time',
  'С орбиты можно бомбардировать (изнашивает здания и замораживает их выпуск), но ПВО гарнизона достаёт до вас. Штурм высаживает десант против гарнизона.':
    "In orbit you can bombard (wears buildings and freezes their output), but the garrison's AA reaches you. Assault lands your troops against the garrison.",
  СВОДКИ: 'DISPATCHES',
  СЕЙЧАС: 'NOW',
  СКР: 'SPD',
  Сброс: 'Clear',
  Сводки: 'Dispatches',
  Свернуть: 'Collapse',
  'Сервер не нужен — свободные места займут боты.': 'No server needed — bots fill the open seats.',
  Сессия: 'Session',
  'Комплекс радаров просвечивает пространство вокруг вашего мира и ловит вражеские сигнатуры задолго до того, как они посмеют на вас напасть. Улучшения обеспечивают большее покрытие.':
    'A radar complex sees through the space around your world and catches enemy signatures long before they dare attack. Upgrades widen the coverage.',
  Скор: 'Spd',
  Скорость: 'Speed',
  Слить: 'Merge',
  'Слить…': 'Merge…',
  Снять: 'Detach',
  'Снять выделение': 'Deselect',
  'Снять выделение группы': 'Deselect group',
  Содержание: 'Upkeep',
  'Сообщение…': 'Message…',
  'Сообщений пока нет.': 'No messages yet.',
  Сообщения: 'Messages',
  'Сообщения — скоро': 'Messages — coming soon',
  'Сорт.': 'Sort',
  Станд: 'Std',
  'Стационарная зенитная батарея защищает воздушное пространство вашего мира и наносит {dmg} урона в час по кораблям на орбите. Кошмар для бомбардировщиков, повисших над планетой, и для налетающих эскадрилий. Захват мира не блокирует — это дело наземной обороны; батарея лишь выкашивает флот над головой.':
    "A stationary anti-air battery guards your world's airspace, dealing {dmg} damage per hour to ships in orbit. A nightmare for bombers hanging over the world and for raiding squadrons. Doesn't block capture (that's ground defense's job) — it just mows down the fleet overhead.",
  Стоимость: 'Cost',
  'Предложение: {stance}': 'Proposal: {stance}',
  'Стойка изменена: {stance}': 'Stance changed: {stance}',
  Столица: 'Capital',
  Стоп: 'Stop',
  'Строительный конвейер': 'Building conveyor',
  'Тапните мир.': 'Tap a world.',
  'тап — полное досье': 'tap for full specs',
  'Тащите за шапку, чтобы переместить': 'Drag the title bar to move',
  'Тяжёлая осадная платформа: {a} урона с дистанции {r}, но тонкая броня ({d} защиты). Её место за спинами крейсеров, откуда она крушит укрепления и верфи.':
    'A heavy siege platform: {a} damage from range {r}, but thin armor ({d} defense). Its place is behind the cruisers, from where it smashes fortifications and shipyards.',
  Удар: 'Strike',
  'Ударный носитель': 'Strike Carrier',
  Уровней: 'Tiers',
  ТЕХНОЛОГИИ: 'TECHNOLOGIES',
  Технологии: 'Technologies',
  ФЛОТ: 'FLEET',
  Фильтр: 'Filter',
  Флагман: 'Flagship',
  Флот: 'Fleet',
  // Авто-имена флотов (Bytro-стиль): тип соединения по размеру
  Звено: 'Wing',
  Эскадрилья: 'Flight',
  Эскадра: 'Squadron',
  Армада: 'Armada',
  // Карточка статистики мира (тап по имени планеты)
  'Сводка мира': 'World summary',
  Обозначение: 'Designation',
  'Вид / тип / местность': 'Kind / type / terrain',
  'Базовый выход/ч': 'Base output/h',
  '— перекос типа мира': '— world-type lean',
  'произв.': 'prod.',
  'Бонусы типа': 'Type bonuses',
  эскадрилий: 'squadrons',
  // 🔥 режим огня артиллерии — кнопка в командном ряду + пункты меню
  'Режим огня': 'Fire mode',
  'не стреляет': 'holds fire',
  'только после урона по флоту': 'only after the fleet takes damage',
  'по тем, с кем война': 'at declared enemies',
  'по любому, кроме пакта/союза': 'at anyone except pact/alliance',
  'Флоты на орбите': 'Fleets in orbit',
  Обновления: 'Updates',
  Фракция: 'Faction',
  // H3 — setup faction picker (pure passive house bonuses)
  'Фракция — пассивный бонус дома': 'Faction — the house passive bonus',
  '+{n}% экономика': '+{n}% economy',
  '+{n}% урон': '+{n}% damage',
  '+{n}% скорость флотов': '+{n}% fleet speed',
  '+{n}% радар': '+{n}% radar',
  ОЗ: 'HP',
  'Цвет шрифта': 'Font color',
  Цензура: 'Censorship',
  'ЧАТ — {ch}': 'CHAT — {ch}',
  'Чат коалиции пуст.<br>Отметьте провинцию пингом 📍 или напишите.':
    'The coalition chat is empty.<br>Mark a province with a ping 📍 or write something.',
  Человек: 'Human',
  'Шрифт, пт': 'Font, pt',
  'Штамп сообщений': 'Message stamp',
  Штурм: 'Assault',
  'Эшелонированный планетарный бастион. Поднимает оборону гарнизона на {d} и держит {hp} структурной прочности под орбитальным огнём. Последний рубеж осаждённого мира.':
    'A layered planetary bastion. Raises garrison defense by {d} and holds {hp} structure HP under orbital fire. The last line of a besieged world.',
  Юнитов: 'Units',

  // --- market resource tabs (MARKET_RES) -----------------------------------------
  Металл: 'Metal',
  Пища: 'Food',
  Энергия: 'Energy',
  Микро: 'Micro',

  // --- diplomatic stance (STANCE_RU, via stanceRu()) ---------------------------
  Война: 'War',
  Мир: 'Peace',
  Союз: 'Alliance',

  // --- kernel rejection codes (ERR_RU, via errText()) --------------------------
  'предложение уже отправлено': 'a proposal is already pending',
  'боты не вступают в коалиции': 'bots do not join coalitions',

  // --- corp mock panel (role/presence dictionaries, CORP_TABS) ------------------
  Глава: 'Leader',
  Офицер: 'Officer',
  Участник: 'Member',
  'в матче': 'in a match',
  Обзор: 'Overview',
  Участники: 'Members',
  Казна: 'Treasury',
  Владения: 'Holdings',
  Войны: 'Wars',
  Заявка: 'Applicant',

  // --- corporation cabinet (AVA-C1/C2, live) ------------------------------------
  'создала корпорацию': 'created the corporation',
  'приняла заявку': 'accepted the application',
  'отклонила заявку': 'declined the application',
  исключила: 'kicked',
  'сменила роль': 'changed a role',
  'передала главенство': 'transferred headship',
  'покинула корпорацию': 'left the corporation',
  'расформировала корпорацию': 'disbanded the corporation',
  'движение влияния': 'influence movement',
  'флаг готовности': 'readiness flag',
  'выдала медаль': 'granted a medal',
  'выдала предмет в аренду': 'rented out an item',
  'вернула арендованный предмет': 'returned a rented item',
  AvA: 'AvA',
  '{n} участников': '{n} members',
  'Без корпорации': 'No corporation',
  'Владения — скоро': 'Holdings — coming soon',
  Вызвать: 'Challenge',
  'Готовность корпорации': 'Corporation readiness',
  'Готовые к войне': 'Ready for war',
  Журнал: 'Log',
  'Журнал виден главе и офицерам.': 'The log is visible to the head and officers.',
  'Заявиться в состав': 'Join the roster',
  'История видна главе и офицерам.': 'History is visible to the head and officers.',
  'Мои вызовы': 'My challenges',
  'Моя готовность': 'My readiness',
  'Моя роль': 'My role',
  'Название (3–24 символа)': 'Name (3–24 characters)',
  'Найти и подать заявку': 'Find and apply',
  Отклонить: 'Decline',
  'Пассивные бонусы владений придут вместе с мета-слоем секторов — пока их нет.':
    'Holding passive bonuses arrive with the sector meta-layer — not yet.',
  'Пока нет вызовов.': 'No challenges yet.',
  'Пока нет других корпораций.': 'No other corporations yet.',
  'Пока пусто.': 'Nothing yet.',
  'Покинуть корпорацию': 'Leave the corporation',
  'Публичная лента AvA': 'Public AvA feed',
  'Пул пуст.': 'The pool is empty.',
  'Расформировать корпорацию': 'Disband the corporation',
  Создать: 'Create',
  'Создать корпорацию': 'Create a corporation',
  'Тратится на вызов AvA (100 ⟡ по умолчанию) — кнопка «Вызвать» во вкладке «Войны».':
    'Spent on an AvA challenge (100 ⟡ by default) — the "Challenge" button in the "Wars" tab.',
  'Чат — скоро': 'Chat — coming soon',
  'в пул': 'to pool',
  'вызов нам': 'challenge to us',
  'вызов от нас': 'challenge from us',
  готов: 'ready',
  'да ✓': 'yes ✓',
  'ждёт ответа': 'awaiting response',
  'заперт — скоро бой': 'locked — battle soon',
  истёк: 'expired',
  'мета-карта секторов появится вместе со вторым контуром метагейма':
    'the sector meta-map arrives with the metagame’s second circuit',
  'набор ростера': 'roster window open',
  назначен: 'scheduled',
  отклонить: 'decline',
  отклонён: 'declined',
  отменён: 'cancelled',
  'передать главенство': 'transfer headship',
  победа: 'victory',
  'постоянный корп-чат ждёт мета-слой; журнал действий — во вкладке «Обзор»':
    'persistent corp chat awaits the meta-layer; the action log is in the "Overview" tab',
  принять: 'accept',
  снять: 'clear',
  состав: 'roster',
  'только глава': 'head only',
  '—': '—',

  // --- preset hero names (HeroLoadout, non-main; heroName() via t()) -----------
  Разрушитель: 'Destroyer',
  Авангард: 'Vanguard',
  Страж: 'Sentinel',

  Пехота: 'Infantry',
  Танк: 'Tank',
  // formation doctrines (formationStats, game.ts) — organisational labels, no combat bonus (BF-23)
  'Комбинированные войска': 'Combined arms',
  'Пехота и танки в одном строю': 'Infantry and tanks in one line',
  Окопались: 'Entrenched',
  '≥3 тяжёлой пехоты держат рубеж': '≥3 heavy infantry hold the line',
  'Танковый кулак': 'Armored fist',
  '≥3 танков — ударный клин': '≥3 tanks — a breakthrough wedge',
  // preset division template names (setupTemplates, game.ts)
  Линия: 'Line',
  Кулак: 'Fist',

  // --- hero grades (HERO_GRADES, heroes.ts) --------------------------------------
  Главный: 'Main',
  '{n} слота под модули': '{n} module slots',

  // --- hero abilities (HERO_ABILITIES, heroes.ts) --------------------------------
  Коридор: 'Corridor',
  Аннигиляция: 'Annihilate',
  Сбор: 'Rally',
  Разведка: 'Scan',
  'Раскрывает зону вокруг цели сквозь туман на время.':
    'Reveals an area around the target through the fog for a while.',
  Отзыв: 'Recall',
  'Мгновенно отзывает корабль-героя в столицу.': 'Instantly recalls the hero ship to the capital.',
  Бастион: 'Bulwark',

  // --- ship modules (SHIP_MODULES, ships.ts) -------------------------------------
  Щит: 'Shield',

  // --- ship hull names (SHIP_HULLS, ships.ts) -------------------------------------
  Носитель: 'Carrier',

  // --- lowercase fragments -------------------------------------------------------
  атака: 'attack',
  'без описания': 'no description',
  бомбардирует: 'bombarding',
  'в очередь: {what} на {at}': 'queued: {what} at {at}',
  'ваш лот': 'your lot',
  влияние: 'influence',
  'входящий вызов': 'incoming challenge',
  высадка: 'landing',
  гарнизон: 'garrison',
  'готов к следующему заказу': 'ready for next order',
  'данные мира': "a world's data",
  'данные о флотах': 'fleet data',
  десант: 'landing',
  'до {n} очк.': 'up to {n} pts.',
  'доминированием в галактике': 'by galactic domination',
  'достижением лимита очков': 'by score limit',
  'ещё {left}': '{left} left',
  завершён: 'ended',
  'загрузка матчей…': 'loading matches…',
  здание: 'building',
  'здесь пусто': "it's empty here",
  земля: 'ground',
  идёт: 'active',
  'истечением времени': 'on the clock',
  казна: 'treasury',
  'казна {who}': "{who}'s treasury",
  'кол-во': 'amount',
  командующий: 'commander',
  кораблей: 'ships',
  корабль: 'ship',
  'корпус {p}%': 'hull {p}%',
  космос: 'space',
  'матч завершён': 'the match has ended',
  'метка {loc}': 'marker {loc}',
  'мир {at}': 'world {at}',
  'на орбите': 'in orbit',
  'нажмите «Обновить список»': 'press "Refresh list"',
  'наземной армии здесь нет': 'no ground army here',
  'наземный юнит': 'ground unit',
  наземных: 'ground',
  'не удалось в архив': 'archiving failed',
  'не удалось восстановить': 'restore failed',
  'неизвестный заказ': 'unknown order',
  'в гарнизоне не осталось': 'none left in the garrison',
  нет: 'none',
  'трюм полон': 'the hold is full',
  ничья: 'a stalemate',
  'новый флот: {a} кораблей · у исходного останется {b}':
    'new fleet: {a} ships · original keeps {b}',
  'обновления доступны только в APK': 'updates are only available in the APK',
  оборона: 'defense',
  'оборона {p}': 'defense {p}',
  орбита: 'orbit',
  'очередь пуста': 'queue empty',
  'ошибка архива': 'archive error',
  'перезарядка {n}': 'rearming {n}',
  'победа: {who}': '{who} won',
  подписка: 'subscription',
  покупка: 'buy',
  'глобальный канал появится вместе с глобальным сервером':
    'the global channel arrives with the global server',
  построек: 'buildings',
  'построек не видели': 'none seen',
  'прицеливание отменено': 'aiming cancelled',
  'проверка: {msg}': 'check: {msg}',
  продажа: 'sell',
  'произв. {p}': 'prod {p}',
  пусто: 'empty',
  'радиус {r}': 'radius {r}',
  роль: 'role',
  'сборка {b}': 'build {b}',
  секторов: 'sectors',
  'сервер недоступен': 'server unreachable',
  'сервер недоступен — укажи адрес сервера': 'server unreachable — enter the server address',
  скоро: 'soon',
  'следующий раунд через': 'next round in',
  спокойно: 'quiet',
  'Строительная телеметрия врага недоступна': 'Enemy construction telemetry unavailable',
  'топливо {n}': 'fuel {n}',
  убрать: 'remove',
  'уничтожением соперников': 'by eliminating rivals',
  участников: 'members',
  вы: 'you',
  флот: 'fleet',
  флоты: 'fleets',
  'флоты {who}': "{who}'s fleets",
  оз: 'hp',
  цена: 'price',
  '— здесь возродятся и сменят модули герои': '— heroes respawn and re-fit modules here',
  '— проекция · +5% атаки/обороны этому флоту': '— projection · +5% attack/defense to this fleet',
  '↗ идёт к {dest} · прибытие через': '↗ en route to {dest} · arrives in',
  '↪ камера': '↪ camera',
  '⇄ биржа: {n} {res} за {paid} ¤ ({side})': '⇄ market: {n} {res} for {paid} ¤ ({side})',
  '⊗ Бомбардировать': '⊗ Bombard',
  '⊗ Прекратить бомбардировку': '⊗ Stop bombard',
  '⊟ флот разделён у {at}': '⊟ fleet split at {at}',
  '⏳ погрузка: {n} (≈1ч на единицу)': '⏳ loading: {n} (≈1h each)',
  '▲ Погрузить {u}': '▲ Load {u}',
  '▲ Улучшить {c}': '▲ Upgrade {c}',
  '▼ Выгрузить {u}': '▼ Unload {u}',
  '◆ новый радарный контакт ({size}) у {at}': '◆ new radar contact ({size}) at {at}',
  '● отключён от сервера': '● disconnected from server',
  '● подключён как {who}': '● connected as {who}',
  '● связь потеряна — переподключение…': '● connection lost — reconnecting…',
  '★ Сделать столицей': '★ Make capital',
  '☠ Потеряно своих': '☠ Own units lost',
  '☠️ флот {who} уничтожен': '☠️ a {who} fleet was destroyed',
  '⚔ Бой — {phase} · раунд {r}': '⚔ Battle — {phase} · round {r}',
  // combat forecast (ONB-6, fleet panel strike section)
  'десант возьмёт мир': 'the landing takes the world',
  'гарнизон устоит': 'the garrison holds',
  'затяжной пат': 'a drawn-out stalemate',
  '⚠ Враг идёт к {node}: прибытие через {dur}':
    '⚠ An enemy is heading for {node}: arrival in {dur}',
  '⚠ Враг у {node}!': '⚠ An enemy at {node}!',
  'Прогноз штурма: {v} · ~{r} р. · потери {a} дес. ({pa}%) / {d} гарн. ({pd}%)':
    'Assault forecast: {v} · ~{r} rounds · losses {a} landing ({pa}%) / {d} garrison ({pd}%)',
  'Прогноз по видимым составам, без бонусов местности, укреплений и технологий — реальный бой может отличаться.':
    'Forecast from visible compositions only — terrain, fortification and technology bonuses are not included; the real battle may differ.',
  '⚔ Война объявлена — флоты выдвигаются': '⚔ War declared — fleets advancing',
  '⚔ Уничтожено юнитов врага': '⚔ Enemy units destroyed',
  '⚔ Штурм': '⚔ Assault',
  '⚔ бой у {at} завершён — {res}': '⚔ battle at {at} ended — {res}',
  '⚔ штурм': '⚔ assault',
  '⚔️ бой у {at} ({phase})': '⚔️ battle at {at} ({phase})',
  '⚛ изучено: {tech}': '⚛ researched: {tech}',
  '⚡ Коалиция · {n} уч.': '⚡ Coalition · {n} members',
  '△ Сессия · {n} в матче': '△ Session · {n} in match',
  'Общий канал матча — вас слышат все участники.':
    'The match-wide channel — everyone in the match hears you.',
  '⛬ выберите флот для объединения': '⛬ pick a fleet to merge with',
  '⛬ флоты объединены у {at}': '⛬ fleets merged at {at}',
  '✓ актуально · локально {l} · сервер {r}': '✓ up to date · local {l} · server {r}',
  '✖ {who} отклонил: {stance}': '✖ {who} declined: {stance}',
  '🕊 {who} предлагает: {stance} — ответьте тем же в Дипломатии':
    '🕊 {who} offers {stance} — answer in kind in Diplomacy',
  '⏳ {who}: предложение отправлено — {stance}': '⏳ {who}: proposal sent — {stance}',
  '✗ GitHub ответил {s}': '✗ GitHub answered {s}',
  '✗ нет связи с GitHub (сеть / VPN?)': "✗ can't reach GitHub (network / VPN?)",
  '✗ ответ получен, но версия не распознана': "✗ got a response, but couldn't parse the version",
  '✦ {score}/{limit}: мир — 50, прочий сектор — 10, здания добавляют по уровню (у вас {w} миров, {s} секторов). Победа: ✦ {limit}, уничтожение соперников или доминирование.':
    '✦ {score}/{limit}: a world — 50, any other province — 10, buildings add per level (you hold {w} worlds, {s} provinces). Win at ✦ {limit}, by eliminating rivals, or by domination.',
  '⟜ стоит на трассе {lane} · {p}% пути': '⟜ holding on the {lane} lane · {p}% across',
  '⟳ переподключение…': '⟳ reconnecting…',
  '⤺ Отступить': '⤺ Retreat',
  '⬆️ {b} → L{lvl} на {at}': '⬆️ {b} → L{lvl} at {at}',
  '⬇ есть обновление → сборка {v}': '⬇ update available → build {v}',
  '🎯 автоприцел': '🎯 auto-target',
  '🎯 сосредоточенный огонь назначен': '🎯 focus fire set',
  '🎯 тапните вражеский флот для сосредоточенного огня · пустота = авто':
    '🎯 tap an enemy fleet to focus fire · empty space = auto',
  '🏆 ПОБЕДА': '🏆 VICTORY',
  '🏆 ПОБЕДА КОАЛИЦИИ': '🏆 COALITION VICTORY',
  '⚖️ НИЧЬЯ': '⚖️ DRAW',
  '💀 ПОРАЖЕНИЕ': '💀 DEFEAT',
  'Итоговый счёт': 'Final score',
  '{p}-е место из {n}': '{p} of {n}',
  Флоты: 'Fleets',
  Юниты: 'Units',
  Длительность: 'Duration',
  'Смотреть доску': 'View the board',
  '⟳ Играть ещё': '⟳ Play again',
  '⟳ Новый матч': '⟳ New match',
  'В меню': 'Menu',
  '🏗️ {b}: построено на {at}': '🏗️ {b} built at {at}',
  '💥 {b}: разрушено на {at}': '💥 {b} destroyed at {at}',
  '📍 Пинг': '📍 Ping',
  '📍 Пинг — отметить и отправить…': '📍 Ping — mark and send…',
  '📍 Пинг → {who}': '📍 Ping → {who}',
  '📍 Пинг → Коалиция': '📍 Ping → Coalition',
  '🕊 {who}: отношения → {stance}': '🕊 {who}: relations → {stance}',
  '🕵 Агент добыл разведданные: {what} — окно 24ч': '🕵 Agent got intel: {what} — a 24h window',
  '🕵 Агент провалился ({who}) — плата сгорела': '🕵 Agent failed ({who}) — the fee is gone',
  '🕵 Окно разведки': '🕵 Intel window',
  '🕵 Разведать мир · {c}¤': '🕵 Spy on the world · {c}¤',
  'Украсть данные казны · {c}¤ · шанс ~60% · окно 24ч (плата сгорает и при провале)':
    'Steal treasury data · {c}¤ · ~60% chance · 24h window (the fee is lost on failure too)',
  'Украсть данные о флотах · {c}¤ · шанс ~60% · окно 24ч (плата сгорает и при провале)':
    'Steal fleet data · {c}¤ · ~60% chance · 24h window (the fee is lost on failure too)',
  '🚀 {who} поднял флот с {at}': '🚀 {who} launched a fleet from {at}',
  '🚩 {who} захватил {at}': '🚩 {who} captured {at}',
  '🛡 Контрразведка: агент {who} пойман при попытке кражи ({what})!':
    '🛡 Counter-intel: agent {who} caught stealing ({what})!',
  '🛡 Контрразведка: утечка разведданных ({what}) — вор не установлен':
    '🛡 Counter-intel: an intel leak ({what}) — the thief is unknown',
  '🛩 Запустить эскадрилью ({n})': '🛩 Launch squadron ({n})',
  '🛩 дежурный вылет включён — эскадрилья бьёт врага в радиусе':
    '🛩 standing patrol on — the wing strikes any enemy in range',
  '🛩 дежурный вылет — только со стоянки в узле': '🛩 standing patrol — only from a parked node',
  '🛩 дежурный вылет — только когда флот свободен': '🛩 standing patrol — only when the fleet is free',
  '🛩 дежурный вылет: ВКЛ': '🛩 standing patrol: ON',
  '🛩 эскадрилья запущена — ведите её на цель': '🛩 squadron launched — steer it onto the target',

  // --- static markup (build.mjs, data-i18n) -------------------------------------
  '×1 — реальное время (час пути = час жизни, мир живёт и офлайн). Для быстрой партии выбери ×10–×100.':
    '×1 — real time (an hour of travel = an hour of life, the world runs offline too). For a quick game pick ×10–×100.',
  Аккаунт: 'Account',
  Активные: 'Active',
  Альянсы: 'Alliances',
  Архив: 'Archive',
  Верфь: 'Shipyard',
  'Войди в матч на вкладке «Игры» — здесь появятся ходы, требующие внимания.':
    'Join a match on the "Games" tab — moves needing your attention will show up here.',
  'Вход по позывному': 'Sign in by callsign',
  'Выбери матч из списка и войди, или обнови список.':
    'Pick a match from the list and join, or refresh it.',
  'Выберите свой домашний мир на карте, задайте число соперников-ботов и запускайте. Пустые места займут боты — выключите место, чтобы командовать меньшим сектором, или выключите все ради мирной одиночной песочницы для знакомства с интерфейсом.':
    'Pick your homeworld on the map, choose how many AI rivals join, then launch. Empty slots are taken by the AI — switch a slot OFF to command a smaller sector, or switch them all off for a peaceful solo sandbox to explore the interface.',
  'Выходные данные': 'Imprint',
  'Грань пустоты': 'Edge of the Void',
  Домой: 'Home',
  'Доступна новая сборка': 'A new build is available',
  Доступные: 'Available',
  Ещё: 'More',
  Игры: 'Games',
  'Кабинет корпорации': 'Corporation cabinet',
  'Нет матчей, ждущих приказа': 'No matches waiting on an order',
  'Новый командир': 'New Commander',
  'Добро пожаловать, командир. Флот ждёт приказа.': 'Welcome, commander. The fleet awaits your orders.',
  'Придумай позывной и пароль — так создаётся аккаунт.':
    'Choose a callsign and password — that creates your account.',
  'Имя командира': 'Commander name',
  'Повтор пароля': 'Repeat password',
  'Создать командира': 'Create commander',
  'Восстановить доступ': 'Recover access',
  'минимум 8 символов': 'at least 8 characters',
  'ещё раз': 'once more',
  'Введи имя командира': 'Enter a commander name',
  'Пароли не совпадают': 'Passwords do not match',
  'Почта (для восстановления)': 'Email (for recovery)',
  'Восстановление доступа': 'Account recovery',
  'Укажи почту аккаунта — пришлём ссылку для сброса пароля.':
    'Enter your account email — we will send a password-reset link.',
  'Отправить ссылку': 'Send link',
  'Новый пароль': 'New password',
  'Придумай новый пароль для входа.': 'Choose a new password to sign in.',
  'Сменить пароль': 'Change password',
  'Эта почта уже занята': 'That email is already in use',
  'Введите почту': 'Enter an email',
  'Если такая почта есть — прислали ссылку для сброса':
    'If that email exists, a reset link is on its way',
  'Ссылка недействительна или устарела': 'The link is invalid or expired',
  'Пароль изменён': 'Password changed',
  'переподключение — приказ не отправлен, повторите позже':
    'reconnecting — order not sent, try again shortly',
  'матч заполнен — все места заняты': 'match is full — every seat is taken',
  'вход в этот матч закрыт (окно приёма новых игроков истекло)':
    'this match is closed to new players (the entry window has elapsed)',
  'Позывной для аккаунта: 3–24 символа — буквы, цифры, _ или -':
    'Account callsign: 3–24 chars — letters, digits, _ or -',
  Обновить: 'Update',
  'Обновить список': 'Refresh list',
  'Одиночная игра': 'Solo game',
  'Одиночный режим': 'Solo mode',
  'Ожидание заказов': 'Awaiting orders',
  Выйти: 'Exit',
  Поддержка: 'Support',
  Позже: 'Later',
  Позывной: 'Callsign',
  'Политика конфиденциальности': 'Privacy Policy',
  'Проверить обновления': 'Check for updates',
  Рейтинг: 'Rank',
  'Рейтинги и альянсы откроются со стартом мета-слоя.':
    'Rankings and alliances unlock once the meta-layer launches.',
  'Рейтинги — скоро': 'Rankings — coming soon',
  Сводка: 'Summary',
  'Сезон ещё не начат': 'The season has not started',
  Сервер: 'Server',
  'Скорость времени': 'Time speed',
  '🧪 Песочница': '🧪 Sandbox',
  'Сменить командира': 'Switch commander',
  Сообщество: 'Community',
  'Тапните светящийся мир, чтобы выбрать старт': 'Tap a glowing world to choose your start',
  Уведомления: 'Notifications',
  Условия: 'Terms',
  Чат: 'Chat',
  'в сети': 'online',
  позывной: 'callsign',
  'реальное время': 'real time',
  'войти через': 'or sign in with',
  'корпорации · общие AvA-битвы · влияние': 'corporations · shared AvA battles · influence',
  'сезонный рейтинг по местам в матчах': 'a seasonal rank from match placements',
  '{ic} {name}: {stock} в казне · {flow}/ч (производство минус содержание войск и зданий)':
    '{ic} {name}: {stock} in the treasury · {flow}/h (production minus army and building upkeep)',
  '⚠ ДЕФИЦИТ — здания-потребители работают на 50%': '⚠ SHORTAGE — consuming buildings run at 50%',
  'Ярусы гидропонных оранжерей под спектральными лампами позволяют вашим подопечным питаться, ведь голод беспощаден. Выращивает {f}❖ в час. Ваши рабочие и воины едят каждый день, было бы глупо проиграть сражение из-за голодного обморока.':
    'Tiers of hydroponic greenhouses under spectral lamps feed those in your care — hunger is merciless. Grows {f}❖ per hour. Your workers and soldiers eat every day; it would be foolish to lose a battle to a hungry faint.',
  'Термоядерный реактор питает энергией ваши миры, он производит {e}↯ в час. Энергия — кровь ваших построек, ведь они работают не на волшебстве. При дефиците всё проседает до половины мощности.':
    "A fusion reactor powers your worlds, producing {e}↯ per hour. Energy is the lifeblood of your buildings — they don't run on magic. When it runs short, everything browns out to half output.",
  'Чистые цеха литографии печатают {m}▦ в час. Прожорлива к энергии и людям, зато её продукция ведёт эскадрильи и открывает осадные доктрины. Апгрейды окупаются собственной продукцией.':
    'Clean lithography halls print {m}▦ per hour. Hungry for power and people, but its output guides strike wings and unlocks siege doctrines. Upgrades pay for themselves in their own product.',
  'состав {n}/{s} · {rest}': 'composition {n}/{s} · {rest}',
  'Мобилизовать «{name}»': 'Mobilize "{name}"',
  // --- meta-progression («Прокачка», hub tab) -----------------------------------
  Прокачка: 'Progression',
  'Уровень {n}': 'Level {n}',
  '{got}/{need} XP': '{got}/{need} XP',
  'Очков: {n}': 'Points: {n}',
  '{n} очк.': '{n} pt.',
  Изучить: 'Unlock',
  Закрыто: 'Locked',
  'Опыт даётся за завершённые матчи: участие + счёт + победа. Прокачка не продаётся — только игра.':
    'XP comes from finished matches: participation + score + victory. Progression is never sold — play only.',
  '★ Опыт командующего: +{n}': '★ Commander XP: +{n}',
  '★ Новый уровень {lvl} — очко прокачки ждёт в меню «Прокачка»':
    '★ Level up to {lvl} — a progression point awaits in the Progression menu',
  Командование: 'Command',
  Экономика: 'Economy',
  Наука: 'Science',
  // --- arsenal witryna («Арсенал», hub tab, ARS-5) --------------------------------
  'Арсенал пуст': 'Arsenal empty',
  'войдите под аккаунтом на сервере с накоплением, чтобы увидеть коллекцию':
    'sign in with an account on a server with persistence to see your collection',
  Всё: 'All',
  Корпуса: 'Hulls',
  Фитинги: 'Fittings',
  стартовый: 'starter',
  дроп: 'drop',
  крафт: 'craft',
  аукцион: 'auction',
  лутбокс: 'lootbox',
  аренда: 'rent',
  Слот: 'Slot',
  модуль: 'module',
  фитинг: 'fitting',
  'В арсенале нет корпусов этого класса.': 'The arsenal has no hulls of this class.',
  '⚡ Арсенал живой: докупленное в матче видно здесь сразу, но начинает работать только когда ты это ПОСТРОИШЬ — постройка и логистика, не мгновенно.':
    '⚡ Live arsenal: anything bought during the match shows up here right away, but it only starts working once you BUILD it — construction and logistics, not instant.',
  'Ходовые школы': 'Helm Schools',
  '+5% к скорости всех флотов с первой секунды матча.':
    '+5% fleet speed from the first second of a match.',
  'Слаженные экипажи': 'Drilled Crews',
  '+5% к урону флотов и гарнизонов.': '+5% damage for fleets and garrisons.',
  'Дальняя разведка': 'Deep Recon',
  '+15% к радиусу всех радаров.': '+15% to every radar radius.',
  'Ветеран кампаний': 'Campaign Veteran',
  'Ещё +5% к скорости и урону — рефлексы старой гвардии.':
    "Another +5% speed and damage — the old guard's reflexes.",
  Хозяйственник: 'Quartermaster',
  '+10% к стартовой казне каждого матча.': '+10% starting treasury every match.',
  Индустриализация: 'Industrialization',
  '+5% к производству всех миров.': '+5% production on all worlds.',
  Госрезерв: 'State Reserve',
  'Ещё +20% к стартовой казне.': 'Another +20% starting treasury.',
  Магнат: 'Magnate',
  'Ещё +5% к производству — империя работает на вас.':
    'Another +5% production — the empire works for you.',
  Аспирантура: 'Postgraduate School',
  'Учёные совета начинают матч на +1 уровень.': 'Council scientists start the match +1 level.',
  'Открытый архив': 'Open Archive',
  '«Промышленная автоматизация» изучена с первой секунды.':
    '"Industrial Automation" is researched from the first second.',
  'Сеть институтов': 'Institute Network',
  'Учёные совета — ещё +1 уровень.': 'Council scientists — another +1 level.',
  'Орбитальная кафедра': 'Orbital Faculty',
  '«Орбитальная логистика» изучена с первой секунды.':
    '"Orbital Logistics" is researched from the first second.',
  // --- H4: ground-army designer (3 infantry lines + tank, officer premades) -------
  Мобилизация: 'Mobilization',
  '⚙ Конструктор': '⚙ Designer',
  Переименовать: 'Rename',
  'Урон по:': 'Damage vs:',
  живучесть: 'toughness',
  Ополчение: 'Militia',
  'Тяжёлая пехота': 'Heavy Infantry',
  Спецназ: 'Special Forces',
  Рейд: 'Raid',
  'Гвардия прорыва': 'Breakthrough Guard',
  'Железный рубеж': 'Iron Line',
  'Колонна снабжения': 'Supply Column',
  Штурмовик: 'Assault Leader',
  'Командир обороны': 'Defense Commander',
  Снабженец: 'Quartermaster',
  'Рейдовая доктрина': 'Raid Doctrine',
  '≥2 спецназа без ополчения': '≥2 special forces, no militia',
  'Людская волна': 'Human Wave',
  '≥4 ополчения — берут числом': '≥4 militia — winning by numbers',
  'Именной шаблон офицера: состав закреплён, редактировать нельзя.':
    "An officer's named template: composition locked, no editing.",
  'Дивизия — снапшот шаблона: правка шаблона в конструкторе не меняет уже собранные. На своём мире +1 HP/юнит/день.':
    'A division is a snapshot of its template: editing a design never touches armies already fielded. On your own world it heals +1 HP/unit/day.',
  'Постройки мира и строительный конвейер: состояние, уровни и улучшения.':
    "The world's buildings and its construction conveyor: condition, levels, upgrades.",
  Дивизия: 'Division',
  'Наземное соединение, собранное по шаблону. Обороняет мир; грузится на флот из панели флота.':
    'A ground formation mobilized from a template. Defends the world; loads onto a fleet from the fleet panel.',
  'Суммарная атака кораблей флота.': "The fleet's total ship attack.",
  'Суммарная защита кораблей флота.': "The fleet's total ship defense.",
  'Очки здоровья': 'Hit points',
  'Суммарная прочность кораблей флота.': "The fleet's total hull strength.",
  'Скорость перелёта — флот движется со скоростью самого медленного корабля.':
    'Travel speed — the fleet moves at its slowest ship.',
  Гарнизон: 'Garrison',
  'Численность наземных войск, обороняющих мир.': 'The ground troops defending the world.',
  'Пехота и техника на поверхности мира.': "Infantry and armour on the world's surface.",
  'Корабли, стоящие в гарнизоне мира (не на орбите).':
    "Ships parked in the world's garrison (not in orbit).",
  'Число построек на мире.': 'The number of buildings on the world.',
  'Тап по слоту меняет род войск: ополчение → тяжёлая пехота → спецназ → танк. Танки бьют любую пехоту; спецназ — единственная пехота, опасная танкам; тяжёлая пехота держит оборону.':
    'Tap a slot to cycle the unit type: militia → heavy infantry → special forces → tank. Tanks shred any infantry; special forces are the one infantry that threatens armour; heavy infantry holds the line.',
  '‹ назад': '‹ back',
  '🧪 Тесты · режим разработчика': '🧪 Tests · developer mode',

  // --- command chains (order queue / plan builder, CC-*) -----------------------
  '⚒ десант': '⚒ ground',
  '⚔ орбита': '⚔ orbital',
  '⚔ {who} объявил вам войну!': '⚔ {who} declared war on you!',

  // --- bot favour meter / stolen intel readout ----------------------------------
  'на грани войны': 'on the brink of war',
  эмбарго: 'embargo',
  дружелюбно: 'friendly',
  'Одобрение бота: {f}/{base} — {label}. Ниже {emb} бот вводит эмбарго на рынке, ниже {war} — объявляет войну.':
    'Bot approval: {f}/{base} — {label}. Below {emb} the bot embargoes the market, below {war} it declares war.',
  'казна: <b>{bag}</b> <em>{left}</em>': 'treasury: <b>{bag}</b> <em>{left}</em>',
  'флоты видны на карте <em>{left}</em>': 'fleets visible on the map <em>{left}</em>',
  'мир <b>{id}</b> раскрыт <em>{left}</em>': 'world <b>{id}</b> revealed <em>{left}</em>',

  // --- province pings / connect screen status -----------------------------------
  'Сначала выберите провинцию на карте': 'Select a province on the map first',
  'Сначала выберите провинцию': 'Select a province first',
  'метка {node}': 'marker {node}',
  'Подключение: {nick}…': 'Connecting: {nick}…',
  'Укажи адрес сервера': 'Enter the server address',
  'Неверный адрес сервера': 'Invalid server address',
  'Введи позывной': 'Enter a callsign',

  // --- science council (pre-match scientist pick + tech-window header) -------------
  'СОВЕТ УЧЁНЫХ': 'SCIENCE COUNCIL',
  '↩ В меню': '↩ Menu',
  'Выбрать учёного': 'Pick a scientist',
  '⚠ Совет закрепляется на весь матч. Рекомендованная пара уже выбрана — замените по вкусу.':
    '⚠ The council locks in for the whole match. A recommended pair is pre-selected — swap to taste.',
  'Кандидаты · нажмите, чтобы занять слот': 'Candidates · tap to fill a slot',
  'Закрепить и продолжить к выбору места →': 'Lock in and continue to start pick →',
  'Выберите двух учёных': 'Pick two scientists',
  '+1 слот исследования (генералист, без фокуса ветки)':
    '+1 research slot (a generalist, no branch focus)',
  'Открывает ветку «{br}»: {list}': 'Opens the {br} branch: {list}',
  'Фокус ветки «{br}»': '{br} branch focus',
  // --- tech-branch labels (tabs / chips / section heads) ---------------------------
  Эскадрильи: 'Squadrons',
  'Дом: {home} — одиночная песочница, без соперников · тапните светящийся мир, чтобы сменить':
    'Home: {home} — a solo sandbox, no rivals · tap another glowing world to change',
  'Дом: {home} — тапните другой светящийся мир, чтобы сменить':
    'Home: {home} — tap another glowing world to change',
  // --- rail icon labels + window headers -------------------------------------------
  Дипло: 'Diplo',
  Почта: 'Mail',
  Сон: 'Sleep',
  Корп: 'Corp',
  ДИПЛОМАТИЯ: 'DIPLOMACY',

  // --- steward window («Хранитель») + settings + end-of-match ---------------------
  'Хранитель ведёт оборону.': 'The Steward holds the line.',
  'Хранитель ведёт активную оборону.': 'The Steward runs an active defense.',
  'Пока вы спите: держит рубежи, поднимает дежурные эскадрильи и контратакует у своих миров, когда прогноз потерь приемлем.':
    'While you sleep: holds the borders, stands squadron patrols and counterstrikes at your own worlds when the loss forecast is acceptable.',
  'Управление вернётся через <b>{dur}</b>.': 'Control returns in <b>{dur}</b>.',
  'Пока вы спите: держит рубежи и отбивает атаки, застраивает очередь и торгует — без наступлений.':
    'While you sleep: holds the borders and repels attacks, keeps building and trading — no offensives.',
  'Вернуть управление': 'Take back control',
  '«Автопилот держит вас в игре — побеждает активная игра.» Оборонительная поза не ходит в атаку и не ведёт дипломатию.':
    '“Autopilot keeps you alive — active play wins.” The defensive posture never attacks and never negotiates.',
  '«Протокол Хранитель» ещё не изучен.': 'The “Steward Protocol” is not researched yet.',
  'Ветка <b>Командование</b>, открывается в <b>День 16</b> учёному <b>Куратор</b> (сейчас день {day}).':
    'The <b>Command</b> branch, opens on <b>Day 16</b> for the <b>Overseer</b> scientist (now day {day}).',
  'Изучите его в окне технологий — затем сможете передать место ИИ на время сна.':
    'Research it in the technology window — then you can hand your seat to the AI while you sleep.',
  'Открыть технологии': 'Open technologies',
  'Хранитель готов.': 'The Steward is ready.',
  'Передайте место доверенному ИИ, пока вы офлайн — он удержит рубежи и вернёт управление к сроку.':
    'Hand your seat to a trusted AI while you are offline — it holds the line and returns control on time.',
  Поза: 'Posture',
  'Активная оборона': 'Active defense',
  'Активная оборона: всё то же, плюс контрудар по врагу у своих миров при приемлемом прогнозе потерь (до 35%) и дежурные вылеты эскадрилий. Свою территорию не покидает.':
    'Active defense: everything above, plus a counterstrike at your own worlds when the loss forecast is acceptable (under 35%) and standing squadron patrols. It never leaves your territory.',
  'Передать на': 'Delegate for',
  '{h} ч': '{h} h',
  'Поза «Оборона»: держит и отбивает, застраивает очередь, торгует — без наступлений и дипломатии. Управление вернётся автоматически, с утренней сводкой.':
    'The “Defend” posture: holds and repels, keeps building and trading — no offensives, no diplomacy. Control returns automatically, with a morning report.',
  '😴 Хранитель принял командование (Оборона) — держит рубежи, пока вы спите.':
    '😴 The Steward took command (Defend) — holding the line while you sleep.',
  '😴 Хранитель принял командование (Активная оборона) — держит рубежи и контратакует у своих миров.':
    '😴 The Steward took command (Active defense) — holding the line and counterstriking at your own worlds.',
  '🎮 Вы вернули командование себе.': '🎮 You took command back.',
  'Журнал Хранителя': "Steward's journal",
  '{dur} назад': '{dur} ago',
  '🏃 Эвакуация с {node} → {to}: прогноз потерь {pct}%, крыльев уведено: {n}':
    '🏃 Evacuation from {node} → {to}: loss forecast {pct}%, wings withdrawn: {n}',
  '🚚 Паром выслан к {node} за гарнизоном': '🚚 A ferry dispatched to {node} for the garrison',
  '⚠ Гарнизон {node} не эвакуировать: транспорт не успевает (прогноз потерь {pct}%)':
    '⚠ The {node} garrison cannot be evacuated: no transport arrives in time (loss forecast {pct}%)',
  '⚔ Контрудар у {node}: прогноз потерь {pct}%': '⚔ Counterstrike at {node}: loss forecast {pct}%',
  '🛫 Дежурный вылет поднят у {node}': '🛫 A standing patrol raised at {node}',
  '🛡 Рубеж {node} удержан: прогноз потерь {pct}%': '🛡 The {node} line held: loss forecast {pct}%',
  '🚩 Подкрепление выслано к {node}: прогноз потерь {pct}%':
    '🚩 Reinforcement sent to {node}: loss forecast {pct}%',
  'Точка удержания': 'Hold point',
  'Снять точку': 'Unmark',
  '🚩 Держать': '🚩 Hold',
  '🚩 Назначить точкой удержания': '🚩 Mark as a hold point',
  'Решений за вахту: {n} — журнал в окне Хранителя.':
    "Decisions this watch: {n} — see the Steward window's journal.",
  '🌅 Хранитель вернул вам управление (была «Оборона»).':
    '🌅 The Steward returned control to you (posture was “Defend”).',
  '🌅 Хранитель вернул вам управление (была «Активная оборона»).':
    '🌅 The Steward returned control to you (posture was “Active defense”).',
  интерфейс: 'interface',
  'Радарная развёртка': 'Radar sweep',
  'вращающийся луч на карте — только вид, не влияет на обнаружение':
    'the rotating beam on the map — visual only, does not affect detection',
  'Прозрачность радарной развёртки': 'Radar sweep opacity',
  'Свои метки на карте': 'My map markers',
  'булавки 📍 ваших пингов — метки союзников видны всегда':
    "your own 📍 ping pins — allies' markers always show",
  'плотная панель сектора — меньше отступов, мельче шрифт (на ПК)':
    'a denser sector panel — smaller paddings and type (PC)',
  Графика: 'Graphics',
  'Свечение и ореолы': 'Glow & haloes',
  'мягкое сияние вокруг миров, флотов и границ — выключите ради чёткой карты и скорости':
    'soft bloom around worlds, fleets and borders — turn off for a crisp, faster map',
  'Звёздный фон': 'Star backdrop',
  'дрейфующие туманности и звёзды на фоне — выключите для плоского фона':
    'drifting nebulae and stars in the background — turn off for a flat backdrop',
  'Счётчик FPS': 'FPS counter',
  'показывать кадры в секунду в углу — для проверки производительности':
    'show frames per second in the corner — to check performance',
  вкл: 'on',
  выкл: 'off',
  ГОТОВО: 'DONE',
  '⟳ К выбору ботов': '⟳ Back to setup',

  // --- suggested-callsign wordlist -----------------------------------------------
  Носорог: 'Rhino',
  Комета: 'Comet',
  Гадюка: 'Viper',
  Орион: 'Orion',
  Вектор: 'Vector',
  Сокол: 'Falcon',
  Титан: 'Titan',
  Квазар: 'Quasar',
  // --- constructor («Верфь») — the unified loadout tab ------------------------
  КОНСТРУКТОР: 'CONSTRUCTOR',
  'Конструктор — оснащение кораблей, эскадрилий, армии и героев':
    'Constructor — outfit ships, squadrons, army and heroes',
  Корабли: 'Ships',
  Армия: 'Army',
  '{n} слота под модули (по размеру корпуса)': '{n} module slots (by hull size)',
  'пусто — выбери модуль': 'empty — pick a module',
  'снять модуль': 'remove module',
  Оружие: 'Weapon',
  Защита: 'Defense',
  Система: 'System',
  'Доступные модули — для слота «{s}»': 'Available modules — for the «{s}» slot',
  'Доступные модули — все слоты заняты': 'Available modules — all slots full',
  'слот «{s}»': '«{s}» slot',
  'Типизированные слоты: модуль встаёт только в свой тип. <b>Серые</b> — не для свободного слота или уже стоят.':
    'Typed slots: a module fits only its own type. <b>Greyed</b> — not for a free slot, or already installed.',
  'Итог с модулями': 'Total with modules',
  'пересчёт вживую': 'live recalc',
  'Корпус ×{n}': 'Hull ×{n}',
  'Модули ×{n}': 'Modules ×{n}',
  Итого: 'Total',
  'Построить ×{n} →': 'Build ×{n} →',
  'Лоадаут фиксируется при постройке. Готовый корабль не переоснастить — только построить новый с другим набором.':
    "Loadout locks in on build. A finished ship can't be refitted — build a new one with a different set.",
  'нет своих миров': 'no worlds of yours',
  '«{what}» переезжает в конструктор следующим кирпичом.':
    '«{what}» moves into the constructor in the next brick.',
  '⚒ заказано: {n}× {hull}': '⚒ ordered: {n}× {hull}',
  'Корпус недоступен.': 'Hull unavailable.',
  бесплатно: 'free',
  // stat / resource words used by the module-effect chips and cost lines
  корпус: 'hull',
  щит: 'shield',
  скорость: 'speed',
  трюм: 'cargo',
  радар: 'radar',
  металла: 'metal',
  кредитов: 'credits',
  энергии: 'energy',
  еды: 'food',
  микроэлектроники: 'microelectronics',
  // --- hero window / deploy flow (окно героя, развёртывание) --------------------
  Способности: 'Abilities',
  Активировать: 'Activate',
  'КД {h}': 'CD {h}',
  'нет слотов': 'no slots',
  установлен: 'installed',
  погиб: 'lost',
  'в пути': 'in transit',
  'перк развёртывания': 'deploy perk',
  '⚓ выберите свой мир{fl}{al} — там поднимется корабль героя':
    "⚓ pick your world{fl}{al} — the hero's ship rises there",
  ' / свой флот': ' / own fleet',
  ' / мир союзника': " / ally's world",
  '✨ выберите мир-цель на карте': '✨ pick a target world on the map',
  '✖ каст отменён': '✖ cast cancelled',
  '✖ развёртывание отменено': '✖ deploy cancelled',
  'Цель…': 'Target…',
  // --- division / formation builder (конструктор дивизий) ----------------------
  'Итог по формации': 'Formation summary',
  'Доктрина состава': 'Composition doctrine',
  'Стоимость мобилизации': 'Mobilization cost',
  'Нет шаблонов.': 'No templates.',
  'Смешай рода войск — состав задаёт доктрину.':
    'Mix troop types — the composition sets a doctrine.',
  '{n}/{s} юнитов · тапни слот, чтобы менять род войск':
    '{n}/{s} units · tap a slot to change the troop type',
  'Тап по слоту: пусто → пехота → танк. Мобилизация дивизии — в панели своего мира (вкладка «Дивизии»).':
    "Tap a slot: empty → infantry → tank. Mobilize the division in your world's panel (the «Divisions» tab).",
  // --- build ETA / misc --------------------------------------------------------
  Стройка: 'Building',
  изучено: 'researched',
  'Ещё раз «Назад» — выход из матча': 'Press Back again to leave the match',
  // --- static H4 headers / steward toggle (build.mjs [data-i18n]) --------------
  'КОНСТРУКТОР ДИВИЗИЙ': 'DIVISION BUILDER',
  'ХРАНИТЕЛЬ · ИИ НА СОН': 'STEWARD · AI WHILE ASLEEP',
  'Хранитель — передать ИИ на сон': 'Steward — hand to the AI while asleep',
  // --- Bytro-карточка армии: ХП-бар, сводка, платный ремонт, кап линии огня ----
  'Мгновенный ремонт всего корпуса за кредиты': 'Instant full-hull repair for credits',
  Состав: 'Composition',
  скауты: 'scouts',
  боевые: 'combat',
  артиллерия: 'artillery',
  транспорты: 'transports',
  флагман: 'flagship',
  рой: 'swarm',
  всего: 'total',
  'бьют {n} юнитов': '{n} units firing',
  'форс-марш': 'forced march',
  'рывок отхода': 'retreat dash',
  'по самому медленному; техи/фракция/местность — на переходе':
    'at the slowest hull; tech/faction/terrain apply per leg',
  Трюм: 'Cargo hold',
  Радар: 'Radar',
  'Сводка армии': 'Army summary',
  '‹ Назад к карточке': '‹ Back to the card',
  'Линия огня': 'Firing line',
  'В залпе бьют максимум {n} юнитов — сильнейшие первыми; все сверх капа только впитывают урон.':
    'At most {n} units fire per volley — the strongest first; everyone beyond the cap only soaks damage.',
  'Текущая/полная прочность армии. Чинится у своего мира с верфью — или мгновенно за кредиты.':
    'Current/full army hull. Mends over your world with a repair yard — or instantly for credits.',
  'Аблятивный щит: принимает урон первым и бесплатно восстанавливается вне боя.':
    'Ablative shield: takes damage first and recharges for free out of combat.',
  // --- настройки: цвета сторон -------------------------------------------------
  'Цвета сторон': 'Side colours',
  'Свой цвет': 'Your colour',
  'вы на карте и в панелях — форма несёт тип, цвет несёт сторону':
    'you on the map and in panels — the shape carries the type, the colour carries the side',
  Нейтральные: 'Neutrals',
  'ничейные миры и неопознанные силы': 'unowned worlds and unidentified forces',
  'Палитра соперников': 'Rival palette',
  '«дальтоник» — оттенки, различимые при цветослепоте':
    '«colourblind» — hues distinguishable with colour vision deficiency',
  классика: 'classic',
  тёплая: 'warm',
  дальтоник: 'colourblind',
  'Вернуть цвета по умолчанию': 'Reset colours to defaults',
  // --- ECON-3: экспресс-ремонт за металл ---------------------------------------
  'Экспресс-ремонт у своего дока за металл': 'Express repair at your own dock for metal',
  // --- ECON-4: рыночная комиссия ------------------------------------------------
  'к получению после комиссии {p}%: {n} ¤': 'you receive after the {p}% fee: {n} ¤',
  'в эскроу уйдёт {n} ¤ · комиссию {p}% платит получатель кредитов':
    'escrow: {n} ¤ · the {p}% fee is paid by whoever receives the credits',
  // --- fleet-command hover tooltips (what each command button does) -------------
  'выберите планету — флот пойдёт к ней по звёздным трассам':
    'pick a planet — the fleet routes to it along the star lanes',
  'отменить текущее движение флота': "cancel the fleet's current movement",
  'лететь к чужому миру и высадить десант при подходе':
    'fly to an enemy world and land troops on arrival',
  'тап по карте — собрать приказ: ждать · курс · штурм · обстрел':
    'tap the map to compose an order: wait · move · assault · barrage',
  'применить способность героя из состава флота':
    "use a hero ability from the fleet's roster",
  'сосредоточить огонь артиллерии по вражескому флоту с дистанции':
    'focus artillery fire on an enemy fleet from standoff range',
  'когда артиллерия стреляет сама: пассив · ответ · станд · агрес':
    'when artillery fires on its own: passive · return · standard · aggressive',
  'объединить выбранные флоты в один': 'merge the selected fleets into one',
  'отделить часть кораблей пришвартованного флота в новый':
    'peel some ships off a docked fleet into a new one',
  'дополнительные приказы': 'extra orders',
  'добавлять флоты в группу по одному тапу': 'add fleets to the group one tap at a time',
  'форс-марш: +50% скорости ценой −5% прочности за час хода':
    'forced march: +50% speed at the cost of −5% hull per hour under way',
  'флот сам штурмует вражеский мир по прибытии':
    'the fleet storms an enemy world by itself on arrival',
  'эскадрилья автоматически бьёт врага в радиусе':
    'the squadron automatically hits enemies within range',
  // --- REL-7 seat/faction picker ------------------------------------------------
  'занято': 'taken',
  'свободно': 'free',
  'слотов': 'slots',
  'ВЫБРАТЬ': 'CHOOSE',
  'Выбор фракции': 'Choose Faction',
  'Выберите фракцию и стартовую позицию. Занятые места отмечены серым.':
    'Choose your faction and starting position. Taken seats are marked grey.',

  // --- sandbox panel (dev-only build, prototype/src/sandbox.ts) ----------------
  'ПЕСОЧНИЦА': 'SANDBOX',
  'Переключатели': 'Toggles',
  'Команды': 'Commands',
  'Прекратить войну со всеми фракциями': 'End the war with every faction',
  'Войны прекращены: {n} — отношения нейтральные': 'Wars ended: {n} — relations are neutral',
  'Вы ни с кем не воюете': 'You are not at war with anyone',
  'нет игрока': 'no player',
};
