// ENGLISH locale. Key → text, mirroring localization/ru.ts.
//
// A key missing here falls back to the Russian source (visible and honest), so an
// untranslated string shows up in Russian rather than as a raw key. The locale
// guard in prototype/src/i18n.test.ts fails on any key present in ru.ts but not here.
export const en: Record<string, string> = {
  // --- data — Имена игровых ДАННЫХ (data/*.json + таблицы прототипа), через tData().
  'data.aa': 'aa',
  'data.artillery': 'artillery',
  'data.asteroid-field': 'Asteroid field',
  'data.barracks': 'Barracks',
  'data.barren': 'Barren',
  'data.bomber': 'bomber',
  'data.carrier': 'carrier',
  'data.credit-refinery': 'Credit Refinery',
  'data.credits': 'credits',
  'data.cruiser': 'cruiser',
  'data.crystalline': 'Crystalline',
  'data.dead-world': 'Dead World',
  'data.debris-field': 'Debris Field',
  'data.deep-void': 'Deep Void',
  'data.dense-nebula': 'Dense Nebula',
  'data.derelict-graveyard': 'Derelict Graveyard',
  'data.dropship': 'dropship',
  'data.empty-space': 'Empty Space',
  'data.energy': 'energy',
  'data.fighter-squadron': 'fighter squadron',
  'data.food': 'food',
  'data.fort': 'Fort',
  'data.fortified-infrastructure': 'Fortified Infrastructure',
  'data.fortress-world': 'Fortress World',
  'data.front': 'front',
  'data.fusion-plant': 'Fusion Plant',
  'data.gas-giant': 'Gas Giant',
  'data.ground': 'ground',
  'data.heavy-infantry': 'heavy infantry',
  'data.hero': 'hero',
  'data.hydroponics-farm': 'Hydroponics Farm',
  'data.industrial-automation': 'Industrial Automation',
  'data.ion-storm': 'Ion Storm',
  'data.irradiated': 'Irradiated',
  'data.metal': 'metal',
  'data.metal-mine': 'Metal Mine',
  'data.microelectronics': 'microelectronics',
  'data.microelectronics-fab': 'Microelectronics Fab',
  'data.microelectronics-fabrication': 'Microelectronics Fabrication',
  'data.militia': 'militia',
  'data.nebula': 'Nebula',
  'data.oceanic': 'Oceanic',
  'data.open-space': 'Open space',
  'data.orbital-aa': 'Orbital AA',
  'data.orbital-logistics': 'Orbital Logistics',
  'data.planet': 'Planet',
  'data.radar-array': 'Radar Array',
  'data.rear': 'rear',
  'data.relic-world': 'Relic World',
  'data.ringworld': 'Ringworld',
  'data.salvage-metal-rig': 'Salvage Metal Rig',
  'data.scout': 'scout',
  'data.siege': 'siege',
  'data.siege-doctrine': 'Siege Doctrine',
  'data.solar-flare-zone': 'Solar Flare Zone',
  'data.space': 'space',
  'data.special-forces': 'special forces',
  'data.squadron': 'squadron',
  'data.strike-carrier': 'strike carrier',
  'data.tank': 'tank',
  'data.tax-office': 'Tax Office',
  'data.terran': 'Terran',
  'data.void-fortress': 'Void Fortress',
  'data.volcanic': 'Volcanic',

  // --- diplo — Дипломатия: названия отношений между игроками.
  'diplo.stance.alliance': 'Alliance',
  'diplo.stance.pact': 'Pact',
  'diplo.stance.peace': 'Peace',
  'diplo.stance.war': 'War',

  // --- err — Отказы ядра (kernel rejection codes). Ключ выводится из кода: E_NO_CAPACITY → err.no-capacity.
  'err.already': 'already in effect',
  'err.already-fitted': 'that fitting is already installed',
  'err.already-offered': 'a proposal is already pending',
  'err.already-unlocked': 'that node is already unlocked',
  'err.bad-effect': 'the ability is misconfigured',
  'err.bad-payload': 'malformed order',
  'err.bad-spawn': 'a hero cannot be deployed here',
  'err.bad-target': 'invalid target',
  'err.bombarded': 'construction under bombardment',
  'err.bot-alliance': 'bots do not join coalitions',
  'err.chat-rate': 'give it a couple of seconds',
  'err.chat-target': 'recipient not found',
  'err.chat-text': 'empty message',
  'err.conditions-unmet': 'conditions not met',
  'err.consent-required': 'the other side must consent',
  'err.cooldown': 'the ability is recharging',
  'err.fleet-busy': 'fleet busy',
  'err.forbidden': 'action forbidden',
  'err.hero-alive': 'the hero already commands a ship',
  'err.hero-cap': 'deployed-hero limit reached',
  'err.hero-dead': 'the hero is dead — wait for the respawn',
  'err.hero-not-deployed': 'the hero is not deployed — raise a ship first',
  'err.insufficient': 'insufficient resources',
  'err.internal': 'internal error',
  'err.limit': 'limit reached',
  'err.no-ability': 'unknown ability',
  'err.no-artillery': 'no artillery',
  'err.no-capacity': 'the hold is full',
  'err.no-capital': 'no capital to recall to',
  'err.no-effect': 'that effect is not implemented yet',
  'err.no-fitting': 'unknown fitting',
  'err.no-fleet': 'fleet not found',
  'err.no-funds': 'insufficient funds',
  'err.no-hero': 'hero not found',
  'err.no-node': 'unknown skill-tree node',
  'err.no-planet': 'world not found',
  'err.no-player': 'player not found',
  'err.no-ships': 'no ships',
  'err.no-shipyard': 'needs a shipyard/spaceport',
  'err.no-slots': 'all fitting slots are taken',
  'err.no-target': 'no target',
  'err.no-troops': 'the world is defended — an assault needs troops aboard',
  'err.not-destructible': 'this world cannot be destroyed',
  'err.not-equipped': 'the hero does not have that ability',
  'err.out-of-range': 'out of range',
  'err.own-planet': 'this is your own world',
  'err.requires': 'unlock the preceding node first',
  'err.research-slots-full': 'all research slots are full',
  'err.respawn-cooldown': 'the hero is still recovering',
  'err.same-location': 'fleet is already here',
  'err.too-early': 'too early',
  'err.unknown-building': 'unknown building',
  'err.unknown-technology': 'unknown technology',
  'err.unknown-unit': 'unknown unit',
  'err.wrong-branch': 'that node belongs to another branch',
  'err.wrong-orbit': 'invalid orbit',
  'err.wrong-sector': 'invalid sector type',

  // --- hero — Герои: грейды, способности (имя + описание).
  'hero.ability.annihilate.desc': 'Destroys a planet in range — it becomes a dead world.',
  'hero.ability.annihilate.name': 'Annihilate',
  'hero.ability.bulwark.desc': 'A temporary shield: +defense to your fleets near the hero.',
  'hero.ability.bulwark.name': 'Bulwark',
  'hero.ability.corridor.desc': 'Opens a temporary corridor lane to a nearby world; your fleets travel it faster.',
  'hero.ability.corridor.name': 'Corridor',
  'hero.ability.rally.desc': 'A battle cry: a temporary extra aura bonus for your fleets near the hero.',
  'hero.ability.rally.name': 'Rally',
  'hero.ability.recall.desc': 'Instantly recalls the hero ship to the capital.',
  'hero.ability.recall.name': 'Recall',
  'hero.ability.scan.desc': 'Reveals an area around the target through the fog for a while.',
  'hero.ability.scan.name': 'Scan',
  'hero.grade.common': 'Common',
  'hero.grade.legendary': 'Legendary',
  'hero.grade.main': 'Main',
  'hero.grade.rare': 'Rare',

  // --- hud — Постоянный интерфейс матча: верхняя панель ресурсов.
  'hud.resource.credits': 'Credits',
  'hud.resource.energy': 'Energy',
  'hud.resource.food': 'Food',
  'hud.resource.metal': 'Metal',
  'hud.resource.microelectronics': 'Microelectronics',

  // --- market — Биржа: вкладки ресурсов.
  'market.res.energy': 'Energy',
  'market.res.food': 'Food',
  'market.res.metal': 'Metal',
  'market.res.microelectronics': 'Micro',

  // --- ship — Корабли: корпуса и модули (имя + описание).
  'ship.hull.cruiser': 'Cruiser',
  'ship.hull.dropship': 'Carrier',
  'ship.hull.scout_drone': 'Scout Drone',
  'ship.hull.siege_lance': 'Siege Lance',
  'ship.module.battery.desc': '+30% to attack.',
  'ship.module.battery.name': 'Battery',
  'ship.module.plating.desc': '+25% hull HP.',
  'ship.module.plating.name': 'Plating',
  'ship.module.shield.desc': '+30% to defense.',
  'ship.module.shield.name': 'Shield',
  'ship.module.targeting.desc': '+15% to attack and defense.',
  'ship.module.targeting.name': 'Targeting',
  'ship.module.thruster.desc': '+20% to speed.',
  'ship.module.thruster.name': 'Thruster',

  // --- tech — Дерево технологий: названия веток.
  'tech.branch.command': 'Command',
  'tech.branch.ground': 'Ground',
  'tech.branch.missile': 'Missiles',
  'tech.branch.space': 'Space',
  'tech.branch.squadron': 'Squadrons',
};
