// ENGLISH locale. Key → text, mirroring localization/ru.ts.
//
// A key missing here falls back to the Russian source (visible and honest), so an
// untranslated string shows up in Russian rather than as a raw key. The locale
// guard in prototype/src/i18n.test.ts fails on any key present in ru.ts but not here.
export const en: Record<string, string> = {
  // --- acc / browser — Аккаунты (вход, регистрация, сессия) и браузер матчей.
  'acc.bad-pass': 'Wrong password',
  'acc.created': 'Account created',
  'acc.join-closed': 'entry closed',
  'acc.join-failed': 'could not join',
  'acc.login-refused': 'Login refused',
  'acc.mail-taken': 'That email is already in use',
  'acc.nick.rule': 'Account callsign: 3–24 chars — letters, digits, _ or -',
  'acc.pass.rule': 'Enter a password (min 8 chars)',
  'acc.rate-limited': 'Too many attempts — wait a bit',
  'acc.reconnect-failed': 'Reconnect failed — sign in again',
  'acc.reconnecting': '⟳ reconnecting…',
  'acc.register-refused': 'Registration refused',
  'acc.seats-full': 'all seats taken',
  'acc.server-down': 'server unreachable',
  'acc.session-expired': 'Session expired — enter the password again',
  'browser.archive': 'Archive',
  'browser.archive-error': 'archive error',
  'browser.archive-failed': 'archiving failed',
  'browser.day': 'Day {n}',
  'browser.empty': "it's empty here",
  'browser.finished': 'ended',
  'browser.free': 'free',
  'browser.goal.map': '{p}% of the map',
  'browser.goal.score': 'up to {n} pts.',
  'browser.join': 'Join',
  'browser.join-window': 'joinable {dur}',
  'browser.left.days': '{d}d {h}h',
  'browser.left.hours': '{h}h',
  'browser.left.soon': '<1h',
  'browser.loading': 'loading matches…',
  'browser.players': '{s}/{c} players',
  'browser.refresh-hint': 'press "Refresh list"',
  'browser.restore': 'Restore',
  'browser.restore-failed': 'restore failed',
  'browser.running': 'active',
  'browser.server-down': 'server unreachable — enter the server address',
  'browser.slots': 'slots',
  'browser.solo': 'Solo mode',
  'browser.solo.hint': 'No server needed — bots fill the open seats.',
  'browser.taken': 'taken',

  // --- ai — Красный ИИ: условия конца матча и отказы дежурного вылета.
  'ai.end.domination': 'by galactic domination',
  'ai.end.elimination': 'by eliminating rivals',
  'ai.end.over': 'the match has ended',
  'ai.end.score': 'by score limit',
  'ai.end.timeout': 'on the clock',
  'ai.sortie.docked-only': '🛩 standing patrol — only from a parked node',
  'ai.sortie.idle-only': '🛩 standing patrol — only when the fleet is free',

  // --- arsenal — «Арсенал»: коллекция аккаунта, фильтр, пустое состояние.
  'arsenal.empty': 'Arsenal empty',
  'arsenal.empty.hint':
    'sign in with an account on a server with persistence to see your collection',
  'arsenal.filter.all': 'All',
  'arsenal.kind.fitting': 'Fittings',
  'arsenal.kind.hull': 'Hulls',
  'arsenal.kind.module': 'Modules',
  'arsenal.origin.auction': 'auction',
  'arsenal.origin.craft': 'craft',
  'arsenal.origin.drop': 'drop',
  'arsenal.origin.lootbox': 'lootbox',
  'arsenal.origin.rent': 'rent',
  'arsenal.origin.starter': 'starter',

  // --- auth — Вход и регистрация: позывной, сторонние провайдеры.
  'auth.apple.soon': 'Sign in with Apple — coming soon · you entered as a guest',
  'auth.commander': 'Commander',
  'auth.google.soon': 'Sign in with Apple — coming soon · you entered as a guest',
  'auth.google.soon': 'Sign in with Google — coming soon · you entered as a guest',
  'auth.need-mail': 'Enter an email',
  'auth.need-name': 'Enter a commander name',
  'auth.need-nick': 'Enter a callsign',
  'auth.pass-mismatch': 'Passwords do not match',
  'auth.recover.sent': 'If that email exists, a reset link is on its way',
  'auth.reset.bad-link': 'The link is invalid or expired',
  'auth.reset.done': 'Password changed',

  // --- back — Кнопка «Назад» (APK/десктоп): подтверждение выхода.
  'back.confirm': 'Press Back again to exit',
  'back.confirm.match': 'Press Back again to leave the match',

  // --- callsign — Позывные ботов.
  'callsign.comet': 'Comet',
  'callsign.falcon': 'Falcon',
  'callsign.orion': 'Orion',
  'callsign.quasar': 'Quasar',
  'callsign.rhino': 'Rhino',
  'callsign.titan': 'Titan',
  'callsign.vector': 'Vector',
  'callsign.viper': 'Viper',

  // --- card — Карточка игрока (тап по гербу): фракция, владения, боевой счёт.
  'card.close': 'CLOSE',
  'card.combat': 'War record',
  'card.commander': 'commander',
  'card.diplomacy': 'Diplomacy',
  'card.faction': 'Faction',
  'card.kills': '⚔ Enemy units destroyed',
  'card.losses': '☠ Own units lost',
  'card.score': 'Score',
  'card.score.goal': 'WIN',
  'card.stances': 'Relations',
  'card.units': 'Units',
  'card.worlds': 'Worlds held',

  // --- cargo — Погрузка десанта: отказы трюма и гарнизона.
  'cargo.garrison-empty': 'none left in the garrison',
  'cargo.hold-full': 'the hold is full',

  // --- chat / spy — Переписка (сессия и коалиция) и вкладка шпионажа.
  'chat.coalition.empty':
    'The coalition chat is empty.<br>Mark a province with a ping 📍 or write something.',
  'chat.empty': 'No messages yet.',
  'chat.head.coalition': '⚡ Coalition · {n} members',
  'chat.head.session': '△ Session · {n} in match',
  'chat.input.ph': 'Message…',
  'chat.jump': '↪ camera',
  'chat.members': '{n} members',
  'chat.open-card': 'Open player card',
  'chat.ping': 'Mark the selected province with a ping',
  'chat.session.note': 'The match-wide channel — everyone in the match hears you.',
  'chat.tab.coalition': 'Coalition',
  'chat.tab.session': 'Session',
  'chat.you': 'You',
  'spy.log.empty': 'no attempts yet',
  'spy.log.title': 'JOURNAL',
  'spy.note':
    'Attempt: {c}¤ · ~60% chance · 24h intel window · a failure burns the fee. World recon — the 🕵 button on an enemy planet card.',
  'spy.op.fleets': 'fleets',
  'spy.ops.empty': 'no opponents',
  'spy.ops.title': 'OPERATIONS',
  'spy.windows.empty': 'no active windows — steal intel with an operation below',
  'spy.windows.title': 'ACTIVE INTEL WINDOWS',

  // --- chat.win — Плавающее окно чата (десктоп): каналы, настройки окна, штамп.
  'chat.ping.mark': 'marker {node}',
  'chat.ping.need-province': 'Select a province on the map first',
  'chat.ping.need-province.short': 'Select a province first',
  'chat.tab.global': 'Global',
  'chat.win.censor': 'Censorship',
  'chat.win.collapse': 'Collapse',
  'chat.win.color': 'Font color',
  'chat.win.color.premium': 'subscription',
  'chat.win.drag': 'Drag the title bar to move',
  'chat.win.empty': 'Channel "{ch}" is empty.',
  'chat.win.empty.hint': 'Write the first message.',
  'chat.win.expand': 'Expand',
  'chat.win.font': 'Font, pt',
  'chat.win.opacity': 'Transparency',
  'chat.win.pin': 'Lock size and position',
  'chat.win.send': 'Send',
  'chat.win.settings': 'Settings',
  'chat.win.size': 'Size h,w',
  'chat.win.stamp': 'Message stamp',
  'chat.win.stamp.day': 'Day',
  'chat.win.stamp.real': 'Real time',
  'chat.win.stamp.time': 'Time',
  'chat.win.title': 'CHAT — {ch}',

  // --- cmd — Командная панель флота: приказы, режим огня артиллерии, способности героя.
  'cmd.assault': 'Assault',
  'cmd.assault.hint': 'fly to an enemy world and land troops on arrival',
  'cmd.auto-assault': 'Auto-storm',
  'cmd.auto-assault.hint': 'the fleet storms an enemy world by itself on arrival',
  'cmd.barrage': 'Barrage',
  'cmd.barrage.hint': 'focus artillery fire on an enemy fleet from standoff range',
  'cmd.cast': 'Cast',
  'cmd.cast.cooldown': 'CD {h}',
  'cmd.cast.hint': "use a hero ability from the fleet's roster",
  'cmd.cast.needs-target': 'target on map',
  'cmd.cast.self': 'in place',
  'cmd.fire.aggressive': 'Aggr',
  'cmd.fire.aggressive.hint': 'at anyone except pact/alliance',
  'cmd.fire.hint': 'when artillery fires on its own: passive · return · standard · aggressive',
  'cmd.fire.passive': 'Passive',
  'cmd.fire.passive.hint': 'holds fire',
  'cmd.fire.return': 'Return',
  'cmd.fire.return.hint': 'only after the fleet takes damage',
  'cmd.fire.standard': 'Std',
  'cmd.fire.standard.hint': 'at declared enemies',
  'cmd.fire.title': 'Fire mode',
  'cmd.forced-march': 'Boost',
  'cmd.forced-march.hint': 'forced march: +50% speed at the cost of −5% hull per hour under way',
  'cmd.merge': 'Merge',
  'cmd.merge.hint': 'merge the selected fleets into one',
  'cmd.merge.pick': 'Merge…',
  'cmd.more': 'More',
  'cmd.more.hint': 'extra orders',
  'cmd.move': 'Move',
  'cmd.move.hint': 'pick a planet — the fleet routes to it along the star lanes',
  'cmd.multiselect': 'Select+',
  'cmd.multiselect.hint': 'add fleets to the group one tap at a time',
  'cmd.selection.many': '{n} FLEETS',
  'cmd.selection.one': 'FLEET',
  'cmd.split': 'Split',
  'cmd.split.hint': 'peel some ships off a docked fleet into a new one',
  'cmd.standing-sortie': 'Scramble',
  'cmd.standing-sortie.hint': 'the squadron automatically hits enemies within range',
  'cmd.stop': 'Stop',
  'cmd.stop.hint': "cancel the fleet's current movement",
  'cmd.target': 'Target',
  'cmd.target.hint': 'tap the map to compose an order: wait · move · assault · barrage',

  // --- codex — Кодекс: карточка здания/юнита/модуля (строки характеристик) и статьи-термины.
  'codex.hub.close': 'CLOSE',
  'codex.hub.empty': 'Nothing found',
  'codex.hub.search.aria': 'Search the codex',
  'codex.hub.search.ph': 'Search: unit, building, term…',
  'codex.hub.sec.building': 'Buildings',
  'codex.hub.sec.mechanic': 'Mechanics',
  'codex.hub.sec.unit': 'Units',
  'codex.hub.title': 'CODEX',
  'codex.row.aa': 'AA',
  'codex.row.atk-def': 'Attack / Defense',
  'codex.row.build-time': 'Build time',
  'codex.row.cargo': 'Cargo capacity',
  'codex.row.class': 'Class',
  'codex.row.cost': 'Cost',
  'codex.row.garrison-defense': 'Garrison defense',
  'codex.row.hp': 'Structure HP',
  'codex.row.hull': 'Hull',
  'codex.row.levels': 'Tiers',
  'codex.row.produces': 'Produces',
  'codex.row.radar': 'Radar reach',
  'codex.row.range': 'Range',
  'codex.row.score': 'Victory points',
  'codex.row.signature': 'Radar signature',
  'codex.row.slot': 'Slot',
  'codex.row.speed': 'Speed',
  'codex.row.upkeep': 'Upkeep',
  'codex.tag.building': 'building',
  'codex.tag.fitting': 'fitting',
  'codex.tag.ground-unit': 'ground unit',
  'codex.tag.mechanic': 'mechanic',
  'codex.tag.module': 'module',
  'codex.tag.ship': 'ship',
  'codex.term.async.body':
    'The world runs in real time and keeps going 24/7 — even after you leave. Orders take real hours: set a course, close the game, come back to the result. This is not turn-based — drop in, issue orders, drop out.',
  'codex.term.async.title': 'Asynchronous world',
  'codex.term.capture.body':
    'Capturing a world is two-phase. First enter orbit and beat the defenders in space; if the world holds a garrison, land troops (a ground division from the hold). Sky first, then ground.',
  'codex.term.capture.title': 'Orbit and landing',
  'codex.term.coalition.body':
    'Diplomacy lets you sign pacts and alliances, but a coalition is capped by combined strength — you cannot gang everyone up on one player. The cap keeps the balance of power and stops a snowball from crushing the game.',
  'codex.term.coalition.title': 'Coalition cap',
  'codex.term.fog.body':
    'You see only what is near your forces and radars; the rest is hidden by fog or shown from memory (the last thing you saw there). Scouts and radar widen your view — keep your eyes open.',
  'codex.term.fog.title': 'Fog of war',
  'codex.term.lanes.body':
    'Fleets travel not in straight lines but along star lanes between worlds — the route is built automatically. Lane nodes can be intercepted: an enemy met on the way is a battle.',
  'codex.term.lanes.title': 'Star lanes',
  'codex.term.score.body':
    'Points accrue from what you hold: a world — 50, any other sector — 10, buildings add per level. Reach the score threshold to win. Other paths to victory: eliminating rivals or domination.',
  'codex.term.score.title': 'Victory points',
  'codex.term.upkeep.body':
    'Fleets and buildings cost a daily fee. Mine income minus upkeep = your net balance; go negative and the treasury drains. Build economy before army.',
  'codex.term.upkeep.title': 'Upkeep',
  'codex.value.hours': '{n} h',
  'codex.value.levels-upgradable': '{n} (upgradeable)',
  'codex.value.per-day': '{n} {r}/day',
  'codex.value.per-hour': '{n} {r}/h',
  'codex.value.per-level': '{n} / level',

  // --- comms — Меню связи: ростер сессии, одобрение ботов, окна интела, предложения.
  'comms.bots-no-coalition': 'Bots do not join coalitions',
  'comms.favour.brink': 'on the brink of war',
  'comms.favour.embargo': 'embargo',
  'comms.favour.friendly': 'friendly',
  'comms.favour.note':
    'Bot approval: {f}/{base} — {label}. Below {emb} the bot embargoes the market, below {war} it declares war.',
  'comms.filter.empty': 'Nobody matches the filter.',
  'comms.global.soon': 'the global channel arrives with the global server',
  'comms.intel.fleets': 'fleets visible on the map <em>{left}</em>',
  'comms.intel.treasury': 'treasury: <b>{bag}</b> <em>{left}</em>',
  'comms.intel.world': 'world <b>{id}</b> revealed <em>{left}</em>',
  'comms.offer.incoming': '{who} is offering — tap to accept',
  'comms.offer.sent': 'a proposal is already pending',
  'comms.provinces': 'provinces',
  'comms.spy.fleets':
    'Steal fleet data · {c}¤ · ~60% chance · 24h window (the fee is lost on failure too)',
  'comms.spy.treasury':
    'Steal treasury data · {c}¤ · ~60% chance · 24h window (the fee is lost on failure too)',
  'comms.stance-changed': '🕊 {who}: relations → {stance}',
  'comms.stance-changed.short': 'Stance changed: {stance}',
  'comms.tag.player': 'PLAYER',
  'comms.war-declared': '⚔ {who} declared war on you!',
  'comms.you': 'YOU',

  // --- corp — Кабинет корпорации и войны альянсов (AvA): состав, заявки, готовность, вызовы.
  'corp.apply': 'Sign up',
  'corp.audit.accept': 'accepted the application',
  'corp.audit.create': 'created the corporation',
  'corp.audit.decline': 'declined the application',
  'corp.audit.disband': 'disbanded the corporation',
  'corp.audit.influence': 'influence movement',
  'corp.audit.kick': 'kicked',
  'corp.audit.leave': 'left the corporation',
  'corp.audit.medal': 'granted a medal',
  'corp.audit.ready': 'readiness flag',
  'corp.audit.rent': 'rented out an item',
  'corp.audit.rent-return': 'returned a rented item',
  'corp.audit.role': 'changed a role',
  'corp.audit.transfer': 'transferred headship',
  'corp.browse.empty': 'No other corporations yet.',
  'corp.browse.title': 'Find and apply',
  'corp.card.influence': 'influence',
  'corp.card.members': 'members',
  'corp.card.none': 'No corporation',
  'corp.card.role': 'role',
  'corp.chat.soon': 'Chat — coming soon',
  'corp.chat.soon.hint':
    'persistent corp chat awaits the meta-layer; the action log is in the "Overview" tab',
  'corp.close': 'Close',
  'corp.create.go': 'Create',
  'corp.create.name-ph': 'Name (3–24 characters)',
  'corp.create.title': 'Create a corporation',
  'corp.disband': 'Disband the corporation',
  'corp.empty': 'Nothing yet.',
  'corp.history': 'History',
  'corp.history.private': 'History is visible to the head and officers.',
  'corp.holdings.note': 'Holding passive bonuses arrive with the sector meta-layer — not yet.',
  'corp.holdings.soon': 'Holdings — coming soon',
  'corp.holdings.soon.hint': 'the sector meta-map arrives with the metagame’s second circuit',
  'corp.influence': 'Influence',
  'corp.influence.hint':
    'Spent on an AvA challenge (100 ⟡ by default) — the "Challenge" button in the "Wars" tab.',
  'corp.leave': 'Leave the corporation',
  'corp.log': 'Log',
  'corp.log.private': 'The log is visible to the head and officers.',
  'corp.members.count': '{n} members',
  'corp.my-role': 'My role',
  'corp.overview.name': 'Corporation',
  'corp.ready.clear': 'clear',
  'corp.ready.corp': 'Corporation readiness',
  'corp.ready.lead-only': 'head only',
  'corp.ready.mine': 'My readiness',
  'corp.ready.no': 'none',
  'corp.ready.set': 'ready',
  'corp.ready.to-pool': 'to pool',
  'corp.ready.yes': 'yes ✓',
  'corp.request.accept': 'accept',
  'corp.request.reject': 'decline',
  'corp.role.head': 'Leader',
  'corp.role.member': 'Member',
  'corp.role.officer': 'Officer',
  'corp.role.recruit': 'Applicant',
  'corp.tab.comms': 'Chat',
  'corp.tab.holdings': 'Holdings',
  'corp.tab.members': 'Members',
  'corp.tab.overview': 'Overview',
  'corp.tab.treasury': 'Treasury',
  'corp.tab.wars': 'Wars',
  'corp.transfer-lead': 'transfer headship',
  'corp.war.accept': 'Accept',
  'corp.war.ava': 'AvA',
  'corp.war.by-us': 'challenge from us',
  'corp.war.cancelled': 'cancelled',
  'corp.war.challenge': 'Challenge',
  'corp.war.decline': 'Decline',
  'corp.war.declined': 'declined',
  'corp.war.draw': 'a stalemate',
  'corp.war.expired': 'expired',
  'corp.war.feed': 'Public AvA feed',
  'corp.war.finished': 'ended',
  'corp.war.incoming': 'incoming challenge',
  'corp.war.join-roster': 'Join the roster',
  'corp.war.locked': 'locked — battle soon',
  'corp.war.mine': 'My challenges',
  'corp.war.none': 'No challenges yet.',
  'corp.war.pending': 'awaiting response',
  'corp.war.pool': 'Ready for war',
  'corp.war.pool-empty': 'The pool is empty.',
  'corp.war.roster': 'roster window open',
  'corp.war.roster-label': 'roster',
  'corp.war.roster-open': 'roster window is open',
  'corp.war.scheduled': 'scheduled',
  'corp.war.to-us': 'challenge to us',
  'corp.war.win': 'victory',
  'corp.you': 'you',

  'codex.build-here': 'Build here',
  'codex.close': 'CLOSE',

  // --- data — Имена игровых ДАННЫХ (data/*.json + таблицы прототипа), через tData().
  'data.aa': 'aa',
  'data.artillery': 'artillery',
  'data.asteroid-field': 'Asteroid field',
  'data.barracks': 'Barracks',
  'data.barren': 'Barren',
  'data.bomber': 'bomber',
  'data.carrier': 'carrier',
  'data.credit-refinery': 'Credit Refinery',
  'data.cargo-bay': 'Cargo Bay',
  'data.radar-module': 'Radar Module',
  'data.ion-engine': 'Ion Engine',
  'data.targeting-array': 'Targeting Array',
  'data.ablative-plating': 'Ablative Plating',
  'data.shield-booster': 'Shield Booster',
  'data.credits': 'credits',
  'data.cruiser': 'cruiser',
  'data.crystalline': 'Crystalline',
  'data.dead-world': 'Dead World',
  'data.debris-field': 'Debris Field',
  'data.deep-void': 'Deep Void',
  'data.dense-nebula': 'Dense Nebula',
  'data.derelict-graveyard': 'Derelict Graveyard',
  'data.dropship': 'dropship',
  'data.empty-space': 'Empty Space',
  'data.energy': 'energy',
  'data.fighter-squadron': 'fighter squadron',
  'data.food': 'food',
  'data.fort': 'Fort',
  'data.fortified-infrastructure': 'Fortified Infrastructure',
  'data.fortress-world': 'Fortress World',
  'data.front': 'front',
  'data.fusion-plant': 'Fusion Plant',
  'data.gas-giant': 'Gas Giant',
  'data.ground': 'ground',
  'data.heavy-infantry': 'heavy infantry',
  'data.hero': 'hero',
  'data.hydroponics-farm': 'Hydroponics Farm',
  'data.industrial-automation': 'Industrial Automation',
  'data.ion-storm': 'Ion Storm',
  'data.irradiated': 'Irradiated',
  'data.metal': 'metal',
  'data.metal-mine': 'Metal Mine',
  'data.microelectronics': 'microelectronics',
  'data.microelectronics-fab': 'Microelectronics Fab',
  'data.microelectronics-fabrication': 'Microelectronics Fabrication',
  'data.militia': 'militia',
  'data.nebula': 'Nebula',
  'data.oceanic': 'Oceanic',
  'data.open-space': 'Open space',
  'data.orbital-aa': 'Orbital AA',
  'data.orbital-logistics': 'Orbital Logistics',
  'data.planet': 'Planet',
  'data.radar-array': 'Radar Array',
  'data.rear': 'rear',
  'data.relic-world': 'Relic World',
  'data.ringworld': 'Ringworld',
  'data.salvage-metal-rig': 'Salvage Metal Rig',
  'data.scout': 'scout',
  'data.siege': 'siege',
  'data.siege-doctrine': 'Siege Doctrine',
  'data.solar-flare-zone': 'Solar Flare Zone',
  'data.space': 'space',
  'data.special-forces': 'special forces',
  'data.squadron': 'squadron',
  'data.strike-carrier': 'strike carrier',
  'data.tank': 'tank',
  'data.tax-office': 'Tax Office',
  'data.terran': 'Terran',
  'data.void-fortress': 'Void Fortress',
  'data.volcanic': 'Volcanic',

  // --- diplo — Дипломатия: окно, вкладки, фильтр и сортировка ростера, названия отношений.
  'diplo.filter': 'Filter',
  'diplo.filter.ai': 'AI',
  'diplo.filter.human': 'Human',
  'diplo.filter.reset': 'Clear',
  'diplo.sort': 'Sort',
  'diplo.sort.name': 'Name',
  'diplo.sort.provinces': 'Provinces',
  'diplo.sort.stance': 'Stance',
  'diplo.stance.alliance': 'Alliance',
  'diplo.stance.pact': 'Pact',
  'diplo.stance.peace': 'Peace',
  'diplo.stance.war': 'War',
  'diplo.tab.diplomacy': 'Diplomacy',
  'diplo.tab.espionage': 'Espionage',
  'diplo.tab.messages': 'Messages',
  'diplo.win.title': 'DIPLOMACY',

  // --- div — Дивизии: список, мобилизация, конструктор, трюм.
  'div.damage-vs': 'Damage vs:',
  'div.designer': '⚙ Designer',
  'div.empty': 'No divisions.',
  'div.empty.hint': 'No divisions — mobilize from a template below.',
  'div.hold': 'Divisions ⇄ hold (free {n})',
  'div.hold.note': 'Loading takes a division into the hold. Unloading lands it on this world.',
  'div.mobilize': 'Mobilization',
  'div.mobilize.named': 'Mobilize "{name}"',
  'div.note':
    'A division is a snapshot of its template: editing a design never touches armies already fielded. On your own world it heals +1 HP/unit/day.',
  'div.officer-locked': "An officer's named template: composition locked, no editing.",
  'div.rename': 'Rename',
  'div.roster': 'composition {n}/{s} · {rest}',
  'div.slot.note':
    'Tap a slot to cycle the unit type: militia → heavy infantry → special forces → tank. Tanks shred any infantry; special forces are the one infantry that threatens armour; heavy infantry holds the line.',
  'div.stat.attack': 'toughness',
  'div.stat.attack': 'defense',
  'div.stat.attack': 'attack',
  'div.stat.defense': 'defense',
  'div.stat.hp': 'toughness',
  'div.title': 'Divisions',

  // --- dossier — Досье объектов: здания, корабли, стройка в очереди, вкладки и характеристики.
  'dossier.building.barracks':
    'Barracks defend your world from invaders. Home to your valiant defenders.',
  'dossier.building.default': 'A planetary structure.',
  'dossier.building.fabricator':
    'Clean lithography halls print {m}▦ per hour. Hungry for power and people, but its output guides strike wings and unlocks siege doctrines. Upgrades pay for themselves in their own product.',
  'dossier.building.farm':
    'Tiers of hydroponic greenhouses under spectral lamps feed those in your care — hunger is merciless. Grows {f}❖ per hour. Your workers and soldiers eat every day; it would be foolish to lose a battle to a hungry faint.',
  'dossier.building.fort':
    'A layered planetary bastion. Raises garrison defense by {d} and holds {hp} structure HP under orbital fire. The last line of a besieged world.',
  'dossier.building.metal-station':
    "A mining rig gnawing into a dead world's scorched crust. Where annihilation burned away all life, raw metal ore lies exposed — the station pumps {m}⬢ per hour. Upgrades raise the yield.",
  'dossier.building.mine':
    'A drilling rig gnaws into the planet, mining {m}⬢ per hour. Upgrades dig deeper to reach the richest veins. The foundation for building your fleet.',
  'dossier.building.orbital-aa':
    "A stationary anti-air battery guards your world's airspace, dealing {dmg} damage per hour to ships in orbit. A nightmare for bombers hanging over the world and for raiding squadrons. Doesn't block capture (that's ground defense's job) — it just mows down the fleet overhead.",
  'dossier.building.power-plant':
    "A fusion reactor powers your worlds, producing {e}↯ per hour. Energy is the lifeblood of your buildings — they don't run on magic. When it runs short, everything browns out to half output.",
  'dossier.building.radar':
    'A radar complex sees through the space around your world and catches enemy signatures long before they dare attack. Upgrades widen the coverage.',
  'dossier.building.refinery':
    'A refining complex turning ore and logistics into liquid credits — {c}¤ per hour. Fuel for imperial bureaucracy, shipyards and mercenary squadrons.',
  'dossier.building.starfort':
    'A standalone fortress raised in an asteroid field: {d} to defense and {hp} structure HP. Turns a faceless crossroads into a fortified node with orbit and AA.',
  'dossier.building.tax-office':
    "An imperial-style tax office: produces nothing itself, but registers the world's population and lifts its credit take by {b}.",
  'dossier.divdesign.desc': 'The template editor: slot composition and division doctrine.',
  'dossier.divdesign.name': 'Division builder',
  'dossier.division.desc':
    'A ground formation mobilized from a template. Defends the world; loads onto a fleet from the fleet panel.',
  'dossier.division.name': 'Division',
  'dossier.fleet.desc':
    'A mobile task force of ships. Select it to give maneuver, orbit and strike orders.',
  'dossier.fleet.name': 'Fleet',
  'dossier.hint': 'Hover an object on the left — its dossier appears here.',
  'dossier.stat.atk.desc': "The fleet's total ship attack.",
  'dossier.stat.atk.name': 'Attack',
  'dossier.stat.cap.desc':
    'At most {n} units fire per volley — the strongest first; everyone beyond the cap only soaks damage.',
  'dossier.stat.cap.name': 'Firing line',
  'dossier.stat.datk.desc': "The division's total attack.",
  'dossier.stat.datk.name': 'Attack',
  'dossier.stat.ddef.desc': "The division's total defense.",
  'dossier.stat.ddef.name': 'Defense',
  'dossier.stat.def.desc': "The fleet's total ship defense.",
  'dossier.stat.def.name': 'Defense',
  'dossier.stat.dhp.desc': "The division's total hit points.",
  'dossier.stat.dhp.name': 'HP',
  'dossier.stat.garrison.desc': 'The ground troops defending the world.',
  'dossier.stat.garrison.name': 'Garrison',
  'dossier.stat.ground.desc': "Infantry and armour on the world's surface.",
  'dossier.stat.ground.name': 'Ground units',
  'dossier.stat.gships.desc': "Ships parked in the world's garrison (not in orbit).",
  'dossier.stat.gships.name': 'Ships in garrison',
  'dossier.stat.hp.desc': "The fleet's total hull strength.",
  'dossier.stat.hp.name': 'Hit points',
  'dossier.stat.hull.desc':
    'Current/full army hull. Mends over your world with a repair yard — or instantly for credits.',
  'dossier.stat.hull.name': 'Hull',
  'dossier.stat.pbuild.desc': 'The number of buildings on the world.',
  'dossier.stat.pbuild.name': 'Structures',
  'dossier.stat.shield.desc':
    'Ablative shield: takes damage first and recharges for free out of combat.',
  'dossier.stat.shield.name': 'Shield',
  'dossier.stat.spd.desc': 'Travel speed — the fleet moves at its slowest ship.',
  'dossier.stat.spd.name': 'Speed',
  'dossier.tab.buildings.desc':
    "The world's buildings and its construction conveyor: condition, levels, upgrades.",
  'dossier.tab.buildings.name': 'Buildings',
  'dossier.tab.ground.desc':
    'Ground units defend your worlds. Load them onto a fleet to capture enemy worlds.',
  'dossier.tab.ground.name': 'Ground',
  'dossier.tab.ships.desc':
    'The fleet is your weapon and shield. Order ships here to reinforce it.',
  'dossier.tab.ships.name': 'Fleet',
  'dossier.tab.squadron.desc':
    'A carrier (◈) holds squadrons (△). Launch the wing from the selected fleet\'s panel with "🛩 Launch squadron".',
  'dossier.tab.squadron.name': 'Wings',
  'dossier.task.eta': 'Remaining: {r}',
  'dossier.task.output': '{r}: {now}/h now → {final}/h once finished',
  'dossier.task.queued': 'Queued — not started yet.',
  'dossier.task.title': 'Building',
  'dossier.task.unit-ready': "Joins the planet's garrison/fleet once finished.",
  'dossier.unit.cruiser.desc':
    "The battle line's workhorse: {a} attack, {hp} hull and a hold for {c}. A general-purpose warship, equally solid on offense and defense.",
  'dossier.unit.cruiser.name': 'Cruiser',
  'dossier.unit.default': 'A combat unit.',
  'dossier.unit.fighter-squadron.desc':
    "A carrier-borne wing: fast (speed {sp}) and hits hard ({a} attack), but almost no armor ({hp} hull). Splits off the carrier into its own fast fleet and strikes from range {r}. Countered by orbital AA — don't send it against an AA-covered world.",
  'dossier.unit.fighter-squadron.name': 'Fighter squadron',
  'dossier.unit.hero.desc':
    "The commander's own combat projection — a flagship leading the home fleet: {a} attack and {hp} hull. But that's not what matters: its presence holds the squadron together, granting {b} attack/defense to every ship nearby. If it falls, the commander loses their projection until it's rebuilt at the home world.",
  'dossier.unit.hero.name': 'Flagship',
  'dossier.unit.scout.desc':
    'A light recon hull. Fast (speed {sp}) and almost silent (signature {sig}) — it maps the void where a battle fleet fears to go.',
  'dossier.unit.scout.name': 'Scout',
  'dossier.unit.siege.desc':
    'A heavy siege platform: {a} damage from range {r}, but thin armor ({d} defense). Its place is behind the cruisers, from where it smashes fortifications and shipyards.',
  'dossier.unit.siege.name': 'Siege Platform',
  'dossier.unit.strike-carrier.desc':
    'A slow armored carrier ({hp} hull, hold for {c}) — almost no guns of its own, all its strength is in the wing it carries. Keep it behind and launch the wing at a target with "🛩 Launch squadron".',
  'dossier.unit.strike-carrier.name': 'Strike Carrier',

  // --- faction — Фракции: пассивный бонус дома.
  'faction.amber.desc': 'A nomad concord of hauliers: fleets run the lanes 15% faster.',
  'faction.blue.desc': 'A trade-and-industry compact: all planetary economy yields +12%.',
  'faction.red.desc': 'A militarist hegemony: all outgoing fleet and army damage +10%.',
  'faction.violet.desc':
    'Universalists of the dawn: a little of everything — +5% economy and +5% damage.',

  // --- fleet — Автоимя флота по размеру соединения.
  'fleet.size.armada': 'Armada',
  'fleet.size.fleet': 'Fleet',
  'fleet.size.flight': 'Wing',
  'fleet.size.squadron': 'Flight',
  'fleet.size.squadron-heavy': 'Squadron',

  // --- fmt — Форматирование величин: длительности.
  'fmt.hours': '{n}m',
  'fmt.hours': '{n}h',
  'fmt.minutes': '{n}m',

  // --- form — Рода войск дивизии.
  'form.heavy-infantry': 'Heavy Infantry',
  'form.militia': 'Militia',
  'form.special-forces': 'Special Forces',
  'form.syn.armor.desc': '≥3 tanks — a breakthrough wedge',
  'form.syn.armor.name': 'Armored fist',
  'form.syn.combined.desc': 'Infantry and tanks in one line',
  'form.syn.combined.name': 'Combined arms',
  'form.syn.entrench.desc': '≥3 heavy infantry hold the line',
  'form.syn.entrench.name': 'Entrenched',
  'form.syn.raid.desc': '≥2 special forces, no militia',
  'form.syn.raid.name': 'Raid Doctrine',
  'form.syn.wave.desc': '≥4 militia — winning by numbers',
  'form.syn.wave.name': 'Human Wave',
  'form.tank': 'Tank',
  'form.tpl.breakthrough': 'Breakthrough Guard',
  'form.tpl.fist': 'Fist',
  'form.tpl.iron-line': 'Iron Line',
  'form.tpl.line': 'Line',
  'form.tpl.raid': 'Raid',
  'form.tpl.supply': 'Supply Column',

  // --- ground — Наземный бой: офицеры дивизии.
  'ground.officer.assault': 'Assault Leader',
  'ground.officer.defender': 'Defense Commander',
  'ground.officer.quartermaster': 'Quartermaster',

  // --- hint — Подсказки режима прицеливания на карте.
  'hint.aim-cancelled': 'aiming cancelled',
  'hint.assault-enemy-only': "⚔ only someone else's world can be stormed",
  'hint.auto-assault':
    '⚔ auto-storm on — the fleet storms the hostile world it arrives at by itself',
  'hint.barrage-auto': '🎯 auto-target',
  'hint.barrage-set': '🎯 auto-target',
  'hint.barrage-set': '🎯 focus fire set',
  'hint.cast-cancelled': '✖ cast cancelled',
  'hint.deploy-cancelled': '✖ deploy cancelled',
  'hint.forced-march': '⚡ forced march: +50% speed, −5% hull per hour underway',
  'hint.multiselect': '⊕ tap your fleets — build the group, then give a common order',
  'hint.no-target': '◎ no target picked',
  'hint.pick-assault': "⚔ pick someone else's world to storm",
  'hint.pick-barrage': '🎯 tap an enemy fleet to focus fire · empty space = auto',
  'hint.pick-merge': '⛬ pick a fleet to merge with',
  'hint.pick-order': '◎ tap a target on the map — compose the order',
  'hint.squadron-launched': '🛩 squadron launched — steer it onto the target',
  'hint.standing-sortie': '🛩 standing patrol on — the wing strikes any enemy in range',

  // --- map — Значки на карте: фазы боя.
  'map.badge.landing': '⚒ ground',
  'map.badge.orbit': '⚔ orbital',

  // --- meta — Прокачка командующего: уровень, очки, узлы.
  'meta.branch.command': 'Command',
  'meta.branch.economy': 'Economy',
  'meta.branch.science': 'Science',
  'meta.cost': '{n} pt.',
  'meta.level': 'Level {n}',
  'meta.locked': 'Locked',
  'meta.node.cmd1.desc': '+5% fleet speed from the first second of a match.',
  'meta.node.cmd1.name': 'Helm Schools',
  'meta.node.cmd2.desc': '+5% damage for fleets and garrisons.',
  'meta.node.cmd2.name': 'Drilled Crews',
  'meta.node.cmd3.desc': '+15% to every radar radius.',
  'meta.node.cmd3.name': 'Deep Recon',
  'meta.node.cmd4.desc': "Another +5% speed and damage — the old guard's reflexes.",
  'meta.node.cmd4.name': 'Campaign Veteran',
  'meta.node.eco1.desc': '+10% starting treasury every match.',
  'meta.node.eco1.name': 'Quartermaster',
  'meta.node.eco2.desc': '+5% production on all worlds.',
  'meta.node.eco2.name': 'Industrialization',
  'meta.node.eco3.desc': 'Another +20% starting treasury.',
  'meta.node.eco3.name': 'State Reserve',
  'meta.node.eco4.desc': 'Another +5% production — the empire works for you.',
  'meta.node.eco4.name': 'Magnate',
  'meta.node.sci1.desc': 'Council scientists start the match +1 level.',
  'meta.node.sci1.name': 'Postgraduate School',
  'meta.node.sci2.desc': '"Industrial Automation" is researched from the first second.',
  'meta.node.sci2.name': 'Open Archive',
  'meta.node.sci3.desc': 'Council scientists — another +1 level.',
  'meta.node.sci3.name': 'Institute Network',
  'meta.node.sci4.desc': '"Orbital Logistics" is researched from the first second.',
  'meta.node.sci4.name': 'Orbital Faculty',
  'meta.note':
    'XP comes from finished matches: participation + score + victory. Progression is never sold — play only.',
  'meta.points': 'Points: {n}',
  'meta.xp': '{got}/{need} XP',

  // --- net — Сеть: подключение, разрывы, адрес сервера.
  'net.bad-address': 'Invalid server address',
  'net.connected': '● connected as {who}',
  'net.connecting': 'Connecting: {nick}…',
  'net.disconnected': '● disconnected from server',
  'net.join-closed': 'this match is closed to new players (the entry window has elapsed)',
  'net.match-full': 'match is full — every seat is taken',
  'net.need-address': 'Enter the server address',
  'net.reconnecting': '● connection lost — reconnecting…',
  'net.reconnecting-order': 'reconnecting — order not sent, try again shortly',
  'net.waiting-host': 'Waiting for the host to start…',

  // --- queue — Очередь стройки: постановка, улучшение, отказы.
  'queue.added': 'queued: {what} at {at}',
  'queue.failed': '{what} — failed: {err}',
  'queue.unknown': 'unknown order',
  'queue.upgrade': '{b} — upgrade',

  // --- res — Ресурсы в косвенных падежах (для фраз «не хватает …»).
  'res.of.credits': 'credits',
  'res.of.energy': 'energy',
  'res.of.food': 'food',
  'res.of.metal': 'metal',
  'res.of.microelectronics': 'microelectronics',

  // --- sandbox — Песочница (дев-инструмент): переключатели и команды.
  'sandbox.commands': 'Commands',
  'sandbox.end-wars': 'Close',
  'sandbox.end-wars': 'End the war with every faction',
  'sandbox.no-player': 'no player',
  'sandbox.no-wars': 'You are not at war with anyone',
  'sandbox.res.credits': 'Credits',
  'sandbox.res.energy': 'Energy',
  'sandbox.res.food': 'Food',
  'sandbox.res.metal': 'Metal',
  'sandbox.res.microelectronics': 'Microelectronics',
  'sandbox.title': 'Toggles',
  'sandbox.title': 'SANDBOX',
  'sandbox.tog.fog': 'Fog of war',
  'sandbox.tog.fog.hint': 'Turn off to reveal the whole map',
  'sandbox.tog.free-build': 'Free upgrades',
  'sandbox.tog.free-build.hint': 'Buildings cost no resources',
  'sandbox.tog.freeze-queues': 'Freeze the queue',
  'sandbox.tog.freeze-queues.hint': 'Construction stops for everyone',
  'sandbox.tog.immortal-home': 'Immortal home world',
  'sandbox.tog.immortal-home.hint': 'The home world cannot be captured',
  'sandbox.tog.instant-build': 'Instant construction',
  'sandbox.tog.instant-build.hint': 'Construction finishes immediately',
  'sandbox.tog.instant-cooldown': 'Skill cooldowns',
  'sandbox.tog.instant-cooldown.hint': 'Commander abilities are always ready',
  'sandbox.tog.speed': 'Speed control',
  'sandbox.tog.speed.hint': 'the in-match time bar — pause and speed multipliers (1× is real time)',
  'sandbox.toggles': 'Toggles',
  'sandbox.wars-ended': 'You are not at war with anyone',
  'sandbox.wars-ended': 'Wars ended: {n} — relations are neutral',

  // --- sci — Учёные совета: имя и что даёт ветка.
  'sci.ground-marshal.desc': 'Leader of the ground branch: strongholds and frontier defence.',
  'sci.ground-marshal.name': 'Ground Marshal',
  'sci.missile-chief.desc': 'Leader of the missile branch: long-range systems.',
  'sci.missile-chief.name': 'Missile Chief',
  'sci.overseer.desc':
    'Leader of the command branch (C2): doctrines of automation and delegation. Unlocks the «Steward Protocol» — handing your seat to an AI while you sleep.',
  'sci.overseer.name': 'Overseer',
  'sci.polymath.desc': 'A generalist with no branch: +1 research slot (2→3) instead of a focus.',
  'sci.polymath.name': 'Polymath',
  'sci.void-admiral.desc': 'Leader of the space branch: shipyards, logistics, siege doctrines.',
  'sci.void-admiral.name': 'Void Admiral',
  'sci.wing-commander.desc': 'Leader of the squadron branch: carrier strike wings.',
  'sci.wing-commander.name': 'Wing Commander',

  // --- scipick — Совет учёных: кандидаты, фокус ветки, закрепление.
  'scipick.candidates': 'Candidates · tap to fill a slot',
  'scipick.confirm': 'Lock in and continue to start pick →',
  'scipick.focus': '{br} branch focus',
  'scipick.generalist': '+1 research slot (a generalist, no branch focus)',
  'scipick.need-two': 'Pick two scientists',
  'scipick.note': 'Candidates · tap to fill a slot',
  'scipick.note':
    '⚠ The council locks in for the whole match. A recommended pair is pre-selected — swap to taste.',
  'scipick.opens': '{br} branch focus',
  'scipick.opens': 'Opens the {br} branch: {list}',
  'scipick.pick': 'Pick a scientist',

  // --- soon — Заглушки «скоро» для ещё не готовых экранов.
  'soon.generic': '{what} — coming soon',

  // --- split — Разделение флота: диалог и предпросмотр.
  'split.all': 'All',
  'split.confirm': 'Cancel',
  'split.confirm': 'Confirm',
  'split.note':
    'Peel ships into a new fleet — it stays in the same sector. At least one ship stays behind; carried troops stay with the original.',
  'split.preview': 'new fleet: {a} ships · original keeps {b}',
  'split.title':
    'Peel ships into a new fleet — it stays in the same sector. At least one ship stays behind; carried troops stay with the original.',
  'split.title': 'SPLIT FLEET',

  // --- stat — Характеристики юнита в компактных подписях.
  'stat.cargo': 'cargo',
  'stat.hp': 'hull',
  'stat.radar': 'radar',
  'stat.shield': 'shield',
  'stat.speed': 'speed',

  // --- tgt — Композер приказов (TGT-1): шаги плана, отправка.
  'tgt.add-wait': 'Home',
  'tgt.add-wait': 'Fire',
  'tgt.add-wait': 'Assault',
  'tgt.add-wait': 'Go here',
  'tgt.add-wait': '⏱ +1h',
  'tgt.at': '🎯{n}h',
  'tgt.clear': 'clear the order',
  'tgt.empty': 'plan is empty — add steps',
  'tgt.fleets': '{n} fleets',
  'tgt.placed': '◎ order set — the fleet will run the plan itself',
  'tgt.send': 'clear the order',
  'tgt.send': 'Send',
  'tgt.step.fire': 'Fire',
  'tgt.step.here': 'Go here',
  'tgt.step.home': 'Home',
  'tgt.step.remove': 'remove step',
  'tgt.title': '{n} fleets',
  'tgt.title': 'ORDER',
  'tgt.wait': '⏱{n}h',

  // --- threat — Оповещение об угрозе: подход врага, радарный контакт.
  'threat.contact': '◆ new radar contact ({size}) at {at}',
  'threat.here': '⚠ An enemy at {node}!',
  'threat.incoming': '⚠ An enemy is heading for {node}: arrival in {dur}',

  // --- yard — «Верфь»: корпус и модули, конструктор дивизий, стоимость и заказ.
  'yard.arsenal.note':
    '⚡ Live arsenal: anything bought during the match shows up here right away, but it only starts working once you BUILD it — construction and logistics, not instant.',
  'yard.build': 'Build ×{n} →',
  'yard.cost.hull': 'Hull ×{n}',
  'yard.cost.live': 'live recalc',
  'yard.cost.modules': 'Modules ×{n}',
  'yard.cost.total': 'Total',
  'yard.cost.with-modules': 'Total with modules',
  'yard.div.attack': 'Attack',
  'yard.div.cost': 'Mobilization cost',
  'yard.div.defense': 'Defense',
  'yard.div.doctrine': 'Composition doctrine',
  'yard.div.doctrine.note': 'Mix troop types — the composition sets a doctrine.',
  'yard.div.empty': 'No templates.',
  'yard.div.hull': 'Hull',
  'yard.div.note':
    "Tap a slot: empty → infantry → tank. Mobilize the division in your world's panel (the «Divisions» tab).",
  'yard.div.slot-empty': 'empty',
  'yard.div.slots': '{n}/{s} units · tap a slot to change the troop type',
  'yard.div.total': 'Formation summary',
  'yard.free': 'free',
  'yard.hull.none': 'The arsenal has no hulls of this class.',
  'yard.hull.unavailable': 'Hull unavailable.',
  'yard.loadout.note':
    "Loadout locks in on build. A finished ship can't be refitted — build a new one with a different set.",
  'yard.module.remove': 'remove module',
  'yard.modules.all-taken': 'Available modules — all slots full',
  'yard.modules.for-slot': 'Available modules — for the «{s}» slot',
  'yard.no-worlds': 'no worlds of yours',
  'yard.ordered': '⚒ ordered: {n}× {hull}',
  'yard.pick.ally-world': " / ally's world",
  'yard.pick.hero-world': "⚓ pick your world{fl}{al} — the hero's ship rises there",
  'yard.pick.own-fleet': ' / own fleet',
  'yard.pick.target': '✨ pick a target world on the map',
  'yard.slot.defense': 'Defense',
  'yard.slot.empty': 'empty — pick a module',
  'yard.slot.named': '«{s}» slot',
  'yard.slot.utility': 'System',
  'yard.slot.weapon': 'Weapon',
  'yard.slots.count': '{n} module slots (by hull size)',
  'yard.slots.note':
    'Typed slots: a module fits only its own type. <b>Greyed</b> — not for a free slot, or already installed.',
  'yard.soon': '«{what}» moves into the constructor in the next brick.',
  'yard.tab.army': 'Army',
  'yard.tab.heroes': 'Heroes',
  'yard.tab.ships': 'Ships',
  'yard.tab.squads': 'Squadrons',
  'yard.title': 'CONSTRUCTOR',

  // --- end — Экран конца матча: исход, опыт, итоговая таблица, реванш.
  'end.board': 'View the board',
  'end.draw': '⚖️ DRAW',
  'end.duration': 'Duration',
  'end.fleets': 'Fleets',
  'end.level-up': '★ Level up to {lvl} — a progression point awaits in the Progression menu',
  'end.loss': '💀 DEFEAT',
  'end.new-match': '⟳ New match',
  'end.place': '{p} of {n}',
  'end.play-again': '⟳ Play again',
  'end.provinces': 'Provinces',
  'end.score': 'Final score',
  'end.to-menu': 'Menu',
  'end.units': 'Units',
  'end.win': '🏆 VICTORY',
  'end.win.coalition': '🏆 COALITION VICTORY',
  'end.xp': '★ Commander XP: +{n}',

  // --- err — Отказы ядра (kernel rejection codes). Ключ выводится из кода: E_NO_CAPACITY → err.no-capacity.
  'err.already': 'already in effect',
  'err.already-fitted': 'that fitting is already installed',
  'err.already-offered': 'a proposal is already pending',
  'err.already-unlocked': 'that node is already unlocked',
  'err.bad-effect': 'the ability is misconfigured',
  'err.bad-payload': 'malformed order',
  'err.bad-spawn': 'a hero cannot be deployed here',
  'err.bad-target': 'invalid target',
  'err.bombarded': 'construction under bombardment',
  'err.bot-alliance': 'bots do not join coalitions',
  'err.chat-rate': 'give it a couple of seconds',
  'err.chat-target': 'recipient not found',
  'err.chat-text': 'empty message',
  'err.conditions-unmet': 'conditions not met',
  'err.consent-required': 'the other side must consent',
  'err.cooldown': 'the ability is recharging',
  'err.fleet-busy': 'fleet busy',
  'err.forbidden': 'action forbidden',
  'err.hero-alive': 'the hero already commands a ship',
  'err.hero-cap': 'deployed-hero limit reached',
  'err.hero-dead': 'the hero is dead — wait for the respawn',
  'err.hero-not-deployed': 'the hero is not deployed — raise a ship first',
  'err.insufficient': 'insufficient resources',
  'err.internal': 'internal error',
  'err.limit': 'limit reached',
  'err.no-ability': 'unknown ability',
  'err.no-artillery': 'no artillery',
  'err.no-capacity': 'the hold is full',
  'err.no-capital': 'no capital to recall to',
  'err.no-effect': 'that effect is not implemented yet',
  'err.no-fitting': 'unknown fitting',
  'err.no-fleet': 'fleet not found',
  'err.no-funds': 'insufficient funds',
  'err.no-hero': 'hero not found',
  'err.no-node': 'unknown skill-tree node',
  'err.no-planet': 'world not found',
  'err.no-player': 'player not found',
  'err.no-ships': 'no ships',
  'err.no-shipyard': 'needs a shipyard/spaceport',
  'err.no-slots': 'all fitting slots are taken',
  'err.no-target': 'no target',
  'err.no-troops': 'the world is defended — an assault needs troops aboard',
  'err.not-destructible': 'this world cannot be destroyed',
  'err.not-equipped': 'the hero does not have that ability',
  'err.out-of-range': 'out of range',
  'err.own-planet': 'this is your own world',
  'err.requires': 'unlock the preceding node first',
  'err.research-slots-full': 'all research slots are full',
  'err.respawn-cooldown': 'the hero is still recovering',
  'err.same-location': 'fleet is already here',
  'err.too-early': 'too early',
  'err.unknown-building': 'unknown building',
  'err.unknown-technology': 'unknown technology',
  'err.unknown-unit': 'unknown unit',
  'err.wrong-branch': 'that node belongs to another branch',
  'err.wrong-orbit': 'invalid orbit',
  'err.wrong-sector': 'invalid sector type',

  // --- hero — Герои: грейды, способности (имя + описание).
  'hero.ability.annihilate.desc': 'Destroys a planet in range — it becomes a dead world.',
  'hero.ability.annihilate.name': 'Annihilate',
  'hero.ability.boarding-translocation.desc':
    'The hero forms aboard one of your fleets — wherever it happens to be. Passive skill: widens the deployment points.',
  'hero.ability.boarding-translocation.name': 'Boarding Translocation',
  'hero.ability.bulwark.desc': 'A temporary shield: +defense to your fleets near the hero.',
  'hero.ability.bulwark.name': 'Bulwark',
  'hero.ability.corridor.desc':
    'Opens a temporary corridor lane to a nearby world; your fleets travel it faster.',
  'hero.ability.corridor.name': 'Corridor',
  'hero.ability.diplomatic-landing.desc':
    "Allied worlds receive the hero as one of their own: the ship can also rise from an ally's planet. Passive skill: widens the deployment points.",
  'hero.ability.diplomatic-landing.name': 'Diplomatic Landing',
  'hero.ability.rally.desc':
    'A battle cry: a temporary extra aura bonus for your fleets near the hero.',
  'hero.ability.rally.name': 'Rally',
  'hero.ability.recall.desc': 'Instantly recalls the hero ship to the capital.',
  'hero.ability.recall.name': 'Recall',
  'hero.ability.scan.desc': 'Reveals an area around the target through the fog for a while.',
  'hero.ability.scan.name': 'Scan',
  'hero.arch.commander': 'Commander',
  'hero.arch.destroyer': 'Destroyer',
  'hero.arch.vanguard': 'Vanguard',
  'hero.arch.warden': 'Sentinel',
  'hero.branch.common': 'Common',
  'hero.branch.psionic': 'psionic',
  'hero.branch.transhuman': 'transhuman',
  'hero.fit.ablative-plating.desc':
    "An extra +40 hull for the hero's ship. (Ship stats take effect with the effective-stats seam, SHIP-3.)",
  'hero.fit.aegis-matrix.desc':
    'A field generator inspires the fleets near the hero: +8% damage within 300.',
  'hero.fit.psi-amplifier.desc': 'A resonance circuit opens scanning through the fog to the hero.',
  'hero.grade.common': 'Common',
  'hero.grade.legendary': 'Legendary',
  'hero.grade.main': 'Main',
  'hero.grade.rare': 'Rare',
  'hero.hook.combat-damage': 'damage to nearby fleets',
  'hero.hook.fleet-speed': 'fleet speed',
  'hero.passive.rally-beacon.desc':
    'Fleets near the hero fight harder: +8% damage for your fleets within 300.',
  'hero.passive.rally-beacon.name': 'Rally Beacon',
  'hero.passive.vanguard-impulse.desc':
    "The hero's ship drives its fleet at full burn: +10% speed for the hero's fleet.",
  'hero.passive.vanguard-impulse.name': 'Vanguard Impulse',
  'hero.tree.neural-lace.desc': "A direct brain-to-helm implant: the hero's ship gains +10% speed.",
  'hero.tree.neural-lace.name': 'Neural Lace',
  'hero.tree.overclocked-helm.desc':
    'Overclocking the neural interface lets the hero lay corridors.',
  'hero.tree.overclocked-helm.name': 'Overclocked Helm',
  'hero.tree.psi-veil.desc': 'Honed psi-sight: the hero learns to tear the fog open with a scan.',
  'hero.tree.psi-veil.name': 'Psi Veil',
  'hero.tree.void-attunement.desc':
    "The hero's psi resonance inspires nearby fleets: +8% damage within 300.",
  'hero.tree.void-attunement.name': 'Void Attunement',
  'hero.unit.commander.desc':
    'The flagship hero: a command transhuman who strengthens the fleet and opens corridors.',
  'hero.unit.commander.name': 'Commander',
  'hero.unit.ravager.desc': 'A psionic destroyer: annihilates worlds and tears open the fog.',
  'hero.unit.ravager.name': 'Destroyer',
  'hero.unit.vanguard.desc':
    'A transhuman manoeuvrist: corridors and a war cry for the leading fleets.',
  'hero.unit.vanguard.name': 'Vanguard',
  'hero.unit.warden.desc': 'A psionic defender: holds the line behind a bastion shield.',
  'hero.unit.warden.name': 'Sentinel',

  // --- hero.hq / hero.tree / hero.abil / hero.fit — Штаб героев: состав, дерево навыков, способности, фиттинги.
  'hero.abil.activate': 'Activate',
  'hero.abil.cooldown': 'CD {h}',
  'hero.abil.deploy-perk': 'deploy perk',
  'hero.abil.empty': 'No abilities.',
  'hero.abil.pick-target': 'Target…',
  'hero.abil.soon': 'soon',
  'hero.fit.hull': 'hull',
  'hero.fit.hull-mod': 'Hull modifier',
  'hero.fit.install': 'Irreversible — install',
  'hero.fit.installed': 'installed',
  'hero.fit.no-slots': 'no slots',
  'hero.fit.none': 'This hero has no fitting slots.',
  'hero.fit.permanent': 'Installed for good — no refit',
  'hero.fit.slots': 'Slots · {u}/{n}',
  'hero.hq.dead': 'lost',
  'hero.hq.deploy': 'Expand',
  'hero.hq.deployed': '⚓ deployed',
  'hero.hq.deployed-count': 'deployed {a}/{c}',
  'hero.hq.empty': 'You have no heroes yet.',
  'hero.hq.enroute': 'in transit',
  'hero.hq.fittings': 'Fittings',
  'hero.hq.reserve': 'reserve',
  'hero.hq.tab.abilities': 'Abilities',
  'hero.hq.tab.fittings': 'Fittings',
  'hero.hq.tab.overview': 'Overview',
  'hero.hq.tab.tree': 'Tree',
  'hero.stat.abilities': 'abilities',
  'hero.stat.active': 'active',
  'hero.stat.bonuses': 'Current bonuses',
  'hero.stat.fittings': 'fittings',
  'hero.stat.tree-nodes': 'tree nodes',
  'hero.tree.ability': 'ability',
  'hero.tree.cooldown': 'CD {h}h',
  'hero.tree.cost': 'Cost',
  'hero.tree.empty': 'The tree is empty.',
  'hero.tree.grants-ability': 'Unlocks an ability',
  'hero.tree.grants-passive': 'Grants a passive',
  'hero.tree.needs': 'needs: {n}',
  'hero.tree.not-your-branch': 'not your branch',
  'hero.tree.other-branch': 'other branch',
  'hero.tree.passive': 'passive',
  'hero.tree.range': 'range {r}',
  'hero.tree.requires': 'Requires',
  'hero.tree.unlock': 'Unlock',
  'hero.tree.unlocked': 'researched',

  // --- hub — Хаб (экран между матчами): шапка, карточки, плитки «Ещё», нижняя навигация.
  'hub.ally.corp': 'Corporation cabinet',
  'hub.ally.empty.sub': 'corporations · shared AvA battles · influence',
  'hub.ally.empty.title': 'Alliances',
  'hub.avatar.title': 'Change emblem',
  'hub.back-to-bots': '⟳ Back to setup',
  'hub.digest.empty.sub':
    'Join a match on the "Games" tab — moves needing your attention will show up here.',
  'hub.digest.empty.title': 'No matches waiting on an order',
  'hub.digest.section': 'Summary',
  'hub.emblem.close': 'Close',
  'hub.emblem.title': 'CHOOSE AN EMBLEM',
  'hub.messages.soon': 'Messages — coming soon',
  'hub.msgs.aria': 'Messages',
  'hub.nav.ally': 'Alliances',
  'hub.nav.arsenal': 'Arsenal',
  'hub.nav.games': 'Games',
  'hub.nav.home': 'Home',
  'hub.nav.meta': 'Progression',
  'hub.nav.more': 'More',
  'hub.nav.rank': 'Rank',
  'hub.onboard.skip': 'Skip',
  'hub.onboard.start': 'Start tutorial',
  'hub.onboard.sub':
    'A short tutorial walks you through the interface and your first move — a couple of minutes.',
  'hub.onboard.title': 'New to Void Dominion?',
  'hub.play': 'PLAY NOW',
  'hub.rank.empty.sub': 'a seasonal rank from match placements',
  'hub.rank.empty.title': 'Rankings — coming soon',
  'hub.sandbox.title': 'Sandbox',
  'hub.season.sub': 'Rankings and alliances unlock once the meta-layer launches.',
  'hub.season.title': 'The season has not started',
  'hub.solo': 'Solo game',
  'hub.sovereigns': 'Sovereigns — the donate currency',
  'hub.status.online': 'online',
  'hub.tile.account': 'Account',
  'hub.tile.chat': 'Chat',
  'hub.tile.community': 'Community',
  'hub.tile.help': 'Codex',
  'hub.tile.logout': 'Switch commander',
  'hub.tile.notifications': 'Notifications',
  'hub.tile.settings': 'Settings',
  'hub.tile.support': 'Support',
  'hub.tile.tutorial': 'Tutorial',
  'hub.tile.updates': 'Updates',

  // --- hud — Постоянный интерфейс матча: верхняя панель ресурсов.
  'hud.crest.title': 'Your profile',
  'hud.deficit': '⚠ SHORTAGE — consuming buildings run at 50%',
  'hud.goal': 'Goal: ✦ {n} (a world — 50, a province — 10) or eliminate your rivals.',
  'hud.resource.credits': 'Credits',
  'hud.resource.energy': 'Energy',
  'hud.resource.food': 'Food',
  'hud.resource.metal': 'Metal',
  'hud.resource.microelectronics': 'Microelectronics',
  'hud.resource.tip':
    '{ic} {name}: {stock} in the treasury · {flow}/h (production minus army and building upkeep)',
  'hud.score.tip':
    '✦ {score}/{limit}: a world — 50, any other province — 10, buildings add per level (you hold {w} worlds, {s} provinces). Win at ✦ {limit}, by eliminating rivals, or by domination.',

  // --- log — Журнал событий матча (сводки) и гейт объявления войны.
  'log.assault.no-troops':
    '⚔ assault impossible: no landing force aboard and the world is defended — load troops',
  'log.assault.warn-no-troops':
    '⚔ warning: no landing force aboard — a defended world cannot be stormed',
  'log.battle.draw': 'a stalemate',
  'log.battle.end': '⚔ battle at {at} ended — {res}',
  'log.battle.losses': ' · losses: {tally}',
  'log.battle.phase.ground': 'landing',
  'log.battle.phase.orbit': 'orbit',
  'log.battle.start': '⚔️ battle at {at} ({phase})',
  'log.battle.win': '{who} won',
  'log.build.destroyed': '💥 {b} destroyed at {at}',
  'log.build.done': '🏗️ {b} built at {at}',
  'log.build.upgraded': '⬆️ {b} → L{lvl} at {at}',
  'log.capture': '🚩 {who} captured {at}',
  'log.diplo.offer': '🕊 {who} offers {stance} — answer in kind in Diplomacy',
  'log.diplo.offer.short': 'Proposal: {stance}',
  'log.diplo.rejected': '{who} declined the proposal: {stance}',
  'log.diplo.rejected.short': '✖ {who} declined: {stance}',
  'log.diplo.sent': '⏳ {who}: proposal sent — {stance}',
  'log.diplo.stance': '{a} and {b}: {stance}',
  'log.diplo.war': '{a} declared war on {b}',
  'log.fleet.destroyed': '☠️ a {who} fleet was destroyed',
  'log.fleet.launched': '🚀 {who} launched a fleet from {at}',
  'log.fleet.merged': '⛬ fleets merged at {at}',
  'log.fleet.split': '⊟ fleet split at {at}',
  'log.market.buy': 'buy',
  'log.market.sell': 'sell',
  'log.market.trade': '⇄ market: {n} {res} for {paid} ¤ ({side})',
  'log.spy.caught': '🛡 Counter-intel: agent {who} caught stealing ({what})!',
  'log.spy.fail': '🕵 Agent failed ({who}) — the fee is gone',
  'log.spy.fail.short': '✖ Failed against {who} — the fee burned',
  'log.spy.kind.fleets': 'fleet data',
  'log.spy.kind.treasury': 'treasury',
  'log.spy.kind.world': "a world's data",
  'log.spy.leak': '🛡 Counter-intel: an intel leak ({what}) — the thief is unknown',
  'log.spy.success': '🕵 Agent got intel: {what} — a 24h window',
  'log.spy.success.short': '🗝 Success: {what}',
  'log.spy.what.fleets': "{who}'s fleets",
  'log.spy.what.treasury': "{who}'s treasury",
  'log.spy.what.world': 'world {at}',
  'log.steward.decisions': "Decisions this watch: {n} — see the Steward window's journal.",
  'log.steward.handback.active':
    '🌅 The Steward returned control to you (posture was “Active defense”).',
  'log.steward.handback.defense': '🌅 The Steward returned control to you (posture was “Defend”).',
  'log.steward.off': '🎮 You took command back.',
  'log.steward.on.active':
    '😴 The Steward took command (Active defense) — holding the line and counterstriking at your own worlds.',
  'log.steward.on.defense':
    '😴 The Steward took command (Defend) — holding the line while you sleep.',
  'log.tech.done': '⚛ researched: {tech}',
  'log.war.declared': '⚔ War declared — fleets advancing',
  'war.confirm.cancel': 'CANCEL',
  'war.confirm.friendly':
    "This is a friendly faction's world. Do you want to declare war on <b>{names}</b>?",
  'war.confirm.go': 'DECLARE WAR',
  'war.confirm.no': 'NO',
  'war.confirm.title': 'DECLARE WAR?',
  'war.confirm.transit':
    'This route crosses worlds held by <b>{names}</b>, with whom you are at <b>peace</b>. There is no peaceful passage — advancing here declares <b>war</b>.',
  'war.confirm.yes': 'YES',

  // --- market — Сессионная биржа: вкладки ресурсов, книга заявок, лот, комиссия.
  'market.buy': 'Buy',
  'market.cancel': 'Cancel',
  'market.escrow-note': 'escrow: {n} ¤ · the {p}% fee is paid by whoever receives the credits',
  'market.in-treasury': 'In the treasury',
  'market.net-after-fee': 'you receive after the {p}% fee: {n} ¤',
  'market.no-asks': 'No sell orders',
  'market.no-bids': 'No buy orders',
  'market.own-lot': 'your lot',
  'market.place': 'List',
  'market.price': 'price',
  'market.qty': 'amount',
  'market.res.energy': 'Energy',
  'market.res.food': 'Food',
  'market.res.metal': 'Metal',
  'market.res.microelectronics': 'Micro',
  'market.sell': 'Sell',
  'market.side.buy': 'Buy',
  'market.side.sell': 'Sell',
  'market.title': 'MARKET',

  // --- onb — Онбординг: туры-подсказки, карточки первого контакта, цели первой сессии, сводка возвращения.
  'onb.goal.capture': 'Capture a world',
  'onb.goal.fleet': 'Build a ship',
  'onb.goal.mine': 'Build a mine',
  'onb.goal.score': 'Reach 100 points',
  'onb.goals.all-done':
    '🏅 All first-session goals done! +{n} XP — you are ready for a real match.',
  'onb.goals.title': 'First-session goals',
  'onb.intro.artillery.body':
    'Artillery fleets fire on the enemy from afar, before closing the distance — focus fire on one target, or let the fleet pick one itself. Artillery has thin armor, so keep it behind the line, not on the front.',
  'onb.intro.artillery.title': 'Barrage — firing from range',
  'onb.intro.async-delay.body':
    'This fleet will arrive in real hours — the world of Void Dominion runs continuously, even while you are offline. You can close the game: your orders carry out on their own, and on your return we will send a notification and show a "while you were away" digest.',
  'onb.intro.async-delay.title': 'The world runs without you',
  'onb.intro.ava.body':
    'Here corporations challenge each other to an organised war. Mark your corporation ready and yourself ready — once both sides are ready, a challenge can be accepted. Next comes roster sign-up and the scheduled war itself.',
  'onb.intro.ava.title': 'Alliance wars (AvA)',
  'onb.intro.badge': 'first time',
  'onb.intro.constructor.body':
    'Here you assemble ships, squadrons, divisions and heroes from modules. The loadout is locked at build time — choose slots up front, a finished unit cannot be re-fitted. The «Heroes» tab is your commander HQ.',
  'onb.intro.constructor.title': 'Shipyard — loadouts',
  'onb.intro.corp.body':
    'A corporation is your squad within the session: a shared warehouse, member roles, and joint alliance-vs-alliance wars (AvA). Join one or found your own — the «Wars» tab opens challenges between corporations.',
  'onb.intro.corp.title': 'Corporation cabinet',
  'onb.intro.diplomacy.body':
    'Declare war and peace, sign pacts and alliances. A coalition is capped by combined strength — you cannot gang everyone up on one player. Watch the stances: an ally today can be a rival tomorrow.',
  'onb.intro.diplomacy.title': 'Diplomacy',
  'onb.intro.hero.body':
    'Each hero has its own skill tree — tap a node to see what it unlocks, then learn it once its requirements and cost are met. Unlocked nodes grant abilities (active, with range and a cooldown) or passives. A fallen hero respawns at your capital.',
  'onb.intro.hero.title': 'Heroes — fleet commanders',
  'onb.intro.market.body':
    'Trade resources with the other players in the session: post your own lots and take theirs. The market smooths shortages — swap a surplus of one resource for the one you lack.',
  'onb.intro.market.title': 'Session market',
  'onb.intro.ok': 'Got it',
  'onb.intro.retreat.body':
    "Retreat costs −40% of CURRENT hull and shield (a wounded fleet loses 40% of what remains — retreat never finishes it off) and grants a speed burst to flee. Troops mid-landing can't retreat; a ship in orbit outside battle leaves freely.",
  'onb.intro.retreat.title': 'Retreat is not free',
  'onb.intro.steward.body':
    'Away for a while? Hand your defence to the Steward — it holds your worlds by your rules while you are gone. The world runs 24/7, but a baseline defence stays up even when you are offline.',
  'onb.intro.steward.title': 'Steward — AI on sleep',
  'onb.intro.tech.body':
    'Here you unlock technologies — permanent upgrades to your fleet, economy and defence. A node costs resources and time; once researched, the bonus lasts the rest of the match. Plan the branch to fit your playstyle.',
  'onb.intro.tech.title': 'Technology tree',
  'onb.recap.attention': 'Needs attention · {n}',
  'onb.recap.close': 'CLOSE',
  'onb.recap.rest': 'While you were away',
  'onb.recap.title': 'RETURN DIGEST',
  'onb.tour.done': '✔ Tutorial complete · +{n} XP — now play a real match!',
  'onb.tour.first.capture':
    'Take a neutral world: enter orbit, and if it is defended, land troops. Capture is two-phase: sky first, then ground.',
  'onb.tour.first.course':
    'Select your fleet (▲) and tap a neighbouring world to set a course. It routes along the star lanes and the fog opens.',
  'onb.tour.first.done':
    'First fight won! You ran the whole loop: produce → build → move → capture → score. Next up — a real match.',
  'onb.tour.first.fleet':
    'Now build a warship — the «Ships» tab of the same panel. A finished ship flies to orbit on its own and forms a fleet — wait for a «▲» to appear next to your world.',
  'onb.tour.first.home':
    'Down here is your homeworld panel: buildings, garrison and construction. Tap your world if the panel is empty.',
  'onb.tour.first.mine':
    'Start with economy: build a Mine — it produces the resources everything else is built from.',
  'onb.tour.first.score':
    'World taken — and the score moves! Points come from worlds and sectors; reach the threshold to win.',
  'onb.tour.first.welcome':
    'This is your first world, commander. I will walk you through the core loop — a couple of minutes, calm, no rivals.',
  'onb.tour.got-it': 'Got it',
  'onb.tour.hud.clock':
    'The world runs in real time and keeps going even while you are offline. Pause and speed live here.',
  'onb.tour.hud.done':
    'Done! Time to act: build a mine, raise a fleet, set a course. Good luck, commander.',
  'onb.tour.hud.purse': 'Your treasury: mine income minus fleet upkeep. Keep it out of the red.',
  'onb.tour.hud.tools':
    "The commander's tools: diplomacy, research, shipyard, market and the event log.",
  'onb.tour.hud.welcome':
    'A quick tour of the interface — the whole game runs on it. «Skip tutorial» is always available.',
  'onb.tour.next': 'Next',
  'onb.tour.skip': 'Skip tutorial',
  'onb.tour.step': 'step {k} of {n}',

  // --- ping — Композер меток провинции: адресат, описание, отправка.
  'ping.cancel': 'Cancel',
  'ping.desc.ph': 'Marker description (optional)…',
  'ping.mark': 'marker {loc}',
  'ping.no-desc': 'no description',
  'ping.note': 'Mark a province and send — the marker becomes clickable (↪ jump the camera).',
  'ping.remove': 'remove',
  'ping.sent.coalition': '📍 Ping → Coalition',
  'ping.sent.player': '📍 Ping → {who}',
  'ping.title': 'Ping',
  'ping.to.coalition': 'To the coalition chat',
  'ping.to.player': "To a player's DM",

  // --- rail — Рельса инструментов в матче: подпись кнопки (.label) + подсказка (.title).
  'rail.chat.label': 'Chat',
  'rail.chat.title': 'Chat',
  'rail.constructor.label': 'Shipyard',
  'rail.constructor.title': 'Constructor — outfit ships, squadrons, army and heroes',
  'rail.corp.label': 'Corp',
  'rail.corp.title': 'Corporation',
  'rail.diplo.label': 'Diplo',
  'rail.diplo.title': 'Diplomacy',
  'rail.exit.label': 'Exit',
  'rail.exit.title': 'Leave session',
  'rail.help.label': 'Help',
  'rail.help.title': 'Codex',
  'rail.log.label': 'Dispatches',
  'rail.log.title': 'Dispatches',
  'rail.market.label': 'Market',
  'rail.market.title': 'Market',
  'rail.msgs.label': 'Mail',
  'rail.msgs.title': 'Messages',
  'rail.settings.label': 'Settings',
  'rail.settings.title': 'Settings',
  'rail.steward.label': 'Sleep',
  'rail.steward.title': 'Steward — hand to the AI while asleep',
  'rail.tech.label': 'Science',
  'rail.tech.title': 'Technologies',
  'rail.toggle.title': 'Tools',

  // --- seatpick — Выбор фракции и места перед входом в сетевой матч.
  'seatpick.bonus.amber': '+15% fleet speed',
  'seatpick.bonus.azure': '+12% economy',
  'seatpick.bonus.crimson': '+10% damage',
  'seatpick.bonus.violet': '+5% economy and +5% damage',
  'seatpick.cancel': 'Back',
  'seatpick.go': 'CHOOSE',
  'seatpick.sub': 'Choose your faction and starting position. Taken seats are marked grey.',
  'seatpick.title': 'Choose Faction',

  // --- setup — Экран «Настройка схватки»: домашний мир, боты, скорость времени.
  'setup.bonus.damage': '+{n}% damage',
  'setup.bonus.economy': '+{n}% economy',
  'setup.bonus.radar': '+{n}% radar',
  'setup.bonus.speed': '+{n}% radar',
  'setup.bonus.speed': '+{n}% fleet speed',
  'setup.cancel': 'Back',
  'setup.faction.note': 'Faction — the house passive bonus',
  'setup.go': 'LAUNCH',
  'setup.home.pick': 'Home: {home} — tap another glowing world to change',
  'setup.home.solo':
    'Home: {home} — a solo sandbox, no rivals · tap another glowing world to change',
  'setup.map-hint': 'Tap a glowing world to choose your start',
  'setup.off': 'OFF',
  'setup.sandbox': '🧪 Sandbox',
  'setup.speed.hint':
    '×1 — real time (an hour of travel = an hour of life, the world runs offline too). For a quick game pick ×10–×100.',
  'setup.speed.label': 'Time speed',
  'setup.start': 'LAUNCH',
  'setup.start.solo': 'LAUNCH SOLO',
  'setup.sub':
    'Pick your homeworld on the map, choose how many AI rivals join, then launch. Empty slots are taken by the AI — switch a slot OFF to command a smaller sector, or switch them all off for a peaceful solo sandbox to explore the interface.',
  'setup.teams.note': 'one side = allies',
  'setup.teams.off': 'Team battle: off',
  'setup.teams.on': 'one side = allies',
  'setup.teams.on': 'Team battle: ON',
  'setup.title': 'SKIRMISH SETUP',

  // --- settings — Экран настроек: интерфейс, цвета сторон, графика.
  'settings.colors.neutral': 'Neutrals',
  'settings.colors.neutral.hint': 'unowned worlds and unidentified forces',
  'settings.colors.own': 'Your colour',
  'settings.colors.own.hint':
    'you on the map and in panels — the shape carries the type, the colour carries the side',
  'settings.colors.palette': 'Rival palette',
  'settings.colors.palette.hint':
    '«colourblind» — hues distinguishable with colour vision deficiency',
  'settings.colors.reset': 'Reset colours to defaults',
  'settings.colors.title': 'Side colours',
  'settings.compact': 'Compact panel mode',
  'settings.compact.hint': 'a denser sector panel — smaller paddings and type (PC)',
  'settings.done': 'DONE',
  'settings.gfx.fps': 'FPS counter',
  'settings.gfx.fps.hint': 'show frames per second in the corner — to check performance',
  'settings.gfx.glow': 'Glow & haloes',
  'settings.gfx.glow.hint':
    'soft bloom around worlds, fleets and borders — turn off for a crisp, faster map',
  'settings.gfx.starfield': 'Star backdrop',
  'settings.gfx.starfield.hint':
    'drifting nebulae and stars in the background — turn off for a flat backdrop',
  'settings.gfx.title': 'Graphics',
  'settings.off': 'off',
  'settings.on': 'on',
  'settings.own-pins': 'My map markers',
  'settings.own-pins.hint': "your own 📍 ping pins — allies' markers always show",
  'settings.palette.classic': 'classic',
  'settings.palette.colorblind': 'colourblind',
  'settings.palette.warm': 'warm',
  'settings.sweep': 'Radar sweep',
  'settings.sweep.hint': 'the rotating beam on the map — visual only, does not affect detection',
  'settings.sweep.opacity': 'Radar sweep opacity',
  'settings.tag': 'interface',
  'settings.title': 'SETTINGS',

  // --- ship — Корабли: корпуса и модули (имя + описание).
  'ship.hull.cruiser': 'Cruiser',
  'ship.hull.dropship': 'Carrier',
  'ship.hull.scout_drone': 'Scout Drone',
  'ship.hull.siege_lance': 'Siege Lance',
  'ship.module.battery.desc': '+30% to attack.',
  'ship.module.battery.name': 'Battery',
  'ship.module.plating.desc': '+25% hull HP.',
  'ship.module.plating.name': 'Plating',
  'ship.module.shield.desc': '+30% to defense.',
  'ship.module.shield.name': 'Shield',
  'ship.module.targeting.desc': '+15% to attack and defense.',
  'ship.module.targeting.name': 'Targeting',
  'ship.module.thruster.desc': '+20% to speed.',
  'ship.module.thruster.name': 'Thruster',

  // --- side — Боковая панель матча: конвейеры, карточка флота, бой, досье мира, вкладки гарнизона.
  'side.arch.artillery': 'artillery',
  'side.arch.combat': 'combat',
  'side.arch.flagship': 'flagship',
  'side.arch.scout': 'scouts',
  'side.arch.swarm': 'swarm',
  'side.arch.transport': 'transports',
  'side.battle.attacker': 'attack',
  'side.battle.defender': 'defense',
  'side.battle.next-round': 'next round in',
  'side.battle.phase.ground': 'landing',
  'side.battle.phase.orbit': 'orbit',
  'side.battle.retreat': '⤺ Retreat',
  'side.battle.retreat.hint':
    "Retreat costs −40% of CURRENT hull and shield (a wounded fleet loses 40% of what remains — retreat never finishes it off) and grants a speed burst to flee. Troops mid-landing can't retreat; a ship in orbit outside battle leaves freely.",
  'side.battle.side.fleet': 'fleet',
  'side.battle.side.garrison': 'garrison',
  'side.battle.side.landing': 'landing',
  'side.battle.title': '⚔ Battle — {phase} · round {r}',
  'side.build.conveyor': 'Building conveyor',
  'side.build.enemy-hidden': 'Enemy construction telemetry unavailable',
  'side.build.hp': 'hp',
  'side.build.upgrade': '▲ Upgrade {c}',
  'side.conveyor.cancel.title': 'Cancel — refunds part of the cost and pauses it',
  'side.conveyor.dequeue.title': 'Remove from the queue',
  'side.conveyor.idle': 'Awaiting orders',
  'side.conveyor.idle.sub': 'ready for next order',
  'side.conveyor.idle.tag': 'IDLE',
  'side.conveyor.now': 'NOW',
  'side.conveyor.paused': 'Paused {n}%',
  'side.conveyor.queue-empty': 'queue empty',
  'side.conveyor.resume.title': 'Resume — pay the remainder',
  'side.conveyor.waiting': 'Waiting for resources: {c}',
  'side.empty': 'Tap a world.',
  'side.fleet.bombarding': 'bombarding',
  'side.fleet.enroute': '↗ en route to {dest} · arrives in',
  'side.fleet.hero-aura': '— projection · +5% attack/defense to this fleet',
  'side.fleet.hull-tag': 'hull {p}%',
  'side.fleet.hunger': 'starving: −25% on the ground',
  'side.fleet.in-orbit': 'in orbit',
  'side.fleet.on-lane': '⟜ holding on the {lane} lane · {p}% across',
  'side.fleet.repair.dock.title': 'Express repair at your own dock for metal',
  'side.fleet.repair.instant.title': 'Instant full-hull repair for credits',
  'side.fleet.ships': 'Ships — tap for specs',
  'side.fleet.sub': '{s} ships · {tr} troops',
  'side.fleet.sub.pc': 'Ships: {s} · Landing: {tr}',
  'side.fleet.tile.hint': 'tap for full specs',
  'side.fleet.troops': 'Carrying troops',
  'side.garrison.plus-troops': '+{n} troops',
  'side.garrison.select': 'Select →',
  'side.garrison.ships': 'Ships in garrison',
  'side.garrison.wing': 'Air wing in garrison',
  'side.ground.conveyor': 'Ground conveyor',
  'side.ground.empty': 'no ground army here',
  'side.ground.hint':
    'Ground units defend your worlds. Load them onto a fleet to capture enemy worlds.',
  'side.ground.load': '▲ Load {u}',
  'side.ground.loading': '⏳ loading: {n} (≈1h each)',
  'side.ground.title': 'Ground army ⇄ garrison',
  'side.ground.units': 'Ground units',
  'side.ground.unload': '▼ Unload {u}',
  'side.group.clear': 'Deselect group',
  'side.group.hint':
    'Press "Move" and tap a destination — every selected fleet routes there and stops. "Merge" fuses the group into one fleet (distant ones fly in first). Shift- or Ctrl/⌘-click a fleet to add it to the group; Shift-drag empty space to box-select several.',
  'side.group.sub': '{f} fleet(s) · {s} ships · {tr} troops',
  'side.group.title': 'TASK GROUP',
  'side.neutral': 'Neutral',
  'side.none': 'none',
  'side.notelemetry.hint': 'Send a fleet toward this system (or extend radar) to detect it.',
  'side.notelemetry.sub': 'Unexplored — outside sensor and radar range. Contents unknown.',
  'side.notelemetry.title': 'NO TELEMETRY',
  'side.scan.buildings': 'Structures',
  'side.scan.garrison': 'Garrison when scanned',
  'side.scan.hint': 'Re-scan with a fleet or radar to refresh.',
  'side.scan.no-buildings': 'none seen',
  'side.scan.owner': 'Owner',
  'side.scan.spy': '🕵 Spy on the world · {c}¤',
  'side.scan.stale': 'Out of sensor range — last scan (may be stale).',
  'side.scan.title': 'LAST KNOWN ✦',
  'side.shipyard.conveyor': 'Shipyard conveyor',
  'side.shipyard.hint': 'The fleet is your weapon and shield. Order ships here to reinforce it.',
  'side.stat.atk': 'ATK',
  'side.stat.def': 'DEF',
  'side.stat.spd': 'SPD',
  'side.strike.assault': '⚔ Assault',
  'side.strike.bombard': '⊗ Bombard',
  'side.strike.bombard.stop': '⊗ Stop bombard',
  'side.strike.forecast':
    'Assault forecast: {v} · ~{r} rounds · losses {a} landing ({pa}%) / {d} garrison ({pd}%)',
  'side.strike.forecast.attacker': 'the landing takes the world',
  'side.strike.forecast.defender': 'the garrison holds',
  'side.strike.forecast.draw': 'a drawn-out stalemate',
  'side.strike.forecast.hint':
    'Forecast from visible compositions only — terrain, fortification and technology bonuses are not included; the real battle may differ.',
  'side.strike.hint':
    "In orbit you can bombard (wears buildings and freezes their output), but the garrison's AA reaches you. Assault lands your troops against the garrison.",
  'side.strike.title': 'Strike',
  'side.summary.attack': 'Attack',
  'side.summary.back': '‹ Back to the card',
  'side.summary.cargo': 'Cargo hold',
  'side.summary.composition': 'Composition',
  'side.summary.day': 'day',
  'side.summary.defense': 'Defense',
  'side.summary.firing-cap': '{n} units firing',
  'side.summary.forced-march': 'forced march',
  'side.summary.hull': 'Hull',
  'side.summary.radar': 'Radar',
  'side.summary.retreat-haste': 'retreat dash',
  'side.summary.shield': 'Shield',
  'side.summary.speed': 'Speed',
  'side.summary.speed.note': 'at the slowest hull; tech/faction/terrain apply per leg',
  'side.summary.title': 'Army summary',
  'side.summary.total': 'total',
  'side.summary.troops': 'landing',
  'side.summary.upkeep': 'Upkeep',
  'side.tab.buildings': 'Buildings',
  'side.tab.fleet': 'Fleet',
  'side.tab.ground': 'Ground',
  'side.tab.wings': 'Wings',
  'side.unit.ground': 'ground',
  'side.unit.space': 'space',
  'side.wing.conveyor': 'Air wing shipyard',
  'side.wing.fuel': 'fuel {n}',
  'side.wing.garrison.hint':
    'A carrier (◈) holds squadrons (△). Launch the wing from the selected fleet\'s panel with "🛩 Launch squadron".',
  'side.wing.hint':
    'Splits the wing off into its own fast strike fleet — send it in while the carrier stays put. Needs at least one non-squadron ship left behind. Countered by orbital AA.',
  'side.wing.launch': '🛩 Launch squadron ({n})',
  'side.wing.patrol-on': '🛩 standing patrol: ON',
  'side.wing.radius': 'radius {r}',
  'side.wing.rearming': 'rearming {n}',
  'side.wing.title': 'Air wing',
  'side.world.blackout': 'blackout: radars and AA −50%',
  'side.world.bonus.defense': 'defense',
  'side.world.bonus.production': 'prod.',
  'side.world.buildings': 'Structures',
  'side.world.capital': 'Capital',
  'side.world.capital.note': '— heroes respawn and re-fit modules here',
  'side.world.count.buildings': 'buildings',
  'side.world.count.ground': 'ground',
  'side.world.count.ships': 'ships',
  'side.world.count.squadrons': 'squadrons',
  'side.world.defense': 'defense {p}',
  'side.world.designation': 'Designation',
  'side.world.fleet-ships': '{n} ships',
  'side.world.fleets': 'Fleets in orbit',
  'side.world.garrison': 'Garrison',
  'side.world.hold': '🚩 Hold',
  'side.world.hold.clear': 'Unmark',
  'side.world.hold.set': '🚩 Mark as a hold point',
  'side.world.hold.title': 'Hold point',
  'side.world.kind': 'Kind / type / terrain',
  'side.world.make-capital': '★ Make capital',
  'side.world.output': 'Base output/h',
  'side.world.output.note': '— world-type lean',
  'side.world.owner': 'Owner',
  'side.world.ping': '📍 Ping',
  'side.world.ping.long': '📍 Ping — mark and send…',
  'side.world.production': 'prod {p}',
  'side.world.spy-window': '🕵 Intel window',
  'side.world.spy-window.left': '{left} left',
  'side.world.stat.garrison': 'garrison',
  'side.world.summary': 'World summary',
  'side.world.type': 'Type: “{pt}” — {mods}',
  'side.world.type-bonuses': 'Type bonuses',
  'side.world.type.long': 'A {pt} world — {mods}',
  'side.world.vp': 'Victory points',

  'side.tiles.empty': 'none',

  // --- speed — Панель времени: подсказки множителей, перезапуска и выхода.
  'speed.exit': 'Exit to menu',
  'speed.mult.half-hour': 'half an hour per second',
  'speed.mult.hour': 'an hour per second',
  'speed.mult.real': 'real time',
  'speed.mult.two-hours': 'two hours per second',
  'speed.restart': 'Restart — back to bot selection',

  // --- steward — «Хранитель»: передача места ИИ на сон, позы, журнал вахты.
  'steward.duration': 'Delegate for',
  'steward.duration.hours': '{h} h',
  'steward.locked': 'The “Steward Protocol” is not researched yet.',
  'steward.locked.go': 'Open technologies',
  'steward.locked.how':
    'Research it in the technology window — then you can hand your seat to the AI while you sleep.',
  'steward.locked.where':
    'The <b>Command</b> branch, opens on <b>Day 16</b> for the <b>Overseer</b> scientist (now day {day}).',
  'steward.log.ago': '{dur} ago',
  'steward.log.counter': '⚔ Counterstrike at {node}: loss forecast {pct}%',
  'steward.log.evac':
    '🏃 Evacuation from {node} → {to}: loss forecast {pct}%, wings withdrawn: {n}',
  'steward.log.evac-failed':
    '⚠ The {node} garrison cannot be evacuated: no transport arrives in time (loss forecast {pct}%)',
  'steward.log.ferry': '🚚 A ferry dispatched to {node} for the garrison',
  'steward.log.held': '🛡 The {node} line held: loss forecast {pct}%',
  'steward.log.reinforce': '🚩 Reinforcement sent to {node}: loss forecast {pct}%',
  'steward.log.sortie': '🛫 A standing patrol raised at {node}',
  'steward.log.title': "Steward's journal",
  'steward.on.active': 'The Steward runs an active defense.',
  'steward.on.active.note':
    'While you sleep: holds the borders, stands squadron patrols and counterstrikes at your own worlds when the loss forecast is acceptable.',
  'steward.on.defense': 'The Steward holds the line.',
  'steward.on.defense.note':
    'While you sleep: holds the borders and repels attacks, keeps building and trading — no offensives.',
  'steward.on.returns': 'Control returns in <b>{dur}</b>.',
  'steward.on.warning':
    '“Autopilot keeps you alive — active play wins.” The defensive posture never attacks and never negotiates.',
  'steward.ready': 'The Steward is ready.',
  'steward.ready.note':
    'Hand your seat to a trusted AI while you are offline — it holds the line and returns control on time.',
  'steward.stance': 'Posture',
  'steward.stance.active': 'Active defense',
  'steward.stance.active.note':
    'Active defense: everything above, plus a counterstrike at your own worlds when the loss forecast is acceptable (under 35%) and standing squadron patrols. It never leaves your territory.',
  'steward.stance.defense': 'Defense',
  'steward.stance.defense.note':
    'The “Defend” posture: holds and repels, keeps building and trading — no offensives, no diplomacy. Control returns automatically, with a morning report.',
  'steward.take-back': 'Take back control',

  // --- tech — Дерево технологий: названия веток.
  'tech.branch.command': 'Command',
  'tech.branch.ground': 'Ground',
  'tech.branch.missile': 'Missiles',
  'tech.branch.space': 'Space',
  'tech.branch.squadron': 'Squadrons',
  'tech.fx.damage': 'damage',
  'tech.fx.fleet-speed': 'fleet speed',
  'tech.fx.production': 'production',
  'tech.fx.radar': 'radar range',
  'tech.group.airwing': 'Air wing',
  'tech.group.arsenal': 'Arsenal',
  'tech.group.automation': 'Automation',
  'tech.group.comms': 'Signals',
  'tech.group.doctrines': 'Doctrines',
  'tech.group.fleet': 'Fleet',
  'tech.group.fortifications': 'Fortifications',
  'tech.group.industry': 'Industry',
  'tech.group.sensors': 'Sensors',
  'tech.node.ace-programs.desc':
    "Ace programmes: elite crews. +6% damage and fleet speed. The Wing Commander's capstone.",
  'tech.node.ai-stewardship.desc':
    'Command automation: hand your seat to a trusted AI while you are offline (asleep) — it holds the line and returns control on time. Powerful, which is why it needs the Overseer scientist and only opens mid-session (day 16).',
  'tech.node.combined-arms.desc': 'Combined arms: infantry and armour in step. +5% damage.',
  'tech.node.deep-survey.desc': 'Deep sensor networks: +15% radar range.',
  'tech.node.flight-decks.desc': 'Flight decks: a fast sortie cycle. +6% fleet speed.',
  'tech.node.fortified-infrastructure.desc':
    'A doctrine of fortified worlds — frontier strongholds.',
  'tech.node.garrison-networks.desc':
    'Garrison networks: the rear supplies itself. +5% production.',
  'tech.node.guidance-arrays.desc': 'Guidance arrays: far-edge telemetry. +10% radar range.',
  'tech.node.industrial-automation.desc': 'Planetary logistics upgrade: +10% production.',
  'tech.node.logistics-command.desc':
    'Logistics command: convoys on schedule. +5% production and fleet speed.',
  'tech.node.meta-drill-combat.desc': 'Meta-progression: +5% damage.',
  'tech.node.meta-drill-radar.desc': 'Meta-progression: +15% radar range.',
  'tech.node.meta-drill-speed.desc': 'Meta-progression: +5% fleet speed.',
  'tech.node.meta-drill-veteran.desc': 'Meta-progression: another +5% speed and damage.',
  'tech.node.meta-industry-2.desc': 'Meta-progression: another +5% production.',
  'tech.node.meta-industry.desc': 'Meta-progression: +5% production.',
  'tech.node.microelectronics-fabrication.desc': 'Orbital foundries: +5% production.',
  'tech.node.orbital-logistics.desc': 'Standardised haulage: +12% fleet speed.',
  'tech.node.planetary-bastions.desc':
    "Planetary bastions: a full-cycle defence industry. +8% damage. The Marshal's capstone.",
  'tech.node.saturation-barrage.desc':
    "Saturation barrage: overwhelms any missile defence. +10% damage. The Missile Chief's capstone.",
  'tech.node.siege-doctrine.desc': 'Long-range siege crews: +8% damage.',
  'tech.node.signal-corps.desc': 'Signal corps: one picture of the battle. +8% radar range.',
  'tech.node.strike-vectors.desc': 'Strike vectors: plotted squadron approaches. +8% damage.',
  'tech.node.void-armadas.desc':
    'Grand-formation doctrine: +6% damage and fleet speed. Requires 5 of your own sectors.',
  'tech.node.warhead-miniaturization.desc':
    'Warhead miniaturisation: a denser salvo per tonne. +6% damage.',

  // --- tech — Дерево технологий: требования узла, рельса дней, состояния и действия.
  'tech.action.done': 'Researched',
  'tech.action.needs-parent': 'Research the node above first',
  'tech.action.no-resources': 'Not enough resources',
  'tech.action.opens-day': 'Opens on Day {n}',
  'tech.action.research': 'Research',
  'tech.action.running': 'In progress — ≈ {n}h',
  'tech.action.unmet': 'Condition not met',
  'tech.curator': 'Branch curated by',
  'tech.curator.none': 'No branch leader — “scientist”-gated nodes stay locked',
  'tech.day': 'Day {n}',
  'tech.from-day': 'from day {n}',
  'tech.grants': 'unlocks: {x}',
  'tech.grants.ability': 'ability: {x}',
  'tech.grants.steward': 'Steward',
  'tech.rail.day': 'DAY',
  'tech.rail.day-short': 'day',
  'tech.rail.start': 'start',
  'tech.req.building': 'building: {b} ×{n}',
  'tech.req.planet': '{p} world ×{n}',
  'tech.req.scientist': 'needs a scientist: {b}',
  'tech.req.scientist.any': 'any branch',
  'tech.req.sectors': 'own sectors: {n}',
  'tech.req.special': 'special condition',
  'tech.req.title': 'Requires:',
  'tech.req.unit': 'unit: {u} ×{n}',
  'tech.slots': 'slots {a}/{b}',
  'tech.state.done': 'RESEARCHED',
  'tech.state.locked': 'LOCKED',
  'tech.state.open': 'AVAILABLE',
  'tech.state.running': 'RESEARCHING',

  // --- upd — Баннер обновления сборки (APK; в браузере не показывается).
  'upd.apk-only': 'updates are only available in the APK',
  'upd.available': 'A new build is available',
  'upd.bad-version': "✗ got a response, but couldn't parse the version",
  'upd.build': 'build {b}',
  'upd.checking': 'check: {msg}',
  'upd.current': '✓ up to date · local {l} · server {r}',
  'upd.go': 'Update',
  'upd.http-error': '✗ GitHub answered {s}',
  'upd.later': 'Later',
  'upd.no-network': "✗ can't reach GitHub (network / VPN?)",

  // --- welcome — Экран приветствия: вход, регистрация, восстановление, список матчей, подвал.
  'welcome.apple': 'Sign in with Apple',
  'welcome.back': '‹ back',
  'welcome.browse.go': 'Refresh list',
  'welcome.browse.nick': 'Callsign',
  'welcome.browse.pass': 'Password',
  'welcome.browse.server': 'Server',
  'welcome.browse.sub': 'Pick a match from the list and join, or refresh it.',
  'welcome.browse.tab.active': 'Active',
  'welcome.browse.tab.archived': 'Archive',
  'welcome.browse.tab.available': 'Available',
  'welcome.browse.title': 'MATCHES',
  'welcome.divider': 'or sign in with',
  'welcome.go': 'Join',
  'welcome.google': 'Sign in with Google',
  'welcome.imprint': 'Imprint',
  'welcome.login': 'Sign in by callsign',
  'welcome.new': 'New Commander',
  'welcome.nick.ph': 'callsign',
  'welcome.pass.again.ph': 'once more',
  'welcome.pass.min.ph': 'at least 8 characters',
  'welcome.pass.ph': 'password (account auto-creates)',
  'welcome.privacy': 'Privacy Policy',
  'welcome.recover.go': 'Send link',
  'welcome.recover.mail': 'Mail',
  'welcome.recover.sub': 'Enter your account email — we will send a password-reset link.',
  'welcome.recover.title': 'Account recovery',
  'welcome.register.go': 'Create commander',
  'welcome.register.mail': 'Email (for recovery)',
  'welcome.register.nick': 'Commander name',
  'welcome.register.pass': 'Password',
  'welcome.register.pass2': 'Repeat password',
  'welcome.register.recover': 'Recover access',
  'welcome.register.sub': 'Choose a callsign and password — that creates your account.',
  'welcome.register.title': 'New Commander',
  'welcome.reset.go': 'Change password',
  'welcome.reset.pass': 'Password',
  'welcome.reset.pass2': 'Repeat password',
  'welcome.reset.sub': 'Choose a new password to sign in.',
  'welcome.reset.title': 'New password',
  'welcome.solo': 'Solo game',
  'welcome.sub': 'Welcome, commander. The fleet awaits your orders.',
  'welcome.support': 'Support',
  'welcome.tagline': 'Edge of the Void',
  'welcome.terms': 'Terms',
  'welcome.testmode': '🧪 Tests · developer mode',
  'welcome.update-check': 'Check for updates',

  // --- win — Заголовки окон матча (сводки, технологии, хранитель, конструкторы).
  'win.divdesign.title': 'DIVISION BUILDER',
  'win.log.recap': 'Return digest',
  'win.log.title': 'DISPATCHES',
  'win.scipick.back': '↩ Menu',
  'win.scipick.title': 'SCIENCE COUNCIL',
  'win.steward.title': 'STEWARD · AI WHILE ASLEEP',
  'win.tech.title': 'TECHNOLOGIES',
};
