// ENGLISH locale. Key → text, mirroring localization/ru.ts.
//
// A key missing here falls back to the Russian source (visible and honest), so an
// untranslated string shows up in Russian rather than as a raw key. The locale
// guard in prototype/src/i18n.test.ts fails on any key present in ru.ts but not here.
export const en: Record<string, string> = {
  // --- data — Имена игровых ДАННЫХ (data/*.json + таблицы прототипа), через tData().
  'data.aa': 'aa',
  'data.artillery': 'artillery',
  'data.asteroid-field': 'Asteroid field',
  'data.barracks': 'Barracks',
  'data.barren': 'Barren',
  'data.bomber': 'bomber',
  'data.carrier': 'carrier',
  'data.credit-refinery': 'Credit Refinery',
  'data.credits': 'credits',
  'data.cruiser': 'cruiser',
  'data.crystalline': 'Crystalline',
  'data.dead-world': 'Dead World',
  'data.debris-field': 'Debris Field',
  'data.deep-void': 'Deep Void',
  'data.dense-nebula': 'Dense Nebula',
  'data.derelict-graveyard': 'Derelict Graveyard',
  'data.dropship': 'dropship',
  'data.empty-space': 'Empty Space',
  'data.energy': 'energy',
  'data.fighter-squadron': 'fighter squadron',
  'data.food': 'food',
  'data.fort': 'Fort',
  'data.fortified-infrastructure': 'Fortified Infrastructure',
  'data.fortress-world': 'Fortress World',
  'data.front': 'front',
  'data.fusion-plant': 'Fusion Plant',
  'data.gas-giant': 'Gas Giant',
  'data.ground': 'ground',
  'data.heavy-infantry': 'heavy infantry',
  'data.hero': 'hero',
  'data.hydroponics-farm': 'Hydroponics Farm',
  'data.industrial-automation': 'Industrial Automation',
  'data.ion-storm': 'Ion Storm',
  'data.irradiated': 'Irradiated',
  'data.metal': 'metal',
  'data.metal-mine': 'Metal Mine',
  'data.microelectronics': 'microelectronics',
  'data.microelectronics-fab': 'Microelectronics Fab',
  'data.microelectronics-fabrication': 'Microelectronics Fabrication',
  'data.militia': 'militia',
  'data.nebula': 'Nebula',
  'data.oceanic': 'Oceanic',
  'data.open-space': 'Open space',
  'data.orbital-aa': 'Orbital AA',
  'data.orbital-logistics': 'Orbital Logistics',
  'data.planet': 'Planet',
  'data.radar-array': 'Radar Array',
  'data.rear': 'rear',
  'data.relic-world': 'Relic World',
  'data.ringworld': 'Ringworld',
  'data.salvage-metal-rig': 'Salvage Metal Rig',
  'data.scout': 'scout',
  'data.siege': 'siege',
  'data.siege-doctrine': 'Siege Doctrine',
  'data.solar-flare-zone': 'Solar Flare Zone',
  'data.space': 'space',
  'data.special-forces': 'special forces',
  'data.squadron': 'squadron',
  'data.strike-carrier': 'strike carrier',
  'data.tank': 'tank',
  'data.tax-office': 'Tax Office',
  'data.terran': 'Terran',
  'data.void-fortress': 'Void Fortress',
  'data.volcanic': 'Volcanic',

  // --- diplo — Дипломатия: названия отношений между игроками.
  'diplo.stance.alliance': 'Alliance',
  'diplo.stance.pact': 'Pact',
  'diplo.stance.peace': 'Peace',
  'diplo.stance.war': 'War',

  // --- err — Отказы ядра (kernel rejection codes). Ключ выводится из кода: E_NO_CAPACITY → err.no-capacity.
  'err.already': 'already in effect',
  'err.already-fitted': 'that fitting is already installed',
  'err.already-offered': 'a proposal is already pending',
  'err.already-unlocked': 'that node is already unlocked',
  'err.bad-effect': 'the ability is misconfigured',
  'err.bad-payload': 'malformed order',
  'err.bad-spawn': 'a hero cannot be deployed here',
  'err.bad-target': 'invalid target',
  'err.bombarded': 'construction under bombardment',
  'err.bot-alliance': 'bots do not join coalitions',
  'err.chat-rate': 'give it a couple of seconds',
  'err.chat-target': 'recipient not found',
  'err.chat-text': 'empty message',
  'err.conditions-unmet': 'conditions not met',
  'err.consent-required': 'the other side must consent',
  'err.cooldown': 'the ability is recharging',
  'err.fleet-busy': 'fleet busy',
  'err.forbidden': 'action forbidden',
  'err.hero-alive': 'the hero already commands a ship',
  'err.hero-cap': 'deployed-hero limit reached',
  'err.hero-dead': 'the hero is dead — wait for the respawn',
  'err.hero-not-deployed': 'the hero is not deployed — raise a ship first',
  'err.insufficient': 'insufficient resources',
  'err.internal': 'internal error',
  'err.limit': 'limit reached',
  'err.no-ability': 'unknown ability',
  'err.no-artillery': 'no artillery',
  'err.no-capacity': 'the hold is full',
  'err.no-capital': 'no capital to recall to',
  'err.no-effect': 'that effect is not implemented yet',
  'err.no-fitting': 'unknown fitting',
  'err.no-fleet': 'fleet not found',
  'err.no-funds': 'insufficient funds',
  'err.no-hero': 'hero not found',
  'err.no-node': 'unknown skill-tree node',
  'err.no-planet': 'world not found',
  'err.no-player': 'player not found',
  'err.no-ships': 'no ships',
  'err.no-shipyard': 'needs a shipyard/spaceport',
  'err.no-slots': 'all fitting slots are taken',
  'err.no-target': 'no target',
  'err.no-troops': 'the world is defended — an assault needs troops aboard',
  'err.not-destructible': 'this world cannot be destroyed',
  'err.not-equipped': 'the hero does not have that ability',
  'err.out-of-range': 'out of range',
  'err.own-planet': 'this is your own world',
  'err.requires': 'unlock the preceding node first',
  'err.research-slots-full': 'all research slots are full',
  'err.respawn-cooldown': 'the hero is still recovering',
  'err.same-location': 'fleet is already here',
  'err.too-early': 'too early',
  'err.unknown-building': 'unknown building',
  'err.unknown-technology': 'unknown technology',
  'err.unknown-unit': 'unknown unit',
  'err.wrong-branch': 'that node belongs to another branch',
  'err.wrong-orbit': 'invalid orbit',
  'err.wrong-sector': 'invalid sector type',

  // --- hero — Герои: грейды, способности (имя + описание).
  'hero.ability.annihilate.desc': 'Destroys a planet in range — it becomes a dead world.',
  'hero.ability.annihilate.name': 'Annihilate',
  'hero.ability.bulwark.desc': 'A temporary shield: +defense to your fleets near the hero.',
  'hero.ability.bulwark.name': 'Bulwark',
  'hero.ability.corridor.desc':
    'Opens a temporary corridor lane to a nearby world; your fleets travel it faster.',
  'hero.ability.corridor.name': 'Corridor',
  'hero.ability.rally.desc':
    'A battle cry: a temporary extra aura bonus for your fleets near the hero.',
  'hero.ability.rally.name': 'Rally',
  'hero.ability.recall.desc': 'Instantly recalls the hero ship to the capital.',
  'hero.ability.recall.name': 'Recall',
  'hero.ability.scan.desc': 'Reveals an area around the target through the fog for a while.',
  'hero.ability.scan.name': 'Scan',
  'hero.grade.common': 'Common',
  'hero.grade.legendary': 'Legendary',
  'hero.grade.main': 'Main',
  'hero.grade.rare': 'Rare',

  // --- hub — Хаб (экран между матчами): шапка, карточки, плитки «Ещё», нижняя навигация.
  'hub.ally.corp': 'Corporation cabinet',
  'hub.ally.empty.sub': 'corporations · shared AvA battles · influence',
  'hub.ally.empty.title': 'Alliances',
  'hub.digest.empty.sub':
    'Join a match on the "Games" tab — moves needing your attention will show up here.',
  'hub.digest.empty.title': 'No matches waiting on an order',
  'hub.digest.section': 'Summary',
  'hub.msgs.aria': 'Messages',
  'hub.nav.ally': 'Alliances',
  'hub.nav.arsenal': 'Arsenal',
  'hub.nav.games': 'Games',
  'hub.nav.home': 'Home',
  'hub.nav.meta': 'Progression',
  'hub.nav.more': 'More',
  'hub.nav.rank': 'Rank',
  'hub.onboard.skip': 'Skip',
  'hub.onboard.start': 'Start tutorial',
  'hub.onboard.sub':
    'A short tutorial walks you through the interface and your first move — a couple of minutes.',
  'hub.onboard.title': 'New to Void Dominion?',
  'hub.play': 'PLAY NOW',
  'hub.rank.empty.sub': 'a seasonal rank from match placements',
  'hub.rank.empty.title': 'Rankings — coming soon',
  'hub.season.sub': 'Rankings and alliances unlock once the meta-layer launches.',
  'hub.season.title': 'The season has not started',
  'hub.solo': 'Solo game',
  'hub.status.online': 'online',
  'hub.tile.account': 'Account',
  'hub.tile.chat': 'Chat',
  'hub.tile.community': 'Community',
  'hub.tile.help': 'Codex',
  'hub.tile.logout': 'Switch commander',
  'hub.tile.notifications': 'Notifications',
  'hub.tile.settings': 'Settings',
  'hub.tile.support': 'Support',
  'hub.tile.tutorial': 'Tutorial',
  'hub.tile.updates': 'Updates',

  // --- hud — Постоянный интерфейс матча: верхняя панель ресурсов.
  'hud.resource.credits': 'Credits',
  'hud.resource.energy': 'Energy',
  'hud.resource.food': 'Food',
  'hud.resource.metal': 'Metal',
  'hud.resource.microelectronics': 'Microelectronics',

  // --- market — Биржа: вкладки ресурсов.
  'market.res.energy': 'Energy',
  'market.res.food': 'Food',
  'market.res.metal': 'Metal',
  'market.res.microelectronics': 'Micro',

  // --- rail — Рельса инструментов в матче: подпись кнопки (.label) + подсказка (.title).
  'rail.chat.label': 'Chat',
  'rail.chat.title': 'Chat',
  'rail.constructor.label': 'Shipyard',
  'rail.constructor.title': 'Constructor — outfit ships, squadrons, army and heroes',
  'rail.corp.label': 'Corp',
  'rail.corp.title': 'Corporation',
  'rail.diplo.label': 'Diplo',
  'rail.diplo.title': 'Diplomacy',
  'rail.exit.label': 'Exit',
  'rail.exit.title': 'Leave session',
  'rail.help.label': 'Help',
  'rail.help.title': 'Codex',
  'rail.log.label': 'Dispatches',
  'rail.log.title': 'Dispatches',
  'rail.market.label': 'Market',
  'rail.market.title': 'Market',
  'rail.msgs.label': 'Mail',
  'rail.msgs.title': 'Messages',
  'rail.settings.label': 'Settings',
  'rail.settings.title': 'Settings',
  'rail.steward.label': 'Sleep',
  'rail.steward.title': 'Steward — hand to the AI while asleep',
  'rail.tech.label': 'Science',
  'rail.tech.title': 'Technologies',

  // --- seatpick — Выбор фракции и места перед входом в сетевой матч.
  'seatpick.cancel': 'Back',
  'seatpick.go': 'CHOOSE',
  'seatpick.sub': 'Choose your faction and starting position. Taken seats are marked grey.',
  'seatpick.title': 'Choose Faction',

  // --- setup — Экран «Настройка схватки»: домашний мир, боты, скорость времени.
  'setup.cancel': 'Back',
  'setup.go': 'LAUNCH',
  'setup.map-hint': 'Tap a glowing world to choose your start',
  'setup.sandbox': '🧪 Sandbox',
  'setup.speed.hint':
    '×1 — real time (an hour of travel = an hour of life, the world runs offline too). For a quick game pick ×10–×100.',
  'setup.speed.label': 'Time speed',
  'setup.sub':
    'Pick your homeworld on the map, choose how many AI rivals join, then launch. Empty slots are taken by the AI — switch a slot OFF to command a smaller sector, or switch them all off for a peaceful solo sandbox to explore the interface.',
  'setup.title': 'SKIRMISH SETUP',

  // --- ship — Корабли: корпуса и модули (имя + описание).
  'ship.hull.cruiser': 'Cruiser',
  'ship.hull.dropship': 'Carrier',
  'ship.hull.scout_drone': 'Scout Drone',
  'ship.hull.siege_lance': 'Siege Lance',
  'ship.module.battery.desc': '+30% to attack.',
  'ship.module.battery.name': 'Battery',
  'ship.module.plating.desc': '+25% hull HP.',
  'ship.module.plating.name': 'Plating',
  'ship.module.shield.desc': '+30% to defense.',
  'ship.module.shield.name': 'Shield',
  'ship.module.targeting.desc': '+15% to attack and defense.',
  'ship.module.targeting.name': 'Targeting',
  'ship.module.thruster.desc': '+20% to speed.',
  'ship.module.thruster.name': 'Thruster',

  // --- speed — Панель времени: подсказки множителей, перезапуска и выхода.
  'speed.exit': 'Exit to menu',
  'speed.mult.half-hour': 'half an hour per second',
  'speed.mult.hour': 'an hour per second',
  'speed.mult.real': 'real time',
  'speed.mult.two-hours': 'two hours per second',
  'speed.restart': 'Restart — back to bot selection',

  // --- tech — Дерево технологий: названия веток.
  'tech.branch.command': 'Command',
  'tech.branch.ground': 'Ground',
  'tech.branch.missile': 'Missiles',
  'tech.branch.space': 'Space',
  'tech.branch.squadron': 'Squadrons',

  // --- upd — Баннер обновления сборки (APK; в браузере не показывается).
  'upd.available': 'A new build is available',
  'upd.go': 'Update',
  'upd.later': 'Later',

  // --- welcome — Экран приветствия: вход, регистрация, восстановление, список матчей, подвал.
  'welcome.apple': 'Sign in with Apple',
  'welcome.back': '‹ back',
  'welcome.browse.go': 'Refresh list',
  'welcome.browse.nick': 'Callsign',
  'welcome.browse.pass': 'Password',
  'welcome.browse.server': 'Server',
  'welcome.browse.sub': 'Pick a match from the list and join, or refresh it.',
  'welcome.browse.tab.active': 'Active',
  'welcome.browse.tab.archived': 'Archive',
  'welcome.browse.tab.available': 'Available',
  'welcome.browse.title': 'MATCHES',
  'welcome.divider': 'or sign in with',
  'welcome.go': 'Join',
  'welcome.google': 'Sign in with Google',
  'welcome.imprint': 'Imprint',
  'welcome.login': 'Sign in by callsign',
  'welcome.new': 'New Commander',
  'welcome.nick.ph': 'callsign',
  'welcome.pass.again.ph': 'once more',
  'welcome.pass.min.ph': 'at least 8 characters',
  'welcome.pass.ph': 'password (account auto-creates)',
  'welcome.privacy': 'Privacy Policy',
  'welcome.recover.go': 'Send link',
  'welcome.recover.mail': 'Mail',
  'welcome.recover.sub': 'Enter your account email — we will send a password-reset link.',
  'welcome.recover.title': 'Account recovery',
  'welcome.register.go': 'Create commander',
  'welcome.register.mail': 'Email (for recovery)',
  'welcome.register.nick': 'Commander name',
  'welcome.register.pass': 'Password',
  'welcome.register.pass2': 'Repeat password',
  'welcome.register.recover': 'Recover access',
  'welcome.register.sub': 'Choose a callsign and password — that creates your account.',
  'welcome.register.title': 'New Commander',
  'welcome.reset.go': 'Change password',
  'welcome.reset.pass': 'Password',
  'welcome.reset.pass2': 'Repeat password',
  'welcome.reset.sub': 'Choose a new password to sign in.',
  'welcome.reset.title': 'New password',
  'welcome.solo': 'Solo game',
  'welcome.sub': 'Welcome, commander. The fleet awaits your orders.',
  'welcome.support': 'Support',
  'welcome.tagline': 'Edge of the Void',
  'welcome.terms': 'Terms',
  'welcome.testmode': '🧪 Tests · developer mode',
  'welcome.update-check': 'Check for updates',

  // --- win — Заголовки окон матча (сводки, технологии, хранитель, конструкторы).
  'win.divdesign.title': 'DIVISION BUILDER',
  'win.log.recap': 'Return digest',
  'win.log.title': 'DISPATCHES',
  'win.scipick.back': '↩ Menu',
  'win.scipick.title': 'SCIENCE COUNCIL',
  'win.steward.title': 'STEWARD · AI WHILE ASLEEP',
  'win.tech.title': 'TECHNOLOGIES',
};
