// РУССКАЯ локаль. Ключ → текст. Русский здесь — ИСТОЧНИК: именно он показывается,
// когда в выбранной локали ключа ещё нет (см. localization/index.ts).
//
// Ключ = домен.сущность.аспект, точки — иерархия, kebab-case внутри сегмента:
//   err.no-capacity · data.metal-mine · hero.ability.corridor.desc
//
// НЕ добавляй сюда русский текст, который уже лежит в коде строкой — сначала
// заведи ключ, потом замени строку в коде на t('ключ').
export const ru: Record<string, string> = {
  // --- acc / browser — Аккаунты (вход, регистрация, сессия) и браузер матчей.
  'acc.bad-pass': 'Неверный пароль',
  'acc.created': 'Аккаунт создан',
  'acc.join-closed': 'вход закрыт',
  'acc.join-failed': 'не удалось войти',
  'acc.login-refused': 'Вход отклонён',
  'acc.mail-taken': 'Эта почта уже занята',
  'acc.nick.rule': 'Позывной для аккаунта: 3–24 символа — буквы, цифры, _ или -',
  'acc.pass.rule': 'Введите пароль (мин. 8 символов)',
  'acc.rate-limited': 'Слишком часто — подождите',
  'acc.reconnect-failed': 'Переподключение не удалось — войди заново',
  'acc.reconnecting': '⟳ переподключение…',
  'acc.register-refused': 'Регистрация отклонена',
  'acc.seats-full': 'все места заняты',
  'acc.server-down': 'сервер недоступен',
  'acc.session-expired': 'Сессия истекла — введите пароль ещё раз',
  'browser.archive': 'В архив',
  'browser.archive-error': 'ошибка архива',
  'browser.archive-failed': 'не удалось в архив',
  'browser.day': 'День {n}',
  'browser.empty': 'здесь пусто',
  'browser.finished': 'завершён',
  'browser.free': 'свободно',
  'browser.goal.map': '{p}% карты',
  'browser.goal.score': 'до {n} очк.',
  'browser.join': 'Войти',
  'browser.join-window': 'вход ещё {dur}',
  'browser.left.days': '{d}д {h}ч',
  'browser.left.hours': '{h}ч',
  'browser.left.soon': '<1ч',
  'browser.loading': 'загрузка матчей…',
  'browser.players': '{s}/{c} игроков',
  'browser.refresh-hint': 'нажмите «Обновить список»',
  'browser.restore': 'Восстановить',
  'browser.restore-failed': 'не удалось восстановить',
  'browser.running': 'идёт',
  'browser.server-down': 'сервер недоступен — укажи адрес сервера',
  'browser.slots': 'слотов',
  'browser.solo': 'Одиночный режим',
  'browser.solo.hint': 'Сервер не нужен — свободные места займут боты.',
  'browser.taken': 'занято',

  // --- ai — Красный ИИ: условия конца матча и отказы дежурного вылета.
  'ai.end.domination': 'доминированием в галактике',
  'ai.end.elimination': 'уничтожением соперников',
  'ai.end.over': 'матч завершён',
  'ai.end.score': 'достижением лимита очков',
  'ai.end.timeout': 'истечением времени',
  'ai.sortie.docked-only': '🛩 дежурный вылет — только со стоянки в узле',
  'ai.sortie.idle-only': '🛩 дежурный вылет — только когда флот свободен',

  // --- arsenal — «Арсенал»: коллекция аккаунта, фильтр, пустое состояние.
  'arsenal.empty': 'Арсенал пуст',
  'arsenal.empty.hint': 'войдите под аккаунтом на сервере с накоплением, чтобы увидеть коллекцию',
  'arsenal.filter.all': 'Всё',

  // --- auth — Вход и регистрация: позывной, сторонние провайдеры.
  'auth.apple.soon': 'Вход через Apple — скоро · ты вошёл гостем',
  'auth.commander': 'Командир',
  'auth.google.soon': 'Вход через Apple — скоро · ты вошёл гостем',
  'auth.google.soon': 'Вход через Google — скоро · ты вошёл гостем',
  'auth.need-mail': 'Введите почту',
  'auth.need-name': 'Введи имя командира',
  'auth.need-nick': 'Введи позывной',
  'auth.pass-mismatch': 'Пароли не совпадают',
  'auth.recover.sent': 'Если такая почта есть — прислали ссылку для сброса',
  'auth.reset.bad-link': 'Ссылка недействительна или устарела',
  'auth.reset.done': 'Пароль изменён',

  // --- back — Кнопка «Назад» (APK/десктоп): подтверждение выхода.
  'back.confirm': 'Ещё раз «Назад» — выход',
  'back.confirm.match': 'Ещё раз «Назад» — выход из матча',

  // --- card — Карточка игрока (тап по гербу): фракция, владения, боевой счёт.
  'card.close': 'ЗАКРЫТЬ',
  'card.combat': 'Боевой счёт',
  'card.commander': 'командующий',
  'card.diplomacy': 'Дипломатия',
  'card.faction': 'Фракция',
  'card.kills': '⚔ Уничтожено юнитов врага',
  'card.losses': '☠ Потеряно своих',
  'card.score': 'Очки',
  'card.score.goal': 'ПОБЕДА',
  'card.stances': 'Отношения',
  'card.units': 'Юнитов',
  'card.worlds': 'Миров под контролем',

  // --- cargo — Погрузка десанта: отказы трюма и гарнизона.
  'cargo.garrison-empty': 'в гарнизоне не осталось',
  'cargo.hold-full': 'трюм полон',

  // --- chat / spy — Переписка (сессия и коалиция) и вкладка шпионажа.
  'chat.coalition.empty': 'Чат коалиции пуст.<br>Отметьте провинцию пингом 📍 или напишите.',
  'chat.empty': 'Сообщений пока нет.',
  'chat.head.coalition': '⚡ Коалиция · {n} уч.',
  'chat.head.session': '△ Сессия · {n} в матче',
  'chat.input.ph': 'Сообщение…',
  'chat.jump': '↪ камера',
  'chat.members': '{n} уч.',
  'chat.open-card': 'Открыть карточку игрока',
  'chat.ping': 'Отметить выбранную провинцию пингом',
  'chat.session.note': 'Общий канал матча — вас слышат все участники.',
  'chat.tab.coalition': 'Коалиция',
  'chat.tab.session': 'Сессия',
  'chat.you': 'Вы',
  'spy.log.empty': 'попыток ещё не было',
  'spy.log.title': 'ЖУРНАЛ',
  'spy.note':
    'Попытка: {c}¤ · шанс ~60% · окно интела 24ч · провал сжигает плату. Разведка мира — кнопка 🕵 на карточке вражеской планеты.',
  'spy.op.fleets': 'флоты',
  'spy.ops.empty': 'противников нет',
  'spy.ops.title': 'ОПЕРАЦИИ',
  'spy.windows.empty': 'нет активных окон — добудьте интел операцией ниже',
  'spy.windows.title': 'АКТИВНЫЕ ОКНА ИНТЕЛА',

  // --- chat.win — Плавающее окно чата (десктоп): каналы, настройки окна, штамп.
  'chat.ping.mark': 'метка {node}',
  'chat.ping.need-province': 'Сначала выберите провинцию на карте',
  'chat.ping.need-province.short': 'Сначала выберите провинцию',
  'chat.tab.global': 'Глобальный',
  'chat.win.censor': 'Цензура',
  'chat.win.collapse': 'Свернуть',
  'chat.win.color': 'Цвет шрифта',
  'chat.win.color.premium': 'подписка',
  'chat.win.drag': 'Тащите за шапку, чтобы переместить',
  'chat.win.empty': 'Канал «{ch}» пуст.',
  'chat.win.empty.hint': 'Напишите первое сообщение.',
  'chat.win.expand': 'Развернуть',
  'chat.win.font': 'Шрифт, пт',
  'chat.win.opacity': 'Прозрачность',
  'chat.win.pin': 'Закрепить размер и положение',
  'chat.win.send': 'Отправить',
  'chat.win.settings': 'Настройки',
  'chat.win.size': 'Размер h,w',
  'chat.win.stamp': 'Штамп сообщений',
  'chat.win.stamp.day': 'День',
  'chat.win.stamp.real': 'Реальное время',
  'chat.win.stamp.time': 'Время',
  'chat.win.title': 'ЧАТ — {ch}',

  // --- cmd — Командная панель флота: приказы, режим огня артиллерии, способности героя.
  'cmd.assault': 'Штурм',
  'cmd.assault.hint': 'лететь к чужому миру и высадить десант при подходе',
  'cmd.auto-assault': 'Авто-штурм',
  'cmd.auto-assault.hint': 'флот сам штурмует вражеский мир по прибытии',
  'cmd.barrage': 'Обстрел',
  'cmd.barrage.hint': 'сосредоточить огонь артиллерии по вражескому флоту с дистанции',
  'cmd.cast': 'Каст',
  'cmd.cast.cooldown': 'КД {h}',
  'cmd.cast.hint': 'применить способность героя из состава флота',
  'cmd.cast.needs-target': 'цель на карте',
  'cmd.cast.self': 'на месте',
  'cmd.fire.aggressive': 'Агрес',
  'cmd.fire.aggressive.hint': 'по любому, кроме пакта/союза',
  'cmd.fire.hint': 'когда артиллерия стреляет сама: пассив · ответ · станд · агрес',
  'cmd.fire.passive': 'Пассив',
  'cmd.fire.passive.hint': 'не стреляет',
  'cmd.fire.return': 'Ответ',
  'cmd.fire.return.hint': 'только после урона по флоту',
  'cmd.fire.standard': 'Станд',
  'cmd.fire.standard.hint': 'по тем, с кем война',
  'cmd.fire.title': 'Режим огня',
  'cmd.forced-march': 'Ускорить',
  'cmd.forced-march.hint': 'форс-марш: +50% скорости ценой −5% прочности за час хода',
  'cmd.merge': 'Слить',
  'cmd.merge.hint': 'объединить выбранные флоты в один',
  'cmd.merge.pick': 'Слить…',
  'cmd.more': 'Ещё',
  'cmd.more.hint': 'дополнительные приказы',
  'cmd.move': 'Курс',
  'cmd.move.hint': 'выберите планету — флот пойдёт к ней по звёздным трассам',
  'cmd.multiselect': 'Выбрать+',
  'cmd.multiselect.hint': 'добавлять флоты в группу по одному тапу',
  'cmd.selection.many': '{n} ФЛОТОВ',
  'cmd.selection.one': 'ФЛОТ',
  'cmd.split': 'Делить',
  'cmd.split.hint': 'отделить часть кораблей пришвартованного флота в новый',
  'cmd.standing-sortie': 'Деж. вылет',
  'cmd.standing-sortie.hint': 'эскадрилья автоматически бьёт врага в радиусе',
  'cmd.stop': 'Стоп',
  'cmd.stop.hint': 'отменить текущее движение флота',
  'cmd.target': 'Цель',
  'cmd.target.hint': 'тап по карте — собрать приказ: ждать · курс · штурм · обстрел',

  // --- codex — Кодекс: карточка здания/юнита/модуля (строки характеристик) и статьи-термины.
  'codex.hub.close': 'ЗАКРЫТЬ',
  'codex.hub.empty': 'Ничего не найдено',
  'codex.hub.search.aria': 'Поиск по справочнику',
  'codex.hub.search.ph': 'Поиск: юнит, здание, термин…',
  'codex.hub.sec.building': 'Здания',
  'codex.hub.sec.mechanic': 'Механики',
  'codex.hub.sec.unit': 'Юниты',
  'codex.hub.title': 'СПРАВОЧНИК',
  'codex.row.aa': 'ПВО',
  'codex.row.atk-def': 'Атака / Оборона',
  'codex.row.build-time': 'Время постройки',
  'codex.row.cargo': 'Вместимость трюма',
  'codex.row.class': 'Класс',
  'codex.row.cost': 'Стоимость',
  'codex.row.garrison-defense': 'Оборона гарнизона',
  'codex.row.hp': 'Прочность',
  'codex.row.hull': 'Корпус',
  'codex.row.levels': 'Уровней',
  'codex.row.produces': 'Производит',
  'codex.row.radar': 'Радиус радара',
  'codex.row.range': 'Дальность',
  'codex.row.score': 'Очки победы',
  'codex.row.signature': 'Радарная сигнатура',
  'codex.row.slot': 'Слот',
  'codex.row.speed': 'Скорость',
  'codex.row.upkeep': 'Содержание',
  'codex.tag.building': 'здание',
  'codex.tag.fitting': 'фитинг',
  'codex.tag.ground-unit': 'наземный юнит',
  'codex.tag.mechanic': 'механика',
  'codex.tag.module': 'модуль',
  'codex.tag.ship': 'корабль',
  'codex.term.async.body':
    'Мир идёт в реальном времени и продолжается 24/7 — даже когда ты вышел. Приказы занимают реальные часы: отдал курс, закрыл игру, вернулся к результату. Это не пошаговая игра — заходи, отдавай приказы, выходи.',
  'codex.term.async.title': 'Асинхронный мир',
  'codex.term.capture.body':
    'Захват мира — двухфазный. Сначала выйди на орбиту и подави оборону в космосе; если мир защищён гарнизоном — высади десант (наземную дивизию из трюма). Небо, потом земля.',
  'codex.term.capture.title': 'Орбита и высадка',
  'codex.term.coalition.body':
    'Дипломатия позволяет заключать пакты и союзы, но коалиция ограничена порогом совокупной силы — нельзя собрать всех против одного. Порог держит баланс сил и не даёт «снежному кому» задавить партию.',
  'codex.term.coalition.title': 'Коалиционный порог',
  'codex.term.fog.body':
    'Ты видишь только то, что рядом с твоими силами и радарами; остальное скрыто туманом или показано по памяти (последнее, что ты там видел). Разведчики и радары раздвигают обзор — держи глаза открытыми.',
  'codex.term.fog.title': 'Туман войны',
  'codex.term.lanes.body':
    'Флоты ходят не напрямую, а по звёздным трассам (лэйнам) между мирами — маршрут строится автоматически. Узлы на трассах можно перехватывать: встречный враг на пути — это бой.',
  'codex.term.lanes.title': 'Звёздные трассы',
  'codex.term.score.body':
    'Очки капают за то, чем ты владеешь: мир — 50, прочий сектор — 10, здания добавляют по уровню. Набери порог очков — победа. Другой путь к победе — уничтожение соперников или доминирование.',
  'codex.term.score.title': 'Очки победы',
  'codex.term.upkeep.body':
    'Флоты и здания требуют ежедневной платы. Доход от шахт минус содержание = чистый баланс; уйдёшь в минус — казна опустеет. Строй экономику раньше армии.',
  'codex.term.upkeep.title': 'Содержание (upkeep)',
  'codex.value.hours': '{n} ч',
  'codex.value.levels-upgradable': '{n} (улучшаемо)',
  'codex.value.per-day': '{n} {r}/день',
  'codex.value.per-hour': '{n} {r}/ч',
  'codex.value.per-level': '{n} / уровень',

  // --- comms — Меню связи: ростер сессии, одобрение ботов, окна интела, предложения.
  'comms.bots-no-coalition': 'Боты не вступают в коалиции',
  'comms.favour.brink': 'на грани войны',
  'comms.favour.embargo': 'эмбарго',
  'comms.favour.friendly': 'дружелюбно',
  'comms.favour.note':
    'Одобрение бота: {f}/{base} — {label}. Ниже {emb} бот вводит эмбарго на рынке, ниже {war} — объявляет войну.',
  'comms.filter.empty': 'Под фильтр никто не подходит.',
  'comms.global.soon': 'глобальный канал появится вместе с глобальным сервером',
  'comms.intel.fleets': 'флоты видны на карте <em>{left}</em>',
  'comms.intel.treasury': 'казна: <b>{bag}</b> <em>{left}</em>',
  'comms.intel.world': 'мир <b>{id}</b> раскрыт <em>{left}</em>',
  'comms.offer.incoming': '{who} предлагает — нажмите, чтобы принять',
  'comms.offer.sent': 'предложение уже отправлено',
  'comms.provinces': 'провинций',
  'comms.spy.fleets':
    'Украсть данные о флотах · {c}¤ · шанс ~60% · окно 24ч (плата сгорает и при провале)',
  'comms.spy.treasury':
    'Украсть данные казны · {c}¤ · шанс ~60% · окно 24ч (плата сгорает и при провале)',
  'comms.stance-changed': '🕊 {who}: отношения → {stance}',
  'comms.stance-changed.short': 'Стойка изменена: {stance}',
  'comms.war-declared': '⚔ {who} объявил вам войну!',
  'comms.you': 'ВЫ',

  // --- corp — Кабинет корпорации и войны альянсов (AvA): состав, заявки, готовность, вызовы.
  'corp.apply': 'Заявиться',
  'corp.browse.empty': 'Пока нет других корпораций.',
  'corp.browse.title': 'Найти и подать заявку',
  'corp.card.influence': 'влияние',
  'corp.card.members': 'участников',
  'corp.card.none': 'Без корпорации',
  'corp.card.role': 'роль',
  'corp.chat.soon': 'Чат — скоро',
  'corp.chat.soon.hint': 'постоянный корп-чат ждёт мета-слой; журнал действий — во вкладке «Обзор»',
  'corp.close': 'Закрыть',
  'corp.create.go': 'Создать',
  'corp.create.name-ph': 'Название (3–24 символа)',
  'corp.create.title': 'Создать корпорацию',
  'corp.disband': 'Расформировать корпорацию',
  'corp.empty': 'Пока пусто.',
  'corp.history': 'История',
  'corp.history.private': 'История видна главе и офицерам.',
  'corp.holdings.note':
    'Пассивные бонусы владений придут вместе с мета-слоем секторов — пока их нет.',
  'corp.holdings.soon': 'Владения — скоро',
  'corp.holdings.soon.hint': 'мета-карта секторов появится вместе со вторым контуром метагейма',
  'corp.influence': 'Влияние',
  'corp.influence.hint':
    'Тратится на вызов AvA (100 ⟡ по умолчанию) — кнопка «Вызвать» во вкладке «Войны».',
  'corp.leave': 'Покинуть корпорацию',
  'corp.log': 'Журнал',
  'corp.log.private': 'Журнал виден главе и офицерам.',
  'corp.members.count': '{n} участников',
  'corp.my-role': 'Моя роль',
  'corp.overview.name': 'Корпорация',
  'corp.ready.clear': 'снять',
  'corp.ready.corp': 'Готовность корпорации',
  'corp.ready.lead-only': 'только глава',
  'corp.ready.mine': 'Моя готовность',
  'corp.ready.no': 'нет',
  'corp.ready.set': 'готов',
  'corp.ready.to-pool': 'в пул',
  'corp.ready.yes': 'да ✓',
  'corp.request.accept': 'принять',
  'corp.request.reject': 'отклонить',
  'corp.transfer-lead': 'передать главенство',
  'corp.war.accept': 'Принять',
  'corp.war.by-us': 'вызов от нас',
  'corp.war.cancelled': 'отменён',
  'corp.war.challenge': 'Вызвать',
  'corp.war.decline': 'Отклонить',
  'corp.war.declined': 'отклонён',
  'corp.war.draw': 'ничья',
  'corp.war.expired': 'истёк',
  'corp.war.feed': 'Публичная лента AvA',
  'corp.war.finished': 'завершён',
  'corp.war.incoming': 'входящий вызов',
  'corp.war.join-roster': 'Заявиться в состав',
  'corp.war.locked': 'заперт — скоро бой',
  'corp.war.mine': 'Мои вызовы',
  'corp.war.none': 'Пока нет вызовов.',
  'corp.war.pending': 'ждёт ответа',
  'corp.war.pool': 'Готовые к войне',
  'corp.war.pool-empty': 'Пул пуст.',
  'corp.war.roster': 'набор ростера',
  'corp.war.roster-label': 'состав',
  'corp.war.roster-open': 'идёт набор ростера',
  'corp.war.scheduled': 'назначен',
  'corp.war.to-us': 'вызов нам',
  'corp.war.win': 'победа',
  'corp.you': 'вы',

  'codex.build-here': 'Построить здесь',
  'codex.close': 'ЗАКРЫТЬ',

  // --- data — Имена игровых ДАННЫХ (data/*.json + таблицы прототипа), через tData().
  'data.aa': 'ПВО',
  'data.artillery': 'артиллерия',
  'data.asteroid-field': 'Астероидное поле',
  'data.barracks': 'Казармы',
  'data.barren': 'Безжизненный',
  'data.bomber': 'бомбардировщик',
  'data.carrier': 'носитель',
  'data.credit-refinery': 'Кредитный НПЗ',
  'data.credits': 'кредиты',
  'data.cruiser': 'крейсер',
  'data.crystalline': 'Кристаллический',
  'data.dead-world': 'Мёртвый мир',
  'data.debris-field': 'Поле обломков',
  'data.deep-void': 'Глубокая пустота',
  'data.dense-nebula': 'Плотная туманность',
  'data.derelict-graveyard': 'Кладбище кораблей',
  'data.dropship': 'носитель',
  'data.empty-space': 'Пустое пространство',
  'data.energy': 'энергия',
  'data.fighter-squadron': 'истребительная эскадрилья',
  'data.food': 'пища',
  'data.fort': 'Форт',
  'data.fortified-infrastructure': 'Укреплённая инфраструктура',
  'data.fortress-world': 'Мир-крепость',
  'data.front': 'передняя линия',
  'data.fusion-plant': 'Термоядерная станция',
  'data.gas-giant': 'Газовый гигант',
  'data.ground': 'земля',
  'data.heavy-infantry': 'тяжёлая пехота',
  'data.hero': 'флагман',
  'data.hydroponics-farm': 'Гидропонная ферма',
  'data.industrial-automation': 'Промышленная автоматизация',
  'data.ion-storm': 'Ионный шторм',
  'data.irradiated': 'Облучённый',
  'data.metal': 'металл',
  'data.metal-mine': 'Металлодобыча',
  'data.microelectronics': 'микроэлектроника',
  'data.microelectronics-fab': 'Фабрика микроэлектроники',
  'data.microelectronics-fabrication': 'Производство микроэлектроники',
  'data.militia': 'ополчение',
  'data.nebula': 'Туманность',
  'data.oceanic': 'Океанический',
  'data.open-space': 'Открытый космос',
  'data.orbital-aa': 'Орбитальное ПВО',
  'data.orbital-logistics': 'Орбитальная логистика',
  'data.planet': 'Планета',
  'data.radar-array': 'Радарный массив',
  'data.rear': 'тыл',
  'data.relic-world': 'Реликтовый мир',
  'data.ringworld': 'Кольцевой мир',
  'data.salvage-metal-rig': 'Утилизационная станция',
  'data.scout': 'разведчик',
  'data.siege': 'осадная платформа',
  'data.siege-doctrine': 'Осадная доктрина',
  'data.solar-flare-zone': 'Зона солнечных вспышек',
  'data.space': 'космос',
  'data.special-forces': 'спецназ',
  'data.squadron': 'эскадрилья',
  'data.strike-carrier': 'ударный носитель',
  'data.tank': 'танк',
  'data.tax-office': 'Налоговая управа',
  'data.terran': 'Земной',
  'data.void-fortress': 'Крепость пустоты',
  'data.volcanic': 'Вулканический',

  // --- diplo — Дипломатия: окно, вкладки, фильтр и сортировка ростера, названия отношений.
  'diplo.filter': 'Фильтр',
  'diplo.filter.ai': 'ИИ',
  'diplo.filter.human': 'Человек',
  'diplo.filter.reset': 'Сброс',
  'diplo.sort': 'Сорт.',
  'diplo.sort.name': 'Имя',
  'diplo.sort.provinces': 'Провинции',
  'diplo.sort.stance': 'Отношение',
  'diplo.stance.alliance': 'Союз',
  'diplo.stance.pact': 'Пакт',
  'diplo.stance.peace': 'Мир',
  'diplo.stance.war': 'Война',
  'diplo.tab.diplomacy': 'Дипломатия',
  'diplo.tab.espionage': 'Шпионаж',
  'diplo.tab.messages': 'Сообщения',
  'diplo.win.title': 'ДИПЛОМАТИЯ',

  // --- div — Дивизии: список, мобилизация, конструктор, трюм.
  'div.damage-vs': 'Урон по:',
  'div.designer': '⚙ Конструктор',
  'div.empty': 'Нет дивизий.',
  'div.empty.hint': 'Нет дивизий — мобилизуй по шаблону ниже.',
  'div.hold': 'Дивизии ⇄ трюм (своб. {n})',
  'div.hold.note': 'Загрузка погружает дивизию в трюм. Выгрузка высаживает её на этот мир.',
  'div.mobilize': 'Мобилизация',
  'div.mobilize.named': 'Мобилизовать «{name}»',
  'div.note':
    'Дивизия — снапшот шаблона: правка шаблона в конструкторе не меняет уже собранные. На своём мире +1 HP/юнит/день.',
  'div.officer-locked': 'Именной шаблон офицера: состав закреплён, редактировать нельзя.',
  'div.rename': 'Переименовать',
  'div.roster': 'состав {n}/{s} · {rest}',
  'div.slot.note':
    'Тап по слоту меняет род войск: ополчение → тяжёлая пехота → спецназ → танк. Танки бьют любую пехоту; спецназ — единственная пехота, опасная танкам; тяжёлая пехота держит оборону.',
  'div.stat.attack': 'живучесть',
  'div.stat.attack': 'оборона',
  'div.stat.attack': 'атака',
  'div.stat.defense': 'оборона',
  'div.stat.hp': 'живучесть',
  'div.title': 'Дивизии',

  // --- dossier — Досье объектов: здания, корабли, стройка в очереди, вкладки и характеристики.
  'dossier.building.barracks':
    'Казармы нужны для защиты вашего мира от захватчиков. Тут живут ваши доблестные защитники.',
  'dossier.building.default': 'Планетарное сооружение.',
  'dossier.building.fabricator':
    'Чистые цеха литографии печатают {m}▦ в час. Прожорлива к энергии и людям, зато её продукция ведёт эскадрильи и открывает осадные доктрины. Апгрейды окупаются собственной продукцией.',
  'dossier.building.farm':
    'Ярусы гидропонных оранжерей под спектральными лампами позволяют вашим подопечным питаться, ведь голод беспощаден. Выращивает {f}❖ в час. Ваши рабочие и воины едят каждый день, было бы глупо проиграть сражение из-за голодного обморока.',
  'dossier.building.fort':
    'Эшелонированный планетарный бастион. Поднимает оборону гарнизона на {d} и держит {hp} структурной прочности под орбитальным огнём. Последний рубеж осаждённого мира.',
  'dossier.building.metal-station':
    'Добывающая платформа, вгрызается в спёкшуюся кору мёртвого мира. Там, где аннигиляция выжгла всё живое, обнажилась чистая металлическая руда — станция качает {m}⬢ в час. Улучшение увеличивает добычу.',
  'dossier.building.mine':
    'Буровая платформа вгрызается в планету и добывает {m}⬢ в час. Улучшение позволяет копать глубже, чтобы добраться до самых богатых жил. Основа для строительства флота.',
  'dossier.building.orbital-aa':
    'Стационарная зенитная батарея защищает воздушное пространство вашего мира и наносит {dmg} урона в час по кораблям на орбите. Кошмар для бомбардировщиков, повисших над планетой, и для налетающих эскадрилий. Захват мира не блокирует — это дело наземной обороны; батарея лишь выкашивает флот над головой.',
  'dossier.building.power-plant':
    'Термоядерный реактор питает энергией ваши миры, он производит {e}↯ в час. Энергия — кровь ваших построек, ведь они работают не на волшебстве. При дефиците всё проседает до половины мощности.',
  'dossier.building.radar':
    'Комплекс радаров просвечивает пространство вокруг вашего мира и ловит вражеские сигнатуры задолго до того, как они посмеют на вас напасть. Улучшения обеспечивают большее покрытие.',
  'dossier.building.refinery':
    'Перерабатывающий комплекс, превращающий руду и логистику в ликвидные кредиты — {c}¤ в час. Топливо для имперской бюрократии, верфей и наёмных эскадр.',
  'dossier.building.starfort':
    'Автономная крепость, возведённая в астероидное поле: {d} к обороне и {hp} прочности. Превращает безликий перекрёсток в укреплённый узел с орбитой и ПКО',
  'dossier.building.tax-office':
    'Налоговая управа имперского образца: сама ничего не добывает, но ставит на учёт население мира и поднимает его кредитный сбор на {b}.',
  'dossier.divdesign.desc': 'Редактор шаблонов: состав слотов и доктрина дивизий.',
  'dossier.divdesign.name': 'Конструктор дивизий',
  'dossier.division.desc':
    'Наземное соединение, собранное по шаблону. Обороняет мир; грузится на флот из панели флота.',
  'dossier.division.name': 'Дивизия',
  'dossier.fleet.desc':
    'Мобильное оперативное соединение кораблей. Выберите его, чтобы отдавать приказы на манёвр, орбиту и удар по врагу.',
  'dossier.fleet.name': 'Флот',
  'dossier.hint': 'Наведи на объект слева — здесь появится его досье.',
  'dossier.stat.atk.desc': 'Суммарная атака кораблей флота.',
  'dossier.stat.atk.name': 'Атака',
  'dossier.stat.cap.desc':
    'В залпе бьют максимум {n} юнитов — сильнейшие первыми; все сверх капа только впитывают урон.',
  'dossier.stat.cap.name': 'Линия огня',
  'dossier.stat.datk.desc': 'Суммарная атака дивизии.',
  'dossier.stat.datk.name': 'Атака',
  'dossier.stat.ddef.desc': 'Суммарная защита дивизии.',
  'dossier.stat.ddef.name': 'Защита',
  'dossier.stat.def.desc': 'Суммарная защита кораблей флота.',
  'dossier.stat.def.name': 'Защита',
  'dossier.stat.dhp.desc': 'Суммарные очки здоровья дивизии.',
  'dossier.stat.dhp.name': 'ОЗ',
  'dossier.stat.garrison.desc': 'Численность наземных войск, обороняющих мир.',
  'dossier.stat.garrison.name': 'Гарнизон',
  'dossier.stat.ground.desc': 'Пехота и техника на поверхности мира.',
  'dossier.stat.ground.name': 'Наземные части',
  'dossier.stat.gships.desc': 'Корабли, стоящие в гарнизоне мира (не на орбите).',
  'dossier.stat.gships.name': 'Корабли в гарнизоне',
  'dossier.stat.hp.desc': 'Суммарная прочность кораблей флота.',
  'dossier.stat.hp.name': 'Очки здоровья',
  'dossier.stat.hull.desc':
    'Текущая/полная прочность армии. Чинится у своего мира с верфью — или мгновенно за кредиты.',
  'dossier.stat.hull.name': 'Корпус',
  'dossier.stat.pbuild.desc': 'Число построек на мире.',
  'dossier.stat.pbuild.name': 'Постройки',
  'dossier.stat.shield.desc':
    'Аблятивный щит: принимает урон первым и бесплатно восстанавливается вне боя.',
  'dossier.stat.shield.name': 'Щит',
  'dossier.stat.spd.desc':
    'Скорость перелёта — флот движется со скоростью самого медленного корабля.',
  'dossier.stat.spd.name': 'Скорость',
  'dossier.tab.buildings.desc':
    'Постройки мира и строительный конвейер: состояние, уровни и улучшения.',
  'dossier.tab.buildings.name': 'Здания',
  'dossier.tab.ground.desc':
    'Наземные части обороняют ваши миры. Их можно погрузить на флот для захвата вражеских миров.',
  'dossier.tab.ground.name': 'Земля',
  'dossier.tab.ships.desc':
    'Флот -ваше оружие и защита. Здесь вы можете заказывать корабли для пополнения флота.',
  'dossier.tab.ships.name': 'Флот',
  'dossier.tab.squadron.desc':
    'Носитель (◈) несёт эскадрильи (△). Запускайте авиагруппу из панели выбранного флота кнопкой «🛩 Запустить эскадрилью».',
  'dossier.tab.squadron.name': 'Крылья',
  'dossier.task.eta': 'Осталось: {r}',
  'dossier.task.output': '{r}: {now}/ч сейчас → {final}/ч по готовности',
  'dossier.task.queued': 'В очереди — ещё не начато.',
  'dossier.task.title': 'Стройка',
  'dossier.task.unit-ready': 'По готовности пополнит гарнизон/флот планеты.',
  'dossier.unit.cruiser.desc':
    'Рабочая лошадь линейного флота: {a} атаки, {hp} корпуса и трюм на {c}. Универсальный боевой корабль, одинаково уверенный в обороне и в наступлении.',
  'dossier.unit.cruiser.name': 'Крейсер',
  'dossier.unit.default': 'Боевая единица.',
  'dossier.unit.fighter-squadron.desc':
    'Палубная эскадрилья: стремительная (ход {sp}) и больно бьёт ({a} атаки), но брони почти нет ({hp} корпуса). Отделяется от носителя в отдельный быстрый флот и наносит удар с дистанции {r}. Контрится орбитальным ПВО — не гоните её на прикрытую ПВО планету.',
  'dossier.unit.fighter-squadron.name': 'Истребительная эскадрилья',
  'dossier.unit.hero.desc':
    'Боевая проекция самого командующего — флагман во главе родного флота: {a} атаки и {hp} корпуса. Но решает не это: его присутствие держит эскадру в кулаке, давая {b} к атаке и обороне всем кораблям рядом. Падёт — командующий лишается проекции, пока та не отстроится заново на родном мире.',
  'dossier.unit.hero.name': 'Флагман',
  'dossier.unit.scout.desc':
    'Лёгкий разведывательный корпус. Быстрый (ход {sp}) и почти неслышный (сигнатура {sig}) — чертит карту пустоты там, куда боится соваться линейный флот.',
  'dossier.unit.scout.name': 'Разведчик',
  'dossier.unit.siege.desc':
    'Тяжёлая осадная платформа: {a} урона с дистанции {r}, но тонкая броня ({d} защиты). Её место за спинами крейсеров, откуда она крушит укрепления и верфи.',
  'dossier.unit.siege.name': 'Осадная платформа',
  'dossier.unit.strike-carrier.desc':
    'Медленный бронированный носитель ({hp} корпуса, трюм на {c}) — своих пушек почти нет, вся его сила в эскадрильях, что он несёт. Держите его позади и запускайте авиагруппу по цели кнопкой «🛩 Запустить эскадрилью».',
  'dossier.unit.strike-carrier.name': 'Ударный носитель',

  // --- fmt — Форматирование величин: длительности.
  'fmt.hours': '{n}м',
  'fmt.hours': '{n}ч',
  'fmt.minutes': '{n}м',

  // --- hint — Подсказки режима прицеливания на карте.
  'hint.aim-cancelled': 'прицеливание отменено',
  'hint.assault-enemy-only': '⚔ штурмовать можно только чужой мир',
  'hint.auto-assault': '⚔ авто-штурм включён — флот сам штурмует вражеский мир по прибытии',
  'hint.barrage-auto': '🎯 автоприцел',
  'hint.barrage-set': '🎯 автоприцел',
  'hint.barrage-set': '🎯 сосредоточенный огонь назначен',
  'hint.cast-cancelled': '✖ каст отменён',
  'hint.deploy-cancelled': '✖ развёртывание отменено',
  'hint.forced-march': '⚡ форс-марш: +50% скорости, −5% прочности за час хода',
  'hint.multiselect': '⊕ тапайте свои флоты — соберите группу и отдайте общий приказ',
  'hint.no-target': '◎ цель не выбрана',
  'hint.pick-assault': '⚔ выберите чужой мир для штурма',
  'hint.pick-barrage': '🎯 тапните вражеский флот для сосредоточенного огня · пустота = авто',
  'hint.pick-merge': '⛬ выберите флот для объединения',
  'hint.pick-order': '◎ тапните цель на карте — соберём приказ',
  'hint.squadron-launched': '🛩 эскадрилья запущена — ведите её на цель',
  'hint.standing-sortie': '🛩 дежурный вылет включён — эскадрилья бьёт врага в радиусе',

  // --- map — Значки на карте: фазы боя.
  'map.badge.landing': '⚒ десант',
  'map.badge.orbit': '⚔ орбита',

  // --- meta — Прокачка командующего: уровень, очки, узлы.
  'meta.cost': '{n} очк.',
  'meta.level': 'Уровень {n}',
  'meta.locked': 'Закрыто',
  'meta.note':
    'Опыт даётся за завершённые матчи: участие + счёт + победа. Прокачка не продаётся — только игра.',
  'meta.points': 'Очков: {n}',

  // --- net — Сеть: подключение, разрывы, адрес сервера.
  'net.bad-address': 'Неверный адрес сервера',
  'net.connected': '● подключён как {who}',
  'net.connecting': 'Подключение: {nick}…',
  'net.disconnected': '● отключён от сервера',
  'net.join-closed': 'вход в этот матч закрыт (окно приёма новых игроков истекло)',
  'net.match-full': 'матч заполнен — все места заняты',
  'net.need-address': 'Укажи адрес сервера',
  'net.reconnecting': '● связь потеряна — переподключение…',
  'net.reconnecting-order': 'переподключение — приказ не отправлен, повторите позже',
  'net.waiting-host': 'Ждём, пока хост начнёт…',

  // --- queue — Очередь стройки: постановка, улучшение, отказы.
  'queue.added': 'в очередь: {what} на {at}',
  'queue.failed': '{what} — не вышло: {err}',
  'queue.unknown': 'неизвестный заказ',
  'queue.upgrade': '{b} — улучшение',

  // --- sandbox — Песочница (дев-инструмент): переключатели и команды.
  'sandbox.commands': 'Команды',
  'sandbox.end-wars': 'Закрыть',
  'sandbox.end-wars': 'Прекратить войну со всеми фракциями',
  'sandbox.no-player': 'нет игрока',
  'sandbox.no-wars': 'Вы ни с кем не воюете',
  'sandbox.title': 'Переключатели',
  'sandbox.title': 'ПЕСОЧНИЦА',
  'sandbox.toggles': 'Переключатели',
  'sandbox.wars-ended': 'Вы ни с кем не воюете',
  'sandbox.wars-ended': 'Войны прекращены: {n} — отношения нейтральные',

  // --- scipick — Совет учёных: кандидаты, фокус ветки, закрепление.
  'scipick.candidates': 'Кандидаты · нажмите, чтобы занять слот',
  'scipick.confirm': 'Закрепить и продолжить к выбору места →',
  'scipick.focus': 'Фокус ветки «{br}»',
  'scipick.generalist': '+1 слот исследования (генералист, без фокуса ветки)',
  'scipick.need-two': 'Выберите двух учёных',
  'scipick.note': 'Кандидаты · нажмите, чтобы занять слот',
  'scipick.note':
    '⚠ Совет закрепляется на весь матч. Рекомендованная пара уже выбрана — замените по вкусу.',
  'scipick.opens': 'Фокус ветки «{br}»',
  'scipick.opens': 'Открывает ветку «{br}»: {list}',
  'scipick.pick': 'Выбрать учёного',

  // --- soon — Заглушки «скоро» для ещё не готовых экранов.
  'soon.generic': '{what} — скоро',

  // --- split — Разделение флота: диалог и предпросмотр.
  'split.all': 'Все',
  'split.confirm': 'Отмена',
  'split.confirm': 'Подтвердить',
  'split.note':
    'Отделите корабли в новый флот — он останется в том же секторе. Хотя бы один корабль остаётся; десант в трюме остаётся с исходным флотом.',
  'split.preview': 'новый флот: {a} кораблей · у исходного останется {b}',
  'split.title':
    'Отделите корабли в новый флот — он останется в том же секторе. Хотя бы один корабль остаётся; десант в трюме остаётся с исходным флотом.',
  'split.title': 'РАЗДЕЛЕНИЕ ФЛОТА',

  // --- tgt — Композер приказов (TGT-1): шаги плана, отправка.
  'tgt.add-wait': 'Домой',
  'tgt.add-wait': 'Огонь',
  'tgt.add-wait': 'Штурм',
  'tgt.add-wait': 'Сюда',
  'tgt.add-wait': '⏱ +1ч',
  'tgt.at': '🎯{n}ч',
  'tgt.clear': 'снять приказ',
  'tgt.empty': 'план пуст — добавь шаги',
  'tgt.fleets': '{n} флотов',
  'tgt.placed': '◎ приказ поставлен — флот исполнит план сам',
  'tgt.send': 'снять приказ',
  'tgt.send': 'Отправить',
  'tgt.step.fire': 'Огонь',
  'tgt.step.here': 'Сюда',
  'tgt.step.home': 'Домой',
  'tgt.step.remove': 'убрать шаг',
  'tgt.title': '{n} флотов',
  'tgt.title': 'ПРИКАЗ',
  'tgt.wait': '⏱{n}ч',

  // --- threat — Оповещение об угрозе: подход врага, радарный контакт.
  'threat.contact': '◆ новый радарный контакт ({size}) у {at}',
  'threat.here': '⚠ Враг у {node}!',
  'threat.incoming': '⚠ Враг идёт к {node}: прибытие через {dur}',

  // --- yard — «Верфь»: корпус и модули, конструктор дивизий, стоимость и заказ.
  'yard.arsenal.note':
    '⚡ Арсенал живой: докупленное в матче видно здесь сразу, но начинает работать только когда ты это ПОСТРОИШЬ — постройка и логистика, не мгновенно.',
  'yard.build': 'Построить ×{n} →',
  'yard.cost.hull': 'Корпус ×{n}',
  'yard.cost.live': 'пересчёт вживую',
  'yard.cost.modules': 'Модули ×{n}',
  'yard.cost.total': 'Итого',
  'yard.cost.with-modules': 'Итог с модулями',
  'yard.div.attack': 'Атака',
  'yard.div.cost': 'Стоимость мобилизации',
  'yard.div.defense': 'Оборона',
  'yard.div.doctrine': 'Доктрина состава',
  'yard.div.doctrine.note': 'Смешай рода войск — состав задаёт доктрину.',
  'yard.div.empty': 'Нет шаблонов.',
  'yard.div.hull': 'Корпус',
  'yard.div.note':
    'Тап по слоту: пусто → пехота → танк. Мобилизация дивизии — в панели своего мира (вкладка «Дивизии»).',
  'yard.div.slot-empty': 'пусто',
  'yard.div.slots': '{n}/{s} юнитов · тапни слот, чтобы менять род войск',
  'yard.div.total': 'Итог по формации',
  'yard.free': 'бесплатно',
  'yard.hull.none': 'В арсенале нет корпусов этого класса.',
  'yard.hull.unavailable': 'Корпус недоступен.',
  'yard.loadout.note':
    'Лоадаут фиксируется при постройке. Готовый корабль не переоснастить — только построить новый с другим набором.',
  'yard.module.remove': 'снять модуль',
  'yard.modules.all-taken': 'Доступные модули — все слоты заняты',
  'yard.modules.for-slot': 'Доступные модули — для слота «{s}»',
  'yard.no-worlds': 'нет своих миров',
  'yard.ordered': '⚒ заказано: {n}× {hull}',
  'yard.pick.ally-world': ' / мир союзника',
  'yard.pick.hero-world': '⚓ выберите свой мир{fl}{al} — там поднимется корабль героя',
  'yard.pick.own-fleet': ' / свой флот',
  'yard.pick.target': '✨ выберите мир-цель на карте',
  'yard.slot.empty': 'пусто — выбери модуль',
  'yard.slot.named': 'слот «{s}»',
  'yard.slots.count': '{n} слота под модули (по размеру корпуса)',
  'yard.slots.note':
    'Типизированные слоты: модуль встаёт только в свой тип. <b>Серые</b> — не для свободного слота или уже стоят.',
  'yard.soon': '«{what}» переезжает в конструктор следующим кирпичом.',
  'yard.title': 'КОНСТРУКТОР',

  // --- end — Экран конца матча: исход, опыт, итоговая таблица, реванш.
  'end.board': 'Смотреть доску',
  'end.draw': '⚖️ НИЧЬЯ',
  'end.duration': 'Длительность',
  'end.fleets': 'Флоты',
  'end.level-up': '★ Новый уровень {lvl} — очко прокачки ждёт в меню «Прокачка»',
  'end.loss': '💀 ПОРАЖЕНИЕ',
  'end.new-match': '⟳ Новый матч',
  'end.place': '{p}-е место из {n}',
  'end.play-again': '⟳ Играть ещё',
  'end.provinces': 'Провинции',
  'end.score': 'Итоговый счёт',
  'end.to-menu': 'В меню',
  'end.units': 'Юниты',
  'end.win': '🏆 ПОБЕДА',
  'end.win.coalition': '🏆 ПОБЕДА КОАЛИЦИИ',
  'end.xp': '★ Опыт командующего: +{n}',

  // --- err — Отказы ядра (kernel rejection codes). Ключ выводится из кода: E_NO_CAPACITY → err.no-capacity.
  'err.already': 'уже действует',
  'err.already-fitted': 'фиттинг уже установлен',
  'err.already-offered': 'предложение уже отправлено',
  'err.already-unlocked': 'узел уже изучен',
  'err.bad-effect': 'способность настроена некорректно',
  'err.bad-payload': 'некорректный приказ',
  'err.bad-spawn': 'здесь нельзя развернуть героя',
  'err.bad-target': 'недопустимая цель',
  'err.bombarded': 'стройка под бомбардировкой',
  'err.bot-alliance': 'боты не вступают в коалиции',
  'err.chat-rate': 'подождите пару секунд',
  'err.chat-target': 'адресат не найден',
  'err.chat-text': 'пустое сообщение',
  'err.conditions-unmet': 'условия не выполнены',
  'err.consent-required': 'требуется согласие второй стороны',
  'err.cooldown': 'способность перезаряжается',
  'err.fleet-busy': 'флот занят',
  'err.forbidden': 'действие запрещено',
  'err.hero-alive': 'герой уже командует кораблём',
  'err.hero-cap': 'достигнут предел развёрнутых героев',
  'err.hero-dead': 'герой погиб — дождитесь возрождения',
  'err.hero-not-deployed': 'герой не развёрнут — сначала поднимите корабль',
  'err.insufficient': 'не хватает ресурсов',
  'err.internal': 'внутренняя ошибка',
  'err.limit': 'достигнут предел',
  'err.no-ability': 'неизвестная способность',
  'err.no-artillery': 'нет артиллерии',
  'err.no-capacity': 'трюм полон',
  'err.no-capital': 'нет столицы для отзыва',
  'err.no-effect': 'эффект ещё не реализован',
  'err.no-fitting': 'неизвестный фиттинг',
  'err.no-fleet': 'флот не найден',
  'err.no-funds': 'не хватает средств',
  'err.no-hero': 'герой не найден',
  'err.no-node': 'неизвестный узел дерева',
  'err.no-planet': 'мир не найден',
  'err.no-player': 'игрок не найден',
  'err.no-ships': 'нет кораблей',
  'err.no-shipyard': 'нужна верфь/космопорт',
  'err.no-slots': 'слоты фиттингов заняты',
  'err.no-target': 'нет цели',
  'err.no-troops': 'мир защищён — для штурма нужен десант на борту',
  'err.not-destructible': 'этот мир нельзя уничтожить',
  'err.not-equipped': 'у героя нет этой способности',
  'err.out-of-range': 'вне радиуса действия',
  'err.own-planet': 'это ваш собственный мир',
  'err.requires': 'сначала изучите предыдущий узел',
  'err.research-slots-full': 'все исследовательские слоты заняты',
  'err.respawn-cooldown': 'герой ещё восстанавливается',
  'err.same-location': 'флот уже здесь',
  'err.too-early': 'слишком рано',
  'err.unknown-building': 'неизвестное здание',
  'err.unknown-technology': 'неизвестная технология',
  'err.unknown-unit': 'неизвестный юнит',
  'err.wrong-branch': 'узел чужой ветви',
  'err.wrong-orbit': 'недопустимая орбита',
  'err.wrong-sector': 'недопустимый тип сектора',

  // --- hero — Герои: грейды, способности (имя + описание).
  'hero.ability.annihilate.desc': 'Уничтожает планету в радиусе — она становится мёртвым миром.',
  'hero.ability.annihilate.name': 'Аннигиляция',
  'hero.ability.bulwark.desc': 'Временный щит: +оборона своим флотам рядом с героем.',
  'hero.ability.bulwark.name': 'Бастион',
  'hero.ability.corridor.desc':
    'Открывает временный коридор-лейн до близкого мира; свои флоты идут по нему быстрее.',
  'hero.ability.corridor.name': 'Коридор',
  'hero.ability.rally.desc':
    'Боевой клич: временный доп. бонус к ауре для своих флотов рядом с героем.',
  'hero.ability.rally.name': 'Сбор',
  'hero.ability.recall.desc': 'Мгновенно отзывает корабль-героя в столицу.',
  'hero.ability.recall.name': 'Отзыв',
  'hero.ability.scan.desc': 'Раскрывает зону вокруг цели сквозь туман на время.',
  'hero.ability.scan.name': 'Разведка',
  'hero.grade.common': 'Обычный',
  'hero.grade.legendary': 'Легендарный',
  'hero.grade.main': 'Главный',
  'hero.grade.rare': 'Редкий',

  // --- hero.hq / hero.tree / hero.abil / hero.fit — Штаб героев: состав, дерево навыков, способности, фиттинги.
  'hero.abil.activate': 'Активировать',
  'hero.abil.cooldown': 'КД {h}',
  'hero.abil.deploy-perk': 'перк развёртывания',
  'hero.abil.empty': 'Нет способностей.',
  'hero.abil.pick-target': 'Цель…',
  'hero.abil.soon': 'скоро',
  'hero.fit.hull': 'корпус',
  'hero.fit.hull-mod': 'Модификатор корпуса',
  'hero.fit.install': 'Необратимо — установить',
  'hero.fit.installed': 'установлен',
  'hero.fit.no-slots': 'нет слотов',
  'hero.fit.none': 'У этого героя нет слотов фиттингов.',
  'hero.fit.permanent': 'Ставится навсегда — рефита нет',
  'hero.fit.slots': 'Слоты · {u}/{n}',
  'hero.hq.dead': 'погиб',
  'hero.hq.deploy': 'Развернуть',
  'hero.hq.deployed': '⚓ развёрнут',
  'hero.hq.deployed-count': 'развёрнуто {a}/{c}',
  'hero.hq.empty': 'У вас пока нет героев.',
  'hero.hq.enroute': 'в пути',
  'hero.hq.fittings': 'Фиттинги',
  'hero.hq.reserve': 'резерв',
  'hero.hq.tab.abilities': 'Способности',
  'hero.hq.tab.fittings': 'Фиттинги',
  'hero.hq.tab.overview': 'Обзор',
  'hero.hq.tab.tree': 'Дерево',
  'hero.stat.abilities': 'способностей',
  'hero.stat.active': 'актив',
  'hero.stat.bonuses': 'Текущие бонусы',
  'hero.stat.fittings': 'фиттингов',
  'hero.stat.tree-nodes': 'узлов дерева',
  'hero.tree.ability': 'способность',
  'hero.tree.cooldown': 'КД {h}ч',
  'hero.tree.cost': 'Цена',
  'hero.tree.empty': 'Дерево пусто.',
  'hero.tree.grants-ability': 'Открывает способность',
  'hero.tree.grants-passive': 'Даёт пассивку',
  'hero.tree.needs': 'нужен: {n}',
  'hero.tree.not-your-branch': 'не ваша ветвь',
  'hero.tree.other-branch': 'чужая ветвь',
  'hero.tree.passive': 'пассивка',
  'hero.tree.range': 'дальность {r}',
  'hero.tree.requires': 'Требует',
  'hero.tree.unlock': 'Изучить',
  'hero.tree.unlocked': 'изучено',

  // --- hub — Хаб (экран между матчами): шапка, карточки, плитки «Ещё», нижняя навигация.
  'hub.ally.corp': 'Кабинет корпорации',
  'hub.ally.empty.sub': 'корпорации · общие AvA-битвы · влияние',
  'hub.ally.empty.title': 'Альянсы',
  'hub.avatar.title': 'Сменить эмблему',
  'hub.back-to-bots': '⟳ К выбору ботов',
  'hub.digest.empty.sub':
    'Войди в матч на вкладке «Игры» — здесь появятся ходы, требующие внимания.',
  'hub.digest.empty.title': 'Нет матчей, ждущих приказа',
  'hub.digest.section': 'Сводка',
  'hub.emblem.close': 'Закрыть',
  'hub.emblem.title': 'ВЫБОР ЭМБЛЕМЫ',
  'hub.messages.soon': 'Сообщения — скоро',
  'hub.msgs.aria': 'Сообщения',
  'hub.nav.ally': 'Альянсы',
  'hub.nav.arsenal': 'Арсенал',
  'hub.nav.games': 'Игры',
  'hub.nav.home': 'Домой',
  'hub.nav.meta': 'Прокачка',
  'hub.nav.more': 'Ещё',
  'hub.nav.rank': 'Рейтинг',
  'hub.onboard.skip': 'Пропустить',
  'hub.onboard.start': 'Начать обучение',
  'hub.onboard.sub': 'Короткое обучение покажет интерфейс и первый ход — пара минут.',
  'hub.onboard.title': 'Впервые в Void Dominion?',
  'hub.play': 'ИГРАТЬ СЕЙЧАС',
  'hub.rank.empty.sub': 'сезонный рейтинг по местам в матчах',
  'hub.rank.empty.title': 'Рейтинги — скоро',
  'hub.sandbox.title': 'Песочница',
  'hub.season.sub': 'Рейтинги и альянсы откроются со стартом мета-слоя.',
  'hub.season.title': 'Сезон ещё не начат',
  'hub.solo': 'Одиночная игра',
  'hub.sovereigns': 'Суверены — донат-валюта',
  'hub.status.online': 'в сети',
  'hub.tile.account': 'Аккаунт',
  'hub.tile.chat': 'Чат',
  'hub.tile.community': 'Сообщество',
  'hub.tile.help': 'Справочник',
  'hub.tile.logout': 'Сменить командира',
  'hub.tile.notifications': 'Уведомления',
  'hub.tile.settings': 'Настройки',
  'hub.tile.support': 'Поддержка',
  'hub.tile.tutorial': 'Обучение',
  'hub.tile.updates': 'Обновления',

  // --- hud — Постоянный интерфейс матча: верхняя панель ресурсов.
  'hud.crest.title': 'Ваш профиль',
  'hud.deficit': '⚠ ДЕФИЦИТ — здания-потребители работают на 50%',
  'hud.goal': 'Задача: ✦ {n} (мир — 50, сектор — 10) или уничтожение соперников.',
  'hud.resource.credits': 'Кредиты',
  'hud.resource.energy': 'Энергия',
  'hud.resource.food': 'Пища',
  'hud.resource.metal': 'Металл',
  'hud.resource.microelectronics': 'Микроэлектроника',
  'hud.resource.tip':
    '{ic} {name}: {stock} в казне · {flow}/ч (производство минус содержание войск и зданий)',
  'hud.score.tip':
    '✦ {score}/{limit}: мир — 50, прочий сектор — 10, здания добавляют по уровню (у вас {w} миров, {s} секторов). Победа: ✦ {limit}, уничтожение соперников или доминирование.',

  // --- log — Журнал событий матча (сводки) и гейт объявления войны.
  'log.assault.no-troops':
    '⚔ штурм невозможен: на борту нет десанта, а мир защищён — погрузите войска',
  'log.assault.warn-no-troops':
    '⚔ внимание: на борту нет десанта — защищённый мир штурмом не взять',
  'log.battle.draw': 'ничья',
  'log.battle.end': '⚔ бой у {at} завершён — {res}',
  'log.battle.losses': ' · потери: {tally}',
  'log.battle.phase.ground': 'десант',
  'log.battle.phase.orbit': 'орбита',
  'log.battle.start': '⚔️ бой у {at} ({phase})',
  'log.battle.win': 'победа: {who}',
  'log.build.destroyed': '💥 {b}: разрушено на {at}',
  'log.build.done': '🏗️ {b}: построено на {at}',
  'log.build.upgraded': '⬆️ {b} → L{lvl} на {at}',
  'log.capture': '🚩 {who} захватил {at}',
  'log.diplo.offer': '🕊 {who} предлагает: {stance} — ответьте тем же в Дипломатии',
  'log.diplo.offer.short': 'Предложение: {stance}',
  'log.diplo.rejected': '{who} отклонил предложение: {stance}',
  'log.diplo.rejected.short': '✖ {who} отклонил: {stance}',
  'log.diplo.sent': '⏳ {who}: предложение отправлено — {stance}',
  'log.diplo.stance': '{a} и {b}: {stance}',
  'log.diplo.war': '{a} объявил войну {b}',
  'log.fleet.destroyed': '☠️ флот {who} уничтожен',
  'log.fleet.launched': '🚀 {who} поднял флот с {at}',
  'log.fleet.merged': '⛬ флоты объединены у {at}',
  'log.fleet.split': '⊟ флот разделён у {at}',
  'log.market.buy': 'покупка',
  'log.market.sell': 'продажа',
  'log.market.trade': '⇄ биржа: {n} {res} за {paid} ¤ ({side})',
  'log.spy.caught': '🛡 Контрразведка: агент {who} пойман при попытке кражи ({what})!',
  'log.spy.fail': '🕵 Агент провалился ({who}) — плата сгорела',
  'log.spy.fail.short': '✖ Провал против {who} — плата сгорела',
  'log.spy.kind.fleets': 'данные о флотах',
  'log.spy.kind.treasury': 'казна',
  'log.spy.kind.world': 'данные мира',
  'log.spy.leak': '🛡 Контрразведка: утечка разведданных ({what}) — вор не установлен',
  'log.spy.success': '🕵 Агент добыл разведданные: {what} — окно 24ч',
  'log.spy.success.short': '🗝 Успех: {what}',
  'log.spy.what.fleets': 'флоты {who}',
  'log.spy.what.treasury': 'казна {who}',
  'log.spy.what.world': 'мир {at}',
  'log.steward.decisions': 'Решений за вахту: {n} — журнал в окне Хранителя.',
  'log.steward.handback.active': '🌅 Хранитель вернул вам управление (была «Активная оборона»).',
  'log.steward.handback.defense': '🌅 Хранитель вернул вам управление (была «Оборона»).',
  'log.steward.off': '🎮 Вы вернули командование себе.',
  'log.steward.on.active':
    '😴 Хранитель принял командование (Активная оборона) — держит рубежи и контратакует у своих миров.',
  'log.steward.on.defense':
    '😴 Хранитель принял командование (Оборона) — держит рубежи, пока вы спите.',
  'log.tech.done': '⚛ изучено: {tech}',
  'log.war.declared': '⚔ Война объявлена — флоты выдвигаются',
  'war.confirm.cancel': 'ОТМЕНА',
  'war.confirm.friendly': 'Это мир дружественной фракции. Вы хотите объявить войну <b>{names}</b>?',
  'war.confirm.go': 'ОБЪЯВИТЬ ВОЙНУ',
  'war.confirm.no': 'НЕТ',
  'war.confirm.title': 'ОБЪЯВИТЬ ВОЙНУ?',
  'war.confirm.transit':
    'Маршрут проходит через миры <b>{names}</b>, с кем у вас <b>мир</b>. Мирного прохода нет — движение сюда объявит <b>войну</b>.',
  'war.confirm.yes': 'ДА',

  // --- market — Сессионная биржа: вкладки ресурсов, книга заявок, лот, комиссия.
  'market.buy': 'Купить',
  'market.cancel': 'Отменить',
  'market.escrow-note': 'в эскроу уйдёт {n} ¤ · комиссию {p}% платит получатель кредитов',
  'market.in-treasury': 'В казне',
  'market.net-after-fee': 'к получению после комиссии {p}%: {n} ¤',
  'market.no-asks': 'Нет лотов на продажу',
  'market.no-bids': 'Нет лотов на покупку',
  'market.own-lot': 'ваш лот',
  'market.place': 'Выставить',
  'market.price': 'цена',
  'market.qty': 'кол-во',
  'market.res.energy': 'Энергия',
  'market.res.food': 'Пища',
  'market.res.metal': 'Металл',
  'market.res.microelectronics': 'Микро',
  'market.sell': 'Продать',
  'market.side.buy': 'Покупка',
  'market.side.sell': 'Продажа',
  'market.title': 'РЫНОК',

  // --- onb — Онбординг: туры-подсказки, карточки первого контакта, цели первой сессии, сводка возвращения.
  'onb.goal.capture': 'Захвати мир',
  'onb.goal.fleet': 'Построй корабль',
  'onb.goal.mine': 'Построй шахту',
  'onb.goal.score': 'Набери 100 очков',
  'onb.goals.all-done':
    '🏅 Все цели первой сессии выполнены! +{n} XP — ты готов к настоящему матчу.',
  'onb.goals.title': 'Цели первой сессии',
  'onb.intro.artillery.body':
    'Флоты с артиллерией бьют по врагу издалека, ещё до сближения — сосредоточь огонь на одной цели или дай флоту выбирать её самому. Толстая броня артиллерии слабая, её место позади линии, а не на передовой.',
  'onb.intro.artillery.title': 'Обстрел — огонь с дистанции',
  'onb.intro.async-delay.body':
    'Этот флот прибудет через часы реального времени — мир Void Dominion идёт непрерывно, даже когда ты офлайн. Можешь закрыть игру: приказы выполнятся сами, а к возвращению мы пришлём уведомление и покажем сводку «пока тебя не было».',
  'onb.intro.async-delay.title': 'Мир идёт без тебя',
  'onb.intro.ava.body':
    'Здесь корпорации бросают друг другу вызов на организованную войну. Отметь готовность корпорации и свою личную — когда обе стороны готовы, можно принять вызов. Дальше — набор состава и сама война по расписанию.',
  'onb.intro.ava.title': 'Войны альянсов (AvA)',
  'onb.intro.badge': 'впервые',
  'onb.intro.constructor.body':
    'Здесь ты собираешь корабли, эскадрильи, дивизии и героев из модулей. Лоадаут фиксируется при постройке — выбирай слоты заранее, переоснастить готовое нельзя. Вкладка «Герои» — штаб командиров.',
  'onb.intro.constructor.title': 'Верфь — оснащение',
  'onb.intro.corp.body':
    'Корпорация — это твой отряд в общей сессии: общий склад, роли участников и совместные войны альянсов (AvA). Вступи в существующую или создай свою — вкладка «Войны» открывает доступ к вызовам между корпорациями.',
  'onb.intro.corp.title': 'Кабинет корпорации',
  'onb.intro.diplomacy.body':
    'Объявляй войну и мир, заключай пакты и союзы. Коалиция ограничена порогом силы — всех против одного не собрать. Следи за стойками сторон: союзник сегодня может стать соперником завтра.',
  'onb.intro.diplomacy.title': 'Дипломатия',
  'onb.intro.hero.body':
    'У каждого героя своё дерево навыков — тапни узел, чтобы увидеть, что он открывает, и изучи по требованиям и стоимости. Открытые узлы дают способности (активные, с дальностью и перезарядкой) или пассивки. Погибший герой возрождается на столице.',
  'onb.intro.hero.title': 'Герои — командиры флота',
  'onb.intro.market.body':
    'Торгуй ресурсами с другими игроками сессии: выставляй свои лоты и забирай чужие. Рынок сглаживает нехватку — обменяй излишек одного ресурса на тот, которого не хватает.',
  'onb.intro.market.title': 'Сессионный рынок',
  'onb.intro.ok': 'Понятно',
  'onb.intro.retreat.body':
    'Отход стоит −40% ТЕКУЩЕГО корпуса и щита (израненный флот теряет 40% остатка — отход не добивает) и даёт рывок скорости для бегства. Десант в высадке отступить не может; с орбиты вне боя корабль уходит свободно.',
  'onb.intro.retreat.title': 'Отступление — не бесплатно',
  'onb.intro.steward.body':
    'Уходишь надолго? Передай оборону Хранителю — он будет держать твои миры по заданным правилам, пока тебя нет. Мир идёт 24/7, но базовая защита останется, даже когда ты офлайн.',
  'onb.intro.steward.title': 'Хранитель — ИИ на сон',
  'onb.intro.tech.body':
    'Здесь ты открываешь технологии — постоянные улучшения флота, экономики и обороны. Узел стоит ресурсов и времени; изучил — бонус действует до конца матча. Планируй ветку под свой стиль игры.',
  'onb.intro.tech.title': 'Дерево технологий',
  'onb.recap.attention': 'Требуют внимания · {n}',
  'onb.recap.close': 'ЗАКРЫТЬ',
  'onb.recap.rest': 'Пока тебя не было',
  'onb.recap.title': 'СВОДКА ВОЗВРАЩЕНИЯ',
  'onb.tour.done': '✔ Обучение пройдено · +{n} XP — теперь сыграй настоящий матч!',
  'onb.tour.first.capture':
    'Захвати нейтральный мир: выйди на орбиту, а если он защищён — высади десант. Захват двухфазный: сначала небо, потом земля.',
  'onb.tour.first.course':
    'Выбери свой флот (▲) и тапни соседний мир — задай курс. Флот пойдёт по звёздным трассам, и туман начнёт открываться.',
  'onb.tour.first.done':
    'Первая схватка выиграна! Ты прошёл весь цикл: добыча → стройка → движение → захват → счёт. Дальше — настоящий матч.',
  'onb.tour.first.fleet':
    'Теперь построй боевой корабль — вкладка «Корабли» той же панели. Готовый корабль сам прилетит на орбиту и соберётся во флот — жди, пока рядом с твоим миром не появится «▲».',
  'onb.tour.first.home':
    'Внизу — панель твоего домашнего мира: здания, гарнизон и стройка. Тапни свой мир, если панель пуста.',
  'onb.tour.first.mine':
    'Начни с экономики: построй Шахту — она даёт ресурсы, на них строится всё остальное.',
  'onb.tour.first.score':
    'Мир взят — и счёт пошёл! Очки капают за миры и сектора; набери порог — и это победа.',
  'onb.tour.first.welcome':
    'Это твой первый мир, командир. Проведу тебя по главному циклу — пара минут, спокойно, без соперников.',
  'onb.tour.got-it': 'Понятно',
  'onb.tour.hud.clock':
    'Мир идёт в реальном времени и продолжается, даже когда ты офлайн. Здесь — пауза и ускорение.',
  'onb.tour.hud.done':
    'Готово! Пора действовать: построй шахту, подними флот, отдай курс. Удачи, командир.',
  'onb.tour.hud.purse':
    'Твоя казна: доход от шахт минус содержание флота. Следи, чтобы не уйти в минус.',
  'onb.tour.hud.tools': 'Инструменты командира: дипломатия, наука, верфь, рынок и сводки событий.',
  'onb.tour.hud.welcome':
    'Короткий тур по интерфейсу — на нём держится весь мир. «Пропустить обучение» доступно всегда.',
  'onb.tour.next': 'Далее',
  'onb.tour.skip': 'Пропустить обучение',
  'onb.tour.step': 'шаг {k} из {n}',

  // --- ping — Композер меток провинции: адресат, описание, отправка.
  'ping.cancel': 'Отмена',
  'ping.desc.ph': 'Описание метки (необязательно)…',
  'ping.mark': 'метка {loc}',
  'ping.no-desc': 'без описания',
  'ping.note': 'Отметьте провинцию и отправьте — метка станет кликабельной (↪ камера).',
  'ping.remove': 'убрать',
  'ping.sent.coalition': '📍 Пинг → Коалиция',
  'ping.sent.player': '📍 Пинг → {who}',
  'ping.title': 'Пинг',
  'ping.to.coalition': 'В чат коалиции',
  'ping.to.player': 'В ЛС игроку',

  // --- rail — Рельса инструментов в матче: подпись кнопки (.label) + подсказка (.title).
  'rail.chat.label': 'Чат',
  'rail.chat.title': 'Чат',
  'rail.constructor.label': 'Верфь',
  'rail.constructor.title': 'Конструктор — оснащение кораблей, эскадрилий, армии и героев',
  'rail.corp.label': 'Корп',
  'rail.corp.title': 'Корпорация',
  'rail.diplo.label': 'Дипло',
  'rail.diplo.title': 'Дипломатия',
  'rail.exit.label': 'Выйти',
  'rail.exit.title': 'Покинуть сессию',
  'rail.help.label': 'Справка',
  'rail.help.title': 'Справочник',
  'rail.log.label': 'Сводки',
  'rail.log.title': 'Сводки',
  'rail.market.label': 'Рынок',
  'rail.market.title': 'Рынок',
  'rail.msgs.label': 'Почта',
  'rail.msgs.title': 'Сообщения',
  'rail.settings.label': 'Настройки',
  'rail.settings.title': 'Настройки',
  'rail.steward.label': 'Сон',
  'rail.steward.title': 'Хранитель — передать ИИ на сон',
  'rail.tech.label': 'Наука',
  'rail.tech.title': 'Технологии',
  'rail.toggle.title': 'Инструменты',

  // --- seatpick — Выбор фракции и места перед входом в сетевой матч.
  'seatpick.cancel': 'Назад',
  'seatpick.go': 'ВЫБРАТЬ',
  'seatpick.sub': 'Выберите фракцию и стартовую позицию. Занятые места отмечены серым.',
  'seatpick.title': 'Выбор фракции',

  // --- setup — Экран «Настройка схватки»: домашний мир, боты, скорость времени.
  'setup.bonus.damage': '+{n}% урон',
  'setup.bonus.economy': '+{n}% экономика',
  'setup.bonus.radar': '+{n}% радар',
  'setup.bonus.speed': '+{n}% радар',
  'setup.bonus.speed': '+{n}% скорость флотов',
  'setup.cancel': 'Назад',
  'setup.faction.note': 'Фракция — пассивный бонус дома',
  'setup.go': 'ЗАПУСК',
  'setup.map-hint': 'Тапните светящийся мир, чтобы выбрать старт',
  'setup.off': 'ВЫКЛ',
  'setup.sandbox': '🧪 Песочница',
  'setup.speed.hint':
    '×1 — реальное время (час пути = час жизни, мир живёт и офлайн). Для быстрой партии выбери ×10–×100.',
  'setup.speed.label': 'Скорость времени',
  'setup.start': 'ЗАПУСК',
  'setup.start.solo': 'ЗАПУСК В ОДИНОЧКУ',
  'setup.sub':
    'Выберите свой домашний мир на карте, задайте число соперников-ботов и запускайте. Пустые места займут боты — выключите место, чтобы командовать меньшим сектором, или выключите все ради мирной одиночной песочницы для знакомства с интерфейсом.',
  'setup.teams.note': 'одна сторона — союзники',
  'setup.teams.off': 'Командный бой: выкл',
  'setup.teams.on': 'одна сторона — союзники',
  'setup.teams.on': 'Командный бой: ВКЛ',
  'setup.title': 'НАСТРОЙКА СХВАТКИ',

  // --- settings — Экран настроек: интерфейс, цвета сторон, графика.
  'settings.colors.neutral': 'Нейтральные',
  'settings.colors.neutral.hint': 'ничейные миры и неопознанные силы',
  'settings.colors.own': 'Свой цвет',
  'settings.colors.own.hint': 'вы на карте и в панелях — форма несёт тип, цвет несёт сторону',
  'settings.colors.palette': 'Палитра соперников',
  'settings.colors.palette.hint': '«дальтоник» — оттенки, различимые при цветослепоте',
  'settings.colors.reset': 'Вернуть цвета по умолчанию',
  'settings.colors.title': 'Цвета сторон',
  'settings.compact': 'Компактный режим меню',
  'settings.compact.hint': 'плотная панель сектора — меньше отступов, мельче шрифт (на ПК)',
  'settings.done': 'ГОТОВО',
  'settings.gfx.fps': 'Счётчик FPS',
  'settings.gfx.fps.hint': 'показывать кадры в секунду в углу — для проверки производительности',
  'settings.gfx.glow': 'Свечение и ореолы',
  'settings.gfx.glow.hint':
    'мягкое сияние вокруг миров, флотов и границ — выключите ради чёткой карты и скорости',
  'settings.gfx.starfield': 'Звёздный фон',
  'settings.gfx.starfield.hint':
    'дрейфующие туманности и звёзды на фоне — выключите для плоского фона',
  'settings.gfx.title': 'Графика',
  'settings.off': 'выкл',
  'settings.on': 'вкл',
  'settings.own-pins': 'Свои метки на карте',
  'settings.own-pins.hint': 'булавки 📍 ваших пингов — метки союзников видны всегда',
  'settings.palette.classic': 'классика',
  'settings.palette.colorblind': 'дальтоник',
  'settings.palette.warm': 'тёплая',
  'settings.sweep': 'Радарная развёртка',
  'settings.sweep.hint': 'вращающийся луч на карте — только вид, не влияет на обнаружение',
  'settings.sweep.opacity': 'Прозрачность радарной развёртки',
  'settings.tag': 'интерфейс',
  'settings.title': 'НАСТРОЙКИ',

  // --- ship — Корабли: корпуса и модули (имя + описание).
  'ship.hull.cruiser': 'Крейсер',
  'ship.hull.dropship': 'Носитель',
  'ship.hull.scout_drone': 'Скаут-дрон',
  'ship.hull.siege_lance': 'Осадная ланса',
  'ship.module.battery.desc': '+30% к атаке.',
  'ship.module.battery.name': 'Батарея',
  'ship.module.plating.desc': '+25% HP корпуса.',
  'ship.module.plating.name': 'Броня',
  'ship.module.shield.desc': '+30% к обороне.',
  'ship.module.shield.name': 'Щит',
  'ship.module.targeting.desc': '+15% к атаке и обороне.',
  'ship.module.targeting.name': 'Наведение',
  'ship.module.thruster.desc': '+20% к скорости.',
  'ship.module.thruster.name': 'Двигатель',

  // --- side — Боковая панель матча: конвейеры, карточка флота, бой, досье мира, вкладки гарнизона.
  'side.arch.artillery': 'артиллерия',
  'side.arch.combat': 'боевые',
  'side.arch.flagship': 'флагман',
  'side.arch.scout': 'скауты',
  'side.arch.swarm': 'рой',
  'side.arch.transport': 'транспорты',
  'side.battle.attacker': 'атака',
  'side.battle.defender': 'оборона',
  'side.battle.next-round': 'следующий раунд через',
  'side.battle.phase.ground': 'высадка',
  'side.battle.phase.orbit': 'орбита',
  'side.battle.retreat': '⤺ Отступить',
  'side.battle.retreat.hint':
    'Отход стоит −40% ТЕКУЩЕГО корпуса и щита (израненный флот теряет 40% остатка — отход не добивает) и даёт рывок скорости для бегства. Десант в высадке отступить не может; с орбиты вне боя корабль уходит свободно.',
  'side.battle.side.fleet': 'флот',
  'side.battle.side.garrison': 'гарнизон',
  'side.battle.side.landing': 'десант',
  'side.battle.title': '⚔ Бой — {phase} · раунд {r}',
  'side.build.conveyor': 'Строительный конвейер',
  'side.build.enemy-hidden': 'Строительная телеметрия врага недоступна',
  'side.build.hp': 'оз',
  'side.build.upgrade': '▲ Улучшить {c}',
  'side.conveyor.cancel.title': 'Отменить — вернёт часть ресурсов и поставит на паузу',
  'side.conveyor.dequeue.title': 'Убрать из очереди',
  'side.conveyor.idle': 'Ожидание заказов',
  'side.conveyor.idle.sub': 'готов к следующему заказу',
  'side.conveyor.idle.tag': 'ПРОСТОЙ',
  'side.conveyor.now': 'СЕЙЧАС',
  'side.conveyor.paused': 'Приостановлено {n}%',
  'side.conveyor.queue-empty': 'очередь пуста',
  'side.conveyor.resume.title': 'Возобновить — доплатить остаток',
  'side.conveyor.waiting': 'Ждёт ресурсы: {c}',
  'side.empty': 'Тапните мир.',
  'side.fleet.bombarding': 'бомбардирует',
  'side.fleet.enroute': '↗ идёт к {dest} · прибытие через',
  'side.fleet.hero-aura': '— проекция · +5% атаки/обороны этому флоту',
  'side.fleet.hull-tag': 'корпус {p}%',
  'side.fleet.hunger': 'голод: −25% на земле',
  'side.fleet.in-orbit': 'на орбите',
  'side.fleet.on-lane': '⟜ стоит на трассе {lane} · {p}% пути',
  'side.fleet.repair.dock.title': 'Экспресс-ремонт у своего дока за металл',
  'side.fleet.repair.instant.title': 'Мгновенный ремонт всего корпуса за кредиты',
  'side.fleet.ships': 'Корабли — тап для характеристик',
  'side.fleet.sub': '{s} кораблей · {tr} десанта',
  'side.fleet.sub.pc': 'Корабли: {s} · Десант: {tr}',
  'side.fleet.tile.hint': 'тап — полное досье',
  'side.fleet.troops': 'Десант на борту',
  'side.garrison.plus-troops': '+{n} десанта',
  'side.garrison.select': 'Выбрать →',
  'side.garrison.ships': 'Корабли в гарнизоне',
  'side.garrison.wing': 'Авиагруппа в гарнизоне',
  'side.ground.conveyor': 'Наземный конвейер',
  'side.ground.empty': 'наземной армии здесь нет',
  'side.ground.hint':
    'Наземные части обороняют ваши миры. Их можно погрузить на флот для захвата вражеских миров.',
  'side.ground.load': '▲ Погрузить {u}',
  'side.ground.loading': '⏳ погрузка: {n} (≈1ч на единицу)',
  'side.ground.title': 'Наземная армия ⇄ гарнизон',
  'side.ground.units': 'Наземные части',
  'side.ground.unload': '▼ Выгрузить {u}',
  'side.group.clear': 'Снять выделение группы',
  'side.group.hint':
    'Нажмите «Курс» и тапните цель — все выбранные флоты пойдут туда (проложат маршрут и встанут). «Слить» сплавляет группу в один флот (дальние сначала подлетят). Shift- или Ctrl/⌘-клик по флоту добавляет его в группу; Shift-рамка по пустому месту выделяет несколько.',
  'side.group.sub': '{f} флот(ов) · {s} кораблей · {tr} десанта',
  'side.group.title': 'ОПЕРАТИВНАЯ ГРУППА',
  'side.neutral': 'Нейтрал',
  'side.none': 'нет',
  'side.notelemetry.hint':
    'Отправьте флот к этой системе (или расширьте радар), чтобы обнаружить её.',
  'side.notelemetry.sub': 'Не исследовано — вне сенсоров и радаров. Содержимое неизвестно.',
  'side.notelemetry.title': 'НЕТ ТЕЛЕМЕТРИИ',
  'side.scan.buildings': 'Постройки',
  'side.scan.garrison': 'Гарнизон на момент скана',
  'side.scan.hint': 'Обновите данные флотом или радаром.',
  'side.scan.no-buildings': 'построек не видели',
  'side.scan.owner': 'Владелец',
  'side.scan.spy': '🕵 Разведать мир · {c}¤',
  'side.scan.stale': 'Вне сенсорного охвата — последний скан (мог устареть).',
  'side.scan.title': 'ПОСЛЕДНИЕ ДАННЫЕ ✦',
  'side.shipyard.conveyor': 'Конвейер верфи',
  'side.shipyard.hint':
    'Флот -ваше оружие и защита. Здесь вы можете заказывать корабли для пополнения флота.',
  'side.stat.atk': 'АТК',
  'side.stat.def': 'ЗАЩ',
  'side.stat.spd': 'СКР',
  'side.strike.assault': '⚔ Штурм',
  'side.strike.bombard': '⊗ Бомбардировать',
  'side.strike.bombard.stop': '⊗ Прекратить бомбардировку',
  'side.strike.forecast':
    'Прогноз штурма: {v} · ~{r} р. · потери {a} дес. ({pa}%) / {d} гарн. ({pd}%)',
  'side.strike.forecast.attacker': 'десант возьмёт мир',
  'side.strike.forecast.defender': 'гарнизон устоит',
  'side.strike.forecast.draw': 'затяжной пат',
  'side.strike.forecast.hint':
    'Прогноз по видимым составам, без бонусов местности, укреплений и технологий — реальный бой может отличаться.',
  'side.strike.hint':
    'С орбиты можно бомбардировать (изнашивает здания и замораживает их выпуск), но ПВО гарнизона достаёт до вас. Штурм высаживает десант против гарнизона.',
  'side.strike.title': 'Удар',
  'side.summary.attack': 'Атака',
  'side.summary.back': '‹ Назад к карточке',
  'side.summary.cargo': 'Трюм',
  'side.summary.composition': 'Состав',
  'side.summary.day': 'день',
  'side.summary.defense': 'Защита',
  'side.summary.firing-cap': 'бьют {n} юнитов',
  'side.summary.forced-march': 'форс-марш',
  'side.summary.hull': 'Корпус',
  'side.summary.radar': 'Радар',
  'side.summary.retreat-haste': 'рывок отхода',
  'side.summary.shield': 'Щит',
  'side.summary.speed': 'Скорость',
  'side.summary.speed.note': 'по самому медленному; техи/фракция/местность — на переходе',
  'side.summary.title': 'Сводка армии',
  'side.summary.total': 'всего',
  'side.summary.troops': 'десант',
  'side.summary.upkeep': 'Содержание',
  'side.tab.buildings': 'Здания',
  'side.tab.fleet': 'Флот',
  'side.tab.ground': 'Земля',
  'side.tab.wings': 'Крылья',
  'side.unit.ground': 'земля',
  'side.unit.space': 'космос',
  'side.wing.conveyor': 'Верфь авиагруппы',
  'side.wing.fuel': 'топливо {n}',
  'side.wing.garrison.hint':
    'Носитель (◈) несёт эскадрильи (△). Запускайте авиагруппу из панели выбранного флота кнопкой «🛩 Запустить эскадрилью».',
  'side.wing.hint':
    'Отделяет эскадрильи в отдельный быстрый флот — уводите его на удар, а носитель остаётся в строю. Нужен хотя бы один не-эскадрильный корабль. Контрится орбитальным ПВО.',
  'side.wing.launch': '🛩 Запустить эскадрилью ({n})',
  'side.wing.patrol-on': '🛩 дежурный вылет: ВКЛ',
  'side.wing.radius': 'радиус {r}',
  'side.wing.rearming': 'перезарядка {n}',
  'side.wing.title': 'Авиагруппа',
  'side.world.blackout': 'блэкаут: радары и ПВО −50%',
  'side.world.bonus.defense': 'оборона',
  'side.world.bonus.production': 'произв.',
  'side.world.buildings': 'Постройки',
  'side.world.capital': 'Столица',
  'side.world.capital.note': '— здесь возродятся и сменят модули герои',
  'side.world.count.buildings': 'построек',
  'side.world.count.ground': 'наземных',
  'side.world.count.ships': 'кораблей',
  'side.world.count.squadrons': 'эскадрилий',
  'side.world.defense': 'оборона {p}',
  'side.world.designation': 'Обозначение',
  'side.world.fleet-ships': '{n} кораблей',
  'side.world.fleets': 'Флоты на орбите',
  'side.world.garrison': 'Гарнизон',
  'side.world.hold': '🚩 Держать',
  'side.world.hold.clear': 'Снять точку',
  'side.world.hold.set': '🚩 Назначить точкой удержания',
  'side.world.hold.title': 'Точка удержания',
  'side.world.kind': 'Вид / тип / местность',
  'side.world.make-capital': '★ Сделать столицей',
  'side.world.output': 'Базовый выход/ч',
  'side.world.output.note': '— перекос типа мира',
  'side.world.owner': 'Владелец',
  'side.world.ping': '📍 Пинг',
  'side.world.ping.long': '📍 Пинг — отметить и отправить…',
  'side.world.production': 'произв. {p}',
  'side.world.spy-window': '🕵 Окно разведки',
  'side.world.spy-window.left': 'ещё {left}',
  'side.world.stat.garrison': 'гарнизон',
  'side.world.summary': 'Сводка мира',
  'side.world.type': 'Тип: «{pt}» — {mods}',
  'side.world.type-bonuses': 'Бонусы типа',
  'side.world.type.long': 'Мир типа «{pt}» — {mods}',
  'side.world.vp': 'Очки победы',

  'side.tiles.empty': 'нет',

  // --- speed — Панель времени: подсказки множителей, перезапуска и выхода.
  'speed.exit': 'Выход в меню',
  'speed.mult.half-hour': 'полчаса в секунду',
  'speed.mult.hour': 'час в секунду',
  'speed.mult.real': 'реальное время',
  'speed.mult.two-hours': 'два часа в секунду',
  'speed.restart': 'Перезапуск — к выбору ботов',

  // --- steward — «Хранитель»: передача места ИИ на сон, позы, журнал вахты.
  'steward.duration': 'Передать на',
  'steward.duration.hours': '{h} ч',
  'steward.locked': '«Протокол Хранитель» ещё не изучен.',
  'steward.locked.go': 'Открыть технологии',
  'steward.locked.how':
    'Изучите его в окне технологий — затем сможете передать место ИИ на время сна.',
  'steward.locked.where':
    'Ветка <b>Командование</b>, открывается в <b>День 16</b> учёному <b>Куратор</b> (сейчас день {day}).',
  'steward.log.ago': '{dur} назад',
  'steward.log.counter': '⚔ Контрудар у {node}: прогноз потерь {pct}%',
  'steward.log.evac': '🏃 Эвакуация с {node} → {to}: прогноз потерь {pct}%, крыльев уведено: {n}',
  'steward.log.evac-failed':
    '⚠ Гарнизон {node} не эвакуировать: транспорт не успевает (прогноз потерь {pct}%)',
  'steward.log.ferry': '🚚 Паром выслан к {node} за гарнизоном',
  'steward.log.held': '🛡 Рубеж {node} удержан: прогноз потерь {pct}%',
  'steward.log.reinforce': '🚩 Подкрепление выслано к {node}: прогноз потерь {pct}%',
  'steward.log.sortie': '🛫 Дежурный вылет поднят у {node}',
  'steward.log.title': 'Журнал Хранителя',
  'steward.on.active': 'Хранитель ведёт активную оборону.',
  'steward.on.active.note':
    'Пока вы спите: держит рубежи, поднимает дежурные эскадрильи и контратакует у своих миров, когда прогноз потерь приемлем.',
  'steward.on.defense': 'Хранитель ведёт оборону.',
  'steward.on.defense.note':
    'Пока вы спите: держит рубежи и отбивает атаки, застраивает очередь и торгует — без наступлений.',
  'steward.on.returns': 'Управление вернётся через <b>{dur}</b>.',
  'steward.on.warning':
    '«Автопилот держит вас в игре — побеждает активная игра.» Оборонительная поза не ходит в атаку и не ведёт дипломатию.',
  'steward.ready': 'Хранитель готов.',
  'steward.ready.note':
    'Передайте место доверенному ИИ, пока вы офлайн — он удержит рубежи и вернёт управление к сроку.',
  'steward.stance': 'Поза',
  'steward.stance.active': 'Активная оборона',
  'steward.stance.active.note':
    'Активная оборона: всё то же, плюс контрудар по врагу у своих миров при приемлемом прогнозе потерь (до 35%) и дежурные вылеты эскадрилий. Свою территорию не покидает.',
  'steward.stance.defense': 'Оборона',
  'steward.stance.defense.note':
    'Поза «Оборона»: держит и отбивает, застраивает очередь, торгует — без наступлений и дипломатии. Управление вернётся автоматически, с утренней сводкой.',
  'steward.take-back': 'Вернуть управление',

  // --- tech — Дерево технологий: названия веток.
  'tech.branch.command': 'Командование',
  'tech.branch.ground': 'Земля',
  'tech.branch.missile': 'Ракеты',
  'tech.branch.space': 'Космос',
  'tech.branch.squadron': 'Эскадрильи',

  // --- tech — Дерево технологий: требования узла, рельса дней, состояния и действия.
  'tech.action.done': 'Изучено',
  'tech.action.needs-parent': 'Сначала изучите узел выше',
  'tech.action.no-resources': 'Не хватает ресурсов',
  'tech.action.opens-day': 'Откроется в День {n}',
  'tech.action.research': 'Исследовать',
  'tech.action.running': 'Идёт — ≈ {n} ч',
  'tech.action.unmet': 'Условие не выполнено',
  'tech.curator': 'Ветку курирует',
  'tech.curator.none': 'Без лидера ветки — узлы с условием «учёный» закрыты',
  'tech.day': 'День {n}',
  'tech.from-day': 'с дня {n}',
  'tech.grants': 'открывает: {x}',
  'tech.grants.ability': 'способность: {x}',
  'tech.grants.steward': 'Хранитель',
  'tech.rail.day': 'ДЕНЬ',
  'tech.rail.day-short': 'день',
  'tech.rail.start': 'старт',
  'tech.req.building': 'здание: {b} ×{n}',
  'tech.req.planet': 'мир типа {p} ×{n}',
  'tech.req.scientist': 'нужен учёный: {b}',
  'tech.req.scientist.any': 'любой ветки',
  'tech.req.sectors': 'своих секторов: {n}',
  'tech.req.special': 'особое условие',
  'tech.req.title': 'Требует:',
  'tech.req.unit': 'юнит: {u} ×{n}',
  'tech.slots': 'слоты {a}/{b}',
  'tech.state.done': 'ИЗУЧЕНО',
  'tech.state.locked': 'ЗАКРЫТО',
  'tech.state.open': 'ДОСТУПНО',
  'tech.state.running': 'ИССЛЕДУЕТСЯ',

  // --- upd — Баннер обновления сборки (APK; в браузере не показывается).
  'upd.apk-only': 'обновления доступны только в APK',
  'upd.available': 'Доступна новая сборка',
  'upd.bad-version': '✗ ответ получен, но версия не распознана',
  'upd.build': 'сборка {b}',
  'upd.checking': 'проверка: {msg}',
  'upd.current': '✓ актуально · локально {l} · сервер {r}',
  'upd.go': 'Обновить',
  'upd.http-error': '✗ GitHub ответил {s}',
  'upd.later': 'Позже',
  'upd.no-network': '✗ нет связи с GitHub (сеть / VPN?)',

  // --- welcome — Экран приветствия: вход, регистрация, восстановление, список матчей, подвал.
  'welcome.apple': 'Войти через Apple',
  'welcome.back': '‹ назад',
  'welcome.browse.go': 'Обновить список',
  'welcome.browse.nick': 'Позывной',
  'welcome.browse.pass': 'Пароль',
  'welcome.browse.server': 'Сервер',
  'welcome.browse.sub': 'Выбери матч из списка и войди, или обнови список.',
  'welcome.browse.tab.active': 'Активные',
  'welcome.browse.tab.archived': 'Архив',
  'welcome.browse.tab.available': 'Доступные',
  'welcome.browse.title': 'МАТЧИ',
  'welcome.divider': 'войти через',
  'welcome.go': 'Войти',
  'welcome.google': 'Войти через Google',
  'welcome.imprint': 'Выходные данные',
  'welcome.login': 'Вход по позывному',
  'welcome.new': 'Новый командир',
  'welcome.nick.ph': 'позывной',
  'welcome.pass.again.ph': 'ещё раз',
  'welcome.pass.min.ph': 'минимум 8 символов',
  'welcome.pass.ph': 'пароль (аккаунт создастся сам)',
  'welcome.privacy': 'Политика конфиденциальности',
  'welcome.recover.go': 'Отправить ссылку',
  'welcome.recover.mail': 'Почта',
  'welcome.recover.sub': 'Укажи почту аккаунта — пришлём ссылку для сброса пароля.',
  'welcome.recover.title': 'Восстановление доступа',
  'welcome.register.go': 'Создать командира',
  'welcome.register.mail': 'Почта (для восстановления)',
  'welcome.register.nick': 'Имя командира',
  'welcome.register.pass': 'Пароль',
  'welcome.register.pass2': 'Повтор пароля',
  'welcome.register.recover': 'Восстановить доступ',
  'welcome.register.sub': 'Придумай позывной и пароль — так создаётся аккаунт.',
  'welcome.register.title': 'Новый командир',
  'welcome.reset.go': 'Сменить пароль',
  'welcome.reset.pass': 'Пароль',
  'welcome.reset.pass2': 'Повтор пароля',
  'welcome.reset.sub': 'Придумай новый пароль для входа.',
  'welcome.reset.title': 'Новый пароль',
  'welcome.solo': 'Одиночная игра',
  'welcome.sub': 'Добро пожаловать, командир. Флот ждёт приказа.',
  'welcome.support': 'Поддержка',
  'welcome.tagline': 'Грань пустоты',
  'welcome.terms': 'Условия',
  'welcome.testmode': '🧪 Тесты · режим разработчика',
  'welcome.update-check': 'Проверить обновления',

  // --- win — Заголовки окон матча (сводки, технологии, хранитель, конструкторы).
  'win.divdesign.title': 'КОНСТРУКТОР ДИВИЗИЙ',
  'win.log.recap': 'Сводка возвращения',
  'win.log.title': 'СВОДКИ',
  'win.scipick.back': '↩ В меню',
  'win.scipick.title': 'СОВЕТ УЧЁНЫХ',
  'win.steward.title': 'ХРАНИТЕЛЬ · ИИ НА СОН',
  'win.tech.title': 'ТЕХНОЛОГИИ',
};
