// РУССКАЯ локаль. Ключ → текст. Русский здесь — ИСТОЧНИК: именно он показывается,
// когда в выбранной локали ключа ещё нет (см. localization/index.ts).
//
// Ключ = домен.сущность.аспект, точки — иерархия, kebab-case внутри сегмента:
//   err.no-capacity · data.metal-mine · hero.ability.corridor.desc
//
// НЕ добавляй сюда русский текст, который уже лежит в коде строкой — сначала
// заведи ключ, потом замени строку в коде на t('ключ').
export const ru: Record<string, string> = {
  // --- data — Имена игровых ДАННЫХ (data/*.json + таблицы прототипа), через tData().
  'data.aa': 'ПВО',
  'data.artillery': 'артиллерия',
  'data.asteroid-field': 'Астероидное поле',
  'data.barracks': 'Казармы',
  'data.barren': 'Безжизненный',
  'data.bomber': 'бомбардировщик',
  'data.carrier': 'носитель',
  'data.credit-refinery': 'Кредитный НПЗ',
  'data.credits': 'кредиты',
  'data.cruiser': 'крейсер',
  'data.crystalline': 'Кристаллический',
  'data.dead-world': 'Мёртвый мир',
  'data.debris-field': 'Поле обломков',
  'data.deep-void': 'Глубокая пустота',
  'data.dense-nebula': 'Плотная туманность',
  'data.derelict-graveyard': 'Кладбище кораблей',
  'data.dropship': 'носитель',
  'data.empty-space': 'Пустое пространство',
  'data.energy': 'энергия',
  'data.fighter-squadron': 'истребительная эскадрилья',
  'data.food': 'пища',
  'data.fort': 'Форт',
  'data.fortified-infrastructure': 'Укреплённая инфраструктура',
  'data.fortress-world': 'Мир-крепость',
  'data.front': 'передняя линия',
  'data.fusion-plant': 'Термоядерная станция',
  'data.gas-giant': 'Газовый гигант',
  'data.ground': 'земля',
  'data.heavy-infantry': 'тяжёлая пехота',
  'data.hero': 'флагман',
  'data.hydroponics-farm': 'Гидропонная ферма',
  'data.industrial-automation': 'Промышленная автоматизация',
  'data.ion-storm': 'Ионный шторм',
  'data.irradiated': 'Облучённый',
  'data.metal': 'металл',
  'data.metal-mine': 'Металлодобыча',
  'data.microelectronics': 'микроэлектроника',
  'data.microelectronics-fab': 'Фабрика микроэлектроники',
  'data.microelectronics-fabrication': 'Производство микроэлектроники',
  'data.militia': 'ополчение',
  'data.nebula': 'Туманность',
  'data.oceanic': 'Океанический',
  'data.open-space': 'Открытый космос',
  'data.orbital-aa': 'Орбитальное ПВО',
  'data.orbital-logistics': 'Орбитальная логистика',
  'data.planet': 'Планета',
  'data.radar-array': 'Радарный массив',
  'data.rear': 'тыл',
  'data.relic-world': 'Реликтовый мир',
  'data.ringworld': 'Кольцевой мир',
  'data.salvage-metal-rig': 'Утилизационная станция',
  'data.scout': 'разведчик',
  'data.siege': 'осадная платформа',
  'data.siege-doctrine': 'Осадная доктрина',
  'data.solar-flare-zone': 'Зона солнечных вспышек',
  'data.space': 'космос',
  'data.special-forces': 'спецназ',
  'data.squadron': 'эскадрилья',
  'data.strike-carrier': 'ударный носитель',
  'data.tank': 'танк',
  'data.tax-office': 'Налоговая управа',
  'data.terran': 'Земной',
  'data.void-fortress': 'Крепость пустоты',
  'data.volcanic': 'Вулканический',

  // --- diplo — Дипломатия: названия отношений между игроками.
  'diplo.stance.alliance': 'Союз',
  'diplo.stance.pact': 'Пакт',
  'diplo.stance.peace': 'Мир',
  'diplo.stance.war': 'Война',

  // --- err — Отказы ядра (kernel rejection codes). Ключ выводится из кода: E_NO_CAPACITY → err.no-capacity.
  'err.already': 'уже действует',
  'err.already-fitted': 'фиттинг уже установлен',
  'err.already-offered': 'предложение уже отправлено',
  'err.already-unlocked': 'узел уже изучен',
  'err.bad-effect': 'способность настроена некорректно',
  'err.bad-payload': 'некорректный приказ',
  'err.bad-spawn': 'здесь нельзя развернуть героя',
  'err.bad-target': 'недопустимая цель',
  'err.bombarded': 'стройка под бомбардировкой',
  'err.bot-alliance': 'боты не вступают в коалиции',
  'err.chat-rate': 'подождите пару секунд',
  'err.chat-target': 'адресат не найден',
  'err.chat-text': 'пустое сообщение',
  'err.conditions-unmet': 'условия не выполнены',
  'err.consent-required': 'требуется согласие второй стороны',
  'err.cooldown': 'способность перезаряжается',
  'err.fleet-busy': 'флот занят',
  'err.forbidden': 'действие запрещено',
  'err.hero-alive': 'герой уже командует кораблём',
  'err.hero-cap': 'достигнут предел развёрнутых героев',
  'err.hero-dead': 'герой погиб — дождитесь возрождения',
  'err.hero-not-deployed': 'герой не развёрнут — сначала поднимите корабль',
  'err.insufficient': 'не хватает ресурсов',
  'err.internal': 'внутренняя ошибка',
  'err.limit': 'достигнут предел',
  'err.no-ability': 'неизвестная способность',
  'err.no-artillery': 'нет артиллерии',
  'err.no-capacity': 'трюм полон',
  'err.no-capital': 'нет столицы для отзыва',
  'err.no-effect': 'эффект ещё не реализован',
  'err.no-fitting': 'неизвестный фиттинг',
  'err.no-fleet': 'флот не найден',
  'err.no-funds': 'не хватает средств',
  'err.no-hero': 'герой не найден',
  'err.no-node': 'неизвестный узел дерева',
  'err.no-planet': 'мир не найден',
  'err.no-player': 'игрок не найден',
  'err.no-ships': 'нет кораблей',
  'err.no-shipyard': 'нужна верфь/космопорт',
  'err.no-slots': 'слоты фиттингов заняты',
  'err.no-target': 'нет цели',
  'err.no-troops': 'мир защищён — для штурма нужен десант на борту',
  'err.not-destructible': 'этот мир нельзя уничтожить',
  'err.not-equipped': 'у героя нет этой способности',
  'err.out-of-range': 'вне радиуса действия',
  'err.own-planet': 'это ваш собственный мир',
  'err.requires': 'сначала изучите предыдущий узел',
  'err.research-slots-full': 'все исследовательские слоты заняты',
  'err.respawn-cooldown': 'герой ещё восстанавливается',
  'err.same-location': 'флот уже здесь',
  'err.too-early': 'слишком рано',
  'err.unknown-building': 'неизвестное здание',
  'err.unknown-technology': 'неизвестная технология',
  'err.unknown-unit': 'неизвестный юнит',
  'err.wrong-branch': 'узел чужой ветви',
  'err.wrong-orbit': 'недопустимая орбита',
  'err.wrong-sector': 'недопустимый тип сектора',

  // --- hero — Герои: грейды, способности (имя + описание).
  'hero.ability.annihilate.desc': 'Уничтожает планету в радиусе — она становится мёртвым миром.',
  'hero.ability.annihilate.name': 'Аннигиляция',
  'hero.ability.bulwark.desc': 'Временный щит: +оборона своим флотам рядом с героем.',
  'hero.ability.bulwark.name': 'Бастион',
  'hero.ability.corridor.desc':
    'Открывает временный коридор-лейн до близкого мира; свои флоты идут по нему быстрее.',
  'hero.ability.corridor.name': 'Коридор',
  'hero.ability.rally.desc':
    'Боевой клич: временный доп. бонус к ауре для своих флотов рядом с героем.',
  'hero.ability.rally.name': 'Сбор',
  'hero.ability.recall.desc': 'Мгновенно отзывает корабль-героя в столицу.',
  'hero.ability.recall.name': 'Отзыв',
  'hero.ability.scan.desc': 'Раскрывает зону вокруг цели сквозь туман на время.',
  'hero.ability.scan.name': 'Разведка',
  'hero.grade.common': 'Обычный',
  'hero.grade.legendary': 'Легендарный',
  'hero.grade.main': 'Главный',
  'hero.grade.rare': 'Редкий',

  // --- hub — Хаб (экран между матчами): шапка, карточки, плитки «Ещё», нижняя навигация.
  'hub.ally.corp': 'Кабинет корпорации',
  'hub.ally.empty.sub': 'корпорации · общие AvA-битвы · влияние',
  'hub.ally.empty.title': 'Альянсы',
  'hub.digest.empty.sub':
    'Войди в матч на вкладке «Игры» — здесь появятся ходы, требующие внимания.',
  'hub.digest.empty.title': 'Нет матчей, ждущих приказа',
  'hub.digest.section': 'Сводка',
  'hub.msgs.aria': 'Сообщения',
  'hub.nav.ally': 'Альянсы',
  'hub.nav.arsenal': 'Арсенал',
  'hub.nav.games': 'Игры',
  'hub.nav.home': 'Домой',
  'hub.nav.meta': 'Прокачка',
  'hub.nav.more': 'Ещё',
  'hub.nav.rank': 'Рейтинг',
  'hub.onboard.skip': 'Пропустить',
  'hub.onboard.start': 'Начать обучение',
  'hub.onboard.sub': 'Короткое обучение покажет интерфейс и первый ход — пара минут.',
  'hub.onboard.title': 'Впервые в Void Dominion?',
  'hub.play': 'ИГРАТЬ СЕЙЧАС',
  'hub.rank.empty.sub': 'сезонный рейтинг по местам в матчах',
  'hub.rank.empty.title': 'Рейтинги — скоро',
  'hub.season.sub': 'Рейтинги и альянсы откроются со стартом мета-слоя.',
  'hub.season.title': 'Сезон ещё не начат',
  'hub.solo': 'Одиночная игра',
  'hub.status.online': 'в сети',
  'hub.tile.account': 'Аккаунт',
  'hub.tile.chat': 'Чат',
  'hub.tile.community': 'Сообщество',
  'hub.tile.help': 'Справочник',
  'hub.tile.logout': 'Сменить командира',
  'hub.tile.notifications': 'Уведомления',
  'hub.tile.settings': 'Настройки',
  'hub.tile.support': 'Поддержка',
  'hub.tile.tutorial': 'Обучение',
  'hub.tile.updates': 'Обновления',

  // --- hud — Постоянный интерфейс матча: верхняя панель ресурсов.
  'hud.resource.credits': 'Кредиты',
  'hud.resource.energy': 'Энергия',
  'hud.resource.food': 'Пища',
  'hud.resource.metal': 'Металл',
  'hud.resource.microelectronics': 'Микроэлектроника',

  // --- market — Биржа: вкладки ресурсов.
  'market.res.energy': 'Энергия',
  'market.res.food': 'Пища',
  'market.res.metal': 'Металл',
  'market.res.microelectronics': 'Микро',

  // --- rail — Рельса инструментов в матче: подпись кнопки (.label) + подсказка (.title).
  'rail.chat.label': 'Чат',
  'rail.chat.title': 'Чат',
  'rail.constructor.label': 'Верфь',
  'rail.constructor.title': 'Конструктор — оснащение кораблей, эскадрилий, армии и героев',
  'rail.corp.label': 'Корп',
  'rail.corp.title': 'Корпорация',
  'rail.diplo.label': 'Дипло',
  'rail.diplo.title': 'Дипломатия',
  'rail.exit.label': 'Выйти',
  'rail.exit.title': 'Покинуть сессию',
  'rail.help.label': 'Справка',
  'rail.help.title': 'Справочник',
  'rail.log.label': 'Сводки',
  'rail.log.title': 'Сводки',
  'rail.market.label': 'Рынок',
  'rail.market.title': 'Рынок',
  'rail.msgs.label': 'Почта',
  'rail.msgs.title': 'Сообщения',
  'rail.settings.label': 'Настройки',
  'rail.settings.title': 'Настройки',
  'rail.steward.label': 'Сон',
  'rail.steward.title': 'Хранитель — передать ИИ на сон',
  'rail.tech.label': 'Наука',
  'rail.tech.title': 'Технологии',

  // --- seatpick — Выбор фракции и места перед входом в сетевой матч.
  'seatpick.cancel': 'Назад',
  'seatpick.go': 'ВЫБРАТЬ',
  'seatpick.sub': 'Выберите фракцию и стартовую позицию. Занятые места отмечены серым.',
  'seatpick.title': 'Выбор фракции',

  // --- setup — Экран «Настройка схватки»: домашний мир, боты, скорость времени.
  'setup.cancel': 'Назад',
  'setup.go': 'ЗАПУСК',
  'setup.map-hint': 'Тапните светящийся мир, чтобы выбрать старт',
  'setup.sandbox': '🧪 Песочница',
  'setup.speed.hint':
    '×1 — реальное время (час пути = час жизни, мир живёт и офлайн). Для быстрой партии выбери ×10–×100.',
  'setup.speed.label': 'Скорость времени',
  'setup.sub':
    'Выберите свой домашний мир на карте, задайте число соперников-ботов и запускайте. Пустые места займут боты — выключите место, чтобы командовать меньшим сектором, или выключите все ради мирной одиночной песочницы для знакомства с интерфейсом.',
  'setup.title': 'НАСТРОЙКА СХВАТКИ',

  // --- ship — Корабли: корпуса и модули (имя + описание).
  'ship.hull.cruiser': 'Крейсер',
  'ship.hull.dropship': 'Носитель',
  'ship.hull.scout_drone': 'Скаут-дрон',
  'ship.hull.siege_lance': 'Осадная ланса',
  'ship.module.battery.desc': '+30% к атаке.',
  'ship.module.battery.name': 'Батарея',
  'ship.module.plating.desc': '+25% HP корпуса.',
  'ship.module.plating.name': 'Броня',
  'ship.module.shield.desc': '+30% к обороне.',
  'ship.module.shield.name': 'Щит',
  'ship.module.targeting.desc': '+15% к атаке и обороне.',
  'ship.module.targeting.name': 'Наведение',
  'ship.module.thruster.desc': '+20% к скорости.',
  'ship.module.thruster.name': 'Двигатель',

  // --- speed — Панель времени: подсказки множителей, перезапуска и выхода.
  'speed.exit': 'Выход в меню',
  'speed.mult.half-hour': 'полчаса в секунду',
  'speed.mult.hour': 'час в секунду',
  'speed.mult.real': 'реальное время',
  'speed.mult.two-hours': 'два часа в секунду',
  'speed.restart': 'Перезапуск — к выбору ботов',

  // --- tech — Дерево технологий: названия веток.
  'tech.branch.command': 'Командование',
  'tech.branch.ground': 'Земля',
  'tech.branch.missile': 'Ракеты',
  'tech.branch.space': 'Космос',
  'tech.branch.squadron': 'Эскадрильи',

  // --- upd — Баннер обновления сборки (APK; в браузере не показывается).
  'upd.available': 'Доступна новая сборка',
  'upd.go': 'Обновить',
  'upd.later': 'Позже',

  // --- welcome — Экран приветствия: вход, регистрация, восстановление, список матчей, подвал.
  'welcome.apple': 'Войти через Apple',
  'welcome.back': '‹ назад',
  'welcome.browse.go': 'Обновить список',
  'welcome.browse.nick': 'Позывной',
  'welcome.browse.pass': 'Пароль',
  'welcome.browse.server': 'Сервер',
  'welcome.browse.sub': 'Выбери матч из списка и войди, или обнови список.',
  'welcome.browse.tab.active': 'Активные',
  'welcome.browse.tab.archived': 'Архив',
  'welcome.browse.tab.available': 'Доступные',
  'welcome.browse.title': 'МАТЧИ',
  'welcome.divider': 'войти через',
  'welcome.go': 'Войти',
  'welcome.google': 'Войти через Google',
  'welcome.imprint': 'Выходные данные',
  'welcome.login': 'Вход по позывному',
  'welcome.new': 'Новый командир',
  'welcome.nick.ph': 'позывной',
  'welcome.pass.again.ph': 'ещё раз',
  'welcome.pass.min.ph': 'минимум 8 символов',
  'welcome.pass.ph': 'пароль (аккаунт создастся сам)',
  'welcome.privacy': 'Политика конфиденциальности',
  'welcome.recover.go': 'Отправить ссылку',
  'welcome.recover.mail': 'Почта',
  'welcome.recover.sub': 'Укажи почту аккаунта — пришлём ссылку для сброса пароля.',
  'welcome.recover.title': 'Восстановление доступа',
  'welcome.register.go': 'Создать командира',
  'welcome.register.mail': 'Почта (для восстановления)',
  'welcome.register.nick': 'Имя командира',
  'welcome.register.pass': 'Пароль',
  'welcome.register.pass2': 'Повтор пароля',
  'welcome.register.recover': 'Восстановить доступ',
  'welcome.register.sub': 'Придумай позывной и пароль — так создаётся аккаунт.',
  'welcome.register.title': 'Новый командир',
  'welcome.reset.go': 'Сменить пароль',
  'welcome.reset.pass': 'Пароль',
  'welcome.reset.pass2': 'Повтор пароля',
  'welcome.reset.sub': 'Придумай новый пароль для входа.',
  'welcome.reset.title': 'Новый пароль',
  'welcome.solo': 'Одиночная игра',
  'welcome.sub': 'Добро пожаловать, командир. Флот ждёт приказа.',
  'welcome.support': 'Поддержка',
  'welcome.tagline': 'Грань пустоты',
  'welcome.terms': 'Условия',
  'welcome.testmode': '🧪 Тесты · режим разработчика',
  'welcome.update-check': 'Проверить обновления',

  // --- win — Заголовки окон матча (сводки, технологии, хранитель, конструкторы).
  'win.divdesign.title': 'КОНСТРУКТОР ДИВИЗИЙ',
  'win.log.recap': 'Сводка возвращения',
  'win.log.title': 'СВОДКИ',
  'win.scipick.back': '↩ В меню',
  'win.scipick.title': 'СОВЕТ УЧЁНЫХ',
  'win.steward.title': 'ХРАНИТЕЛЬ · ИИ НА СОН',
  'win.tech.title': 'ТЕХНОЛОГИИ',
};
