// РУССКАЯ локаль. Ключ → текст. Русский здесь — ИСТОЧНИК: именно он показывается,
// когда в выбранной локали ключа ещё нет (см. localization/index.ts).
//
// Ключ = домен.сущность.аспект, точки — иерархия, kebab-case внутри сегмента:
//   err.no-capacity · data.metal-mine · hero.ability.corridor.desc
//
// НЕ добавляй сюда русский текст, который уже лежит в коде строкой — сначала
// заведи ключ, потом замени строку в коде на t('ключ').
export const ru: Record<string, string> = {
  // --- codex — Кодекс: карточка здания/юнита/модуля (строки характеристик) и статьи-термины.
  'codex.hub.close': 'ЗАКРЫТЬ',
  'codex.hub.empty': 'Ничего не найдено',
  'codex.hub.search.aria': 'Поиск по справочнику',
  'codex.hub.search.ph': 'Поиск: юнит, здание, термин…',
  'codex.hub.sec.building': 'Здания',
  'codex.hub.sec.mechanic': 'Механики',
  'codex.hub.sec.unit': 'Юниты',
  'codex.hub.title': 'СПРАВОЧНИК',
  'codex.row.aa': 'ПВО',
  'codex.row.atk-def': 'Атака / Оборона',
  'codex.row.build-time': 'Время постройки',
  'codex.row.cargo': 'Вместимость трюма',
  'codex.row.class': 'Класс',
  'codex.row.cost': 'Стоимость',
  'codex.row.garrison-defense': 'Оборона гарнизона',
  'codex.row.hp': 'Прочность',
  'codex.row.hull': 'Корпус',
  'codex.row.levels': 'Уровней',
  'codex.row.produces': 'Производит',
  'codex.row.radar': 'Радиус радара',
  'codex.row.range': 'Дальность',
  'codex.row.score': 'Очки победы',
  'codex.row.signature': 'Радарная сигнатура',
  'codex.row.slot': 'Слот',
  'codex.row.speed': 'Скорость',
  'codex.row.upkeep': 'Содержание',
  'codex.tag.building': 'здание',
  'codex.tag.fitting': 'фитинг',
  'codex.tag.ground-unit': 'наземный юнит',
  'codex.tag.mechanic': 'механика',
  'codex.tag.module': 'модуль',
  'codex.tag.ship': 'корабль',
  'codex.term.async.body':
    'Мир идёт в реальном времени и продолжается 24/7 — даже когда ты вышел. Приказы занимают реальные часы: отдал курс, закрыл игру, вернулся к результату. Это не пошаговая игра — заходи, отдавай приказы, выходи.',
  'codex.term.async.title': 'Асинхронный мир',
  'codex.term.capture.body':
    'Захват мира — двухфазный. Сначала выйди на орбиту и подави оборону в космосе; если мир защищён гарнизоном — высади десант (наземную дивизию из трюма). Небо, потом земля.',
  'codex.term.capture.title': 'Орбита и высадка',
  'codex.term.coalition.body':
    'Дипломатия позволяет заключать пакты и союзы, но коалиция ограничена порогом совокупной силы — нельзя собрать всех против одного. Порог держит баланс сил и не даёт «снежному кому» задавить партию.',
  'codex.term.coalition.title': 'Коалиционный порог',
  'codex.term.fog.body':
    'Ты видишь только то, что рядом с твоими силами и радарами; остальное скрыто туманом или показано по памяти (последнее, что ты там видел). Разведчики и радары раздвигают обзор — держи глаза открытыми.',
  'codex.term.fog.title': 'Туман войны',
  'codex.term.lanes.body':
    'Флоты ходят не напрямую, а по звёздным трассам (лэйнам) между мирами — маршрут строится автоматически. Узлы на трассах можно перехватывать: встречный враг на пути — это бой.',
  'codex.term.lanes.title': 'Звёздные трассы',
  'codex.term.score.body':
    'Очки капают за то, чем ты владеешь: мир — 50, прочий сектор — 10, здания добавляют по уровню. Набери порог очков — победа. Другой путь к победе — уничтожение соперников или доминирование.',
  'codex.term.score.title': 'Очки победы',
  'codex.term.upkeep.body':
    'Флоты и здания требуют ежедневной платы. Доход от шахт минус содержание = чистый баланс; уйдёшь в минус — казна опустеет. Строй экономику раньше армии.',
  'codex.term.upkeep.title': 'Содержание (upkeep)',
  'codex.value.hours': '{n} ч',
  'codex.value.levels-upgradable': '{n} (улучшаемо)',
  'codex.value.per-day': '{n} {r}/день',
  'codex.value.per-hour': '{n} {r}/ч',
  'codex.value.per-level': '{n} / уровень',

  // --- data — Имена игровых ДАННЫХ (data/*.json + таблицы прототипа), через tData().
  'data.aa': 'ПВО',
  'data.artillery': 'артиллерия',
  'data.asteroid-field': 'Астероидное поле',
  'data.barracks': 'Казармы',
  'data.barren': 'Безжизненный',
  'data.bomber': 'бомбардировщик',
  'data.carrier': 'носитель',
  'data.credit-refinery': 'Кредитный НПЗ',
  'data.credits': 'кредиты',
  'data.cruiser': 'крейсер',
  'data.crystalline': 'Кристаллический',
  'data.dead-world': 'Мёртвый мир',
  'data.debris-field': 'Поле обломков',
  'data.deep-void': 'Глубокая пустота',
  'data.dense-nebula': 'Плотная туманность',
  'data.derelict-graveyard': 'Кладбище кораблей',
  'data.dropship': 'носитель',
  'data.empty-space': 'Пустое пространство',
  'data.energy': 'энергия',
  'data.fighter-squadron': 'истребительная эскадрилья',
  'data.food': 'пища',
  'data.fort': 'Форт',
  'data.fortified-infrastructure': 'Укреплённая инфраструктура',
  'data.fortress-world': 'Мир-крепость',
  'data.front': 'передняя линия',
  'data.fusion-plant': 'Термоядерная станция',
  'data.gas-giant': 'Газовый гигант',
  'data.ground': 'земля',
  'data.heavy-infantry': 'тяжёлая пехота',
  'data.hero': 'флагман',
  'data.hydroponics-farm': 'Гидропонная ферма',
  'data.industrial-automation': 'Промышленная автоматизация',
  'data.ion-storm': 'Ионный шторм',
  'data.irradiated': 'Облучённый',
  'data.metal': 'металл',
  'data.metal-mine': 'Металлодобыча',
  'data.microelectronics': 'микроэлектроника',
  'data.microelectronics-fab': 'Фабрика микроэлектроники',
  'data.microelectronics-fabrication': 'Производство микроэлектроники',
  'data.militia': 'ополчение',
  'data.nebula': 'Туманность',
  'data.oceanic': 'Океанический',
  'data.open-space': 'Открытый космос',
  'data.orbital-aa': 'Орбитальное ПВО',
  'data.orbital-logistics': 'Орбитальная логистика',
  'data.planet': 'Планета',
  'data.radar-array': 'Радарный массив',
  'data.rear': 'тыл',
  'data.relic-world': 'Реликтовый мир',
  'data.ringworld': 'Кольцевой мир',
  'data.salvage-metal-rig': 'Утилизационная станция',
  'data.scout': 'разведчик',
  'data.siege': 'осадная платформа',
  'data.siege-doctrine': 'Осадная доктрина',
  'data.solar-flare-zone': 'Зона солнечных вспышек',
  'data.space': 'космос',
  'data.special-forces': 'спецназ',
  'data.squadron': 'эскадрилья',
  'data.strike-carrier': 'ударный носитель',
  'data.tank': 'танк',
  'data.tax-office': 'Налоговая управа',
  'data.terran': 'Земной',
  'data.void-fortress': 'Крепость пустоты',
  'data.volcanic': 'Вулканический',

  // --- diplo — Дипломатия: названия отношений между игроками.
  'diplo.stance.alliance': 'Союз',
  'diplo.stance.pact': 'Пакт',
  'diplo.stance.peace': 'Мир',
  'diplo.stance.war': 'Война',

  // --- dossier — Досье объектов: здания, корабли, стройка в очереди, вкладки и характеристики.
  'dossier.building.barracks':
    'Казармы нужны для защиты вашего мира от захватчиков. Тут живут ваши доблестные защитники.',
  'dossier.building.default': 'Планетарное сооружение.',
  'dossier.building.fabricator':
    'Чистые цеха литографии печатают {m}▦ в час. Прожорлива к энергии и людям, зато её продукция ведёт эскадрильи и открывает осадные доктрины. Апгрейды окупаются собственной продукцией.',
  'dossier.building.farm':
    'Ярусы гидропонных оранжерей под спектральными лампами позволяют вашим подопечным питаться, ведь голод беспощаден. Выращивает {f}❖ в час. Ваши рабочие и воины едят каждый день, было бы глупо проиграть сражение из-за голодного обморока.',
  'dossier.building.fort':
    'Эшелонированный планетарный бастион. Поднимает оборону гарнизона на {d} и держит {hp} структурной прочности под орбитальным огнём. Последний рубеж осаждённого мира.',
  'dossier.building.metal-station':
    'Добывающая платформа, вгрызается в спёкшуюся кору мёртвого мира. Там, где аннигиляция выжгла всё живое, обнажилась чистая металлическая руда — станция качает {m}⬢ в час. Улучшение увеличивает добычу.',
  'dossier.building.mine':
    'Буровая платформа вгрызается в планету и добывает {m}⬢ в час. Улучшение позволяет копать глубже, чтобы добраться до самых богатых жил. Основа для строительства флота.',
  'dossier.building.orbital-aa':
    'Стационарная зенитная батарея защищает воздушное пространство вашего мира и наносит {dmg} урона в час по кораблям на орбите. Кошмар для бомбардировщиков, повисших над планетой, и для налетающих эскадрилий. Захват мира не блокирует — это дело наземной обороны; батарея лишь выкашивает флот над головой.',
  'dossier.building.power-plant':
    'Термоядерный реактор питает энергией ваши миры, он производит {e}↯ в час. Энергия — кровь ваших построек, ведь они работают не на волшебстве. При дефиците всё проседает до половины мощности.',
  'dossier.building.radar':
    'Комплекс радаров просвечивает пространство вокруг вашего мира и ловит вражеские сигнатуры задолго до того, как они посмеют на вас напасть. Улучшения обеспечивают большее покрытие.',
  'dossier.building.refinery':
    'Перерабатывающий комплекс, превращающий руду и логистику в ликвидные кредиты — {c}¤ в час. Топливо для имперской бюрократии, верфей и наёмных эскадр.',
  'dossier.building.starfort':
    'Автономная крепость, возведённая в астероидное поле: {d} к обороне и {hp} прочности. Превращает безликий перекрёсток в укреплённый узел с орбитой и ПКО',
  'dossier.building.tax-office':
    'Налоговая управа имперского образца: сама ничего не добывает, но ставит на учёт население мира и поднимает его кредитный сбор на {b}.',
  'dossier.divdesign.desc': 'Редактор шаблонов: состав слотов и доктрина дивизий.',
  'dossier.divdesign.name': 'Конструктор дивизий',
  'dossier.division.desc':
    'Наземное соединение, собранное по шаблону. Обороняет мир; грузится на флот из панели флота.',
  'dossier.division.name': 'Дивизия',
  'dossier.fleet.desc':
    'Мобильное оперативное соединение кораблей. Выберите его, чтобы отдавать приказы на манёвр, орбиту и удар по врагу.',
  'dossier.fleet.name': 'Флот',
  'dossier.stat.atk.desc': 'Суммарная атака кораблей флота.',
  'dossier.stat.atk.name': 'Атака',
  'dossier.stat.cap.desc':
    'В залпе бьют максимум {n} юнитов — сильнейшие первыми; все сверх капа только впитывают урон.',
  'dossier.stat.cap.name': 'Линия огня',
  'dossier.stat.datk.desc': 'Суммарная атака дивизии.',
  'dossier.stat.datk.name': 'Атака',
  'dossier.stat.ddef.desc': 'Суммарная защита дивизии.',
  'dossier.stat.ddef.name': 'Защита',
  'dossier.stat.def.desc': 'Суммарная защита кораблей флота.',
  'dossier.stat.def.name': 'Защита',
  'dossier.stat.dhp.desc': 'Суммарные очки здоровья дивизии.',
  'dossier.stat.dhp.name': 'ОЗ',
  'dossier.stat.garrison.desc': 'Численность наземных войск, обороняющих мир.',
  'dossier.stat.garrison.name': 'Гарнизон',
  'dossier.stat.ground.desc': 'Пехота и техника на поверхности мира.',
  'dossier.stat.ground.name': 'Наземные части',
  'dossier.stat.gships.desc': 'Корабли, стоящие в гарнизоне мира (не на орбите).',
  'dossier.stat.gships.name': 'Корабли в гарнизоне',
  'dossier.stat.hp.desc': 'Суммарная прочность кораблей флота.',
  'dossier.stat.hp.name': 'Очки здоровья',
  'dossier.stat.hull.desc':
    'Текущая/полная прочность армии. Чинится у своего мира с верфью — или мгновенно за кредиты.',
  'dossier.stat.hull.name': 'Корпус',
  'dossier.stat.pbuild.desc': 'Число построек на мире.',
  'dossier.stat.pbuild.name': 'Постройки',
  'dossier.stat.shield.desc':
    'Аблятивный щит: принимает урон первым и бесплатно восстанавливается вне боя.',
  'dossier.stat.shield.name': 'Щит',
  'dossier.stat.spd.desc':
    'Скорость перелёта — флот движется со скоростью самого медленного корабля.',
  'dossier.stat.spd.name': 'Скорость',
  'dossier.tab.buildings.desc':
    'Постройки мира и строительный конвейер: состояние, уровни и улучшения.',
  'dossier.tab.buildings.name': 'Здания',
  'dossier.tab.ground.desc':
    'Наземные части обороняют ваши миры. Их можно погрузить на флот для захвата вражеских миров.',
  'dossier.tab.ground.name': 'Земля',
  'dossier.tab.ships.desc':
    'Флот -ваше оружие и защита. Здесь вы можете заказывать корабли для пополнения флота.',
  'dossier.tab.ships.name': 'Флот',
  'dossier.tab.squadron.desc':
    'Носитель (◈) несёт эскадрильи (△). Запускайте авиагруппу из панели выбранного флота кнопкой «🛩 Запустить эскадрилью».',
  'dossier.tab.squadron.name': 'Крылья',
  'dossier.task.eta': 'Осталось: {r}',
  'dossier.task.output': '{r}: {now}/ч сейчас → {final}/ч по готовности',
  'dossier.task.queued': 'В очереди — ещё не начато.',
  'dossier.task.title': 'Стройка',
  'dossier.task.unit-ready': 'По готовности пополнит гарнизон/флот планеты.',
  'dossier.unit.cruiser.desc':
    'Рабочая лошадь линейного флота: {a} атаки, {hp} корпуса и трюм на {c}. Универсальный боевой корабль, одинаково уверенный в обороне и в наступлении.',
  'dossier.unit.cruiser.name': 'Крейсер',
  'dossier.unit.default': 'Боевая единица.',
  'dossier.unit.fighter-squadron.desc':
    'Палубная эскадрилья: стремительная (ход {sp}) и больно бьёт ({a} атаки), но брони почти нет ({hp} корпуса). Отделяется от носителя в отдельный быстрый флот и наносит удар с дистанции {r}. Контрится орбитальным ПВО — не гоните её на прикрытую ПВО планету.',
  'dossier.unit.fighter-squadron.name': 'Истребительная эскадрилья',
  'dossier.unit.hero.desc':
    'Боевая проекция самого командующего — флагман во главе родного флота: {a} атаки и {hp} корпуса. Но решает не это: его присутствие держит эскадру в кулаке, давая {b} к атаке и обороне всем кораблям рядом. Падёт — командующий лишается проекции, пока та не отстроится заново на родном мире.',
  'dossier.unit.hero.name': 'Флагман',
  'dossier.unit.scout.desc':
    'Лёгкий разведывательный корпус. Быстрый (ход {sp}) и почти неслышный (сигнатура {sig}) — чертит карту пустоты там, куда боится соваться линейный флот.',
  'dossier.unit.scout.name': 'Разведчик',
  'dossier.unit.siege.desc':
    'Тяжёлая осадная платформа: {a} урона с дистанции {r}, но тонкая броня ({d} защиты). Её место за спинами крейсеров, откуда она крушит укрепления и верфи.',
  'dossier.unit.siege.name': 'Осадная платформа',
  'dossier.unit.strike-carrier.desc':
    'Медленный бронированный носитель ({hp} корпуса, трюм на {c}) — своих пушек почти нет, вся его сила в эскадрильях, что он несёт. Держите его позади и запускайте авиагруппу по цели кнопкой «🛩 Запустить эскадрилью».',
  'dossier.unit.strike-carrier.name': 'Ударный носитель',

  // --- err — Отказы ядра (kernel rejection codes). Ключ выводится из кода: E_NO_CAPACITY → err.no-capacity.
  'err.already': 'уже действует',
  'err.already-fitted': 'фиттинг уже установлен',
  'err.already-offered': 'предложение уже отправлено',
  'err.already-unlocked': 'узел уже изучен',
  'err.bad-effect': 'способность настроена некорректно',
  'err.bad-payload': 'некорректный приказ',
  'err.bad-spawn': 'здесь нельзя развернуть героя',
  'err.bad-target': 'недопустимая цель',
  'err.bombarded': 'стройка под бомбардировкой',
  'err.bot-alliance': 'боты не вступают в коалиции',
  'err.chat-rate': 'подождите пару секунд',
  'err.chat-target': 'адресат не найден',
  'err.chat-text': 'пустое сообщение',
  'err.conditions-unmet': 'условия не выполнены',
  'err.consent-required': 'требуется согласие второй стороны',
  'err.cooldown': 'способность перезаряжается',
  'err.fleet-busy': 'флот занят',
  'err.forbidden': 'действие запрещено',
  'err.hero-alive': 'герой уже командует кораблём',
  'err.hero-cap': 'достигнут предел развёрнутых героев',
  'err.hero-dead': 'герой погиб — дождитесь возрождения',
  'err.hero-not-deployed': 'герой не развёрнут — сначала поднимите корабль',
  'err.insufficient': 'не хватает ресурсов',
  'err.internal': 'внутренняя ошибка',
  'err.limit': 'достигнут предел',
  'err.no-ability': 'неизвестная способность',
  'err.no-artillery': 'нет артиллерии',
  'err.no-capacity': 'трюм полон',
  'err.no-capital': 'нет столицы для отзыва',
  'err.no-effect': 'эффект ещё не реализован',
  'err.no-fitting': 'неизвестный фиттинг',
  'err.no-fleet': 'флот не найден',
  'err.no-funds': 'не хватает средств',
  'err.no-hero': 'герой не найден',
  'err.no-node': 'неизвестный узел дерева',
  'err.no-planet': 'мир не найден',
  'err.no-player': 'игрок не найден',
  'err.no-ships': 'нет кораблей',
  'err.no-shipyard': 'нужна верфь/космопорт',
  'err.no-slots': 'слоты фиттингов заняты',
  'err.no-target': 'нет цели',
  'err.no-troops': 'мир защищён — для штурма нужен десант на борту',
  'err.not-destructible': 'этот мир нельзя уничтожить',
  'err.not-equipped': 'у героя нет этой способности',
  'err.out-of-range': 'вне радиуса действия',
  'err.own-planet': 'это ваш собственный мир',
  'err.requires': 'сначала изучите предыдущий узел',
  'err.research-slots-full': 'все исследовательские слоты заняты',
  'err.respawn-cooldown': 'герой ещё восстанавливается',
  'err.same-location': 'флот уже здесь',
  'err.too-early': 'слишком рано',
  'err.unknown-building': 'неизвестное здание',
  'err.unknown-technology': 'неизвестная технология',
  'err.unknown-unit': 'неизвестный юнит',
  'err.wrong-branch': 'узел чужой ветви',
  'err.wrong-orbit': 'недопустимая орбита',
  'err.wrong-sector': 'недопустимый тип сектора',

  // --- hero — Герои: грейды, способности (имя + описание).
  'hero.ability.annihilate.desc': 'Уничтожает планету в радиусе — она становится мёртвым миром.',
  'hero.ability.annihilate.name': 'Аннигиляция',
  'hero.ability.bulwark.desc': 'Временный щит: +оборона своим флотам рядом с героем.',
  'hero.ability.bulwark.name': 'Бастион',
  'hero.ability.corridor.desc':
    'Открывает временный коридор-лейн до близкого мира; свои флоты идут по нему быстрее.',
  'hero.ability.corridor.name': 'Коридор',
  'hero.ability.rally.desc':
    'Боевой клич: временный доп. бонус к ауре для своих флотов рядом с героем.',
  'hero.ability.rally.name': 'Сбор',
  'hero.ability.recall.desc': 'Мгновенно отзывает корабль-героя в столицу.',
  'hero.ability.recall.name': 'Отзыв',
  'hero.ability.scan.desc': 'Раскрывает зону вокруг цели сквозь туман на время.',
  'hero.ability.scan.name': 'Разведка',
  'hero.grade.common': 'Обычный',
  'hero.grade.legendary': 'Легендарный',
  'hero.grade.main': 'Главный',
  'hero.grade.rare': 'Редкий',

  // --- hub — Хаб (экран между матчами): шапка, карточки, плитки «Ещё», нижняя навигация.
  'hub.ally.corp': 'Кабинет корпорации',
  'hub.ally.empty.sub': 'корпорации · общие AvA-битвы · влияние',
  'hub.ally.empty.title': 'Альянсы',
  'hub.avatar.title': 'Сменить эмблему',
  'hub.digest.empty.sub':
    'Войди в матч на вкладке «Игры» — здесь появятся ходы, требующие внимания.',
  'hub.digest.empty.title': 'Нет матчей, ждущих приказа',
  'hub.digest.section': 'Сводка',
  'hub.emblem.close': 'Закрыть',
  'hub.emblem.title': 'ВЫБОР ЭМБЛЕМЫ',
  'hub.msgs.aria': 'Сообщения',
  'hub.nav.ally': 'Альянсы',
  'hub.nav.arsenal': 'Арсенал',
  'hub.nav.games': 'Игры',
  'hub.nav.home': 'Домой',
  'hub.nav.meta': 'Прокачка',
  'hub.nav.more': 'Ещё',
  'hub.nav.rank': 'Рейтинг',
  'hub.onboard.skip': 'Пропустить',
  'hub.onboard.start': 'Начать обучение',
  'hub.onboard.sub': 'Короткое обучение покажет интерфейс и первый ход — пара минут.',
  'hub.onboard.title': 'Впервые в Void Dominion?',
  'hub.play': 'ИГРАТЬ СЕЙЧАС',
  'hub.rank.empty.sub': 'сезонный рейтинг по местам в матчах',
  'hub.rank.empty.title': 'Рейтинги — скоро',
  'hub.sandbox.title': 'Песочница',
  'hub.season.sub': 'Рейтинги и альянсы откроются со стартом мета-слоя.',
  'hub.season.title': 'Сезон ещё не начат',
  'hub.solo': 'Одиночная игра',
  'hub.status.online': 'в сети',
  'hub.tile.account': 'Аккаунт',
  'hub.tile.chat': 'Чат',
  'hub.tile.community': 'Сообщество',
  'hub.tile.help': 'Справочник',
  'hub.tile.logout': 'Сменить командира',
  'hub.tile.notifications': 'Уведомления',
  'hub.tile.settings': 'Настройки',
  'hub.tile.support': 'Поддержка',
  'hub.tile.tutorial': 'Обучение',
  'hub.tile.updates': 'Обновления',

  // --- hud — Постоянный интерфейс матча: верхняя панель ресурсов.
  'hud.crest.title': 'Ваш профиль',
  'hud.resource.credits': 'Кредиты',
  'hud.resource.energy': 'Энергия',
  'hud.resource.food': 'Пища',
  'hud.resource.metal': 'Металл',
  'hud.resource.microelectronics': 'Микроэлектроника',

  // --- market — Биржа: вкладки ресурсов.
  'market.res.energy': 'Энергия',
  'market.res.food': 'Пища',
  'market.res.metal': 'Металл',
  'market.res.microelectronics': 'Микро',

  // --- onb — Первый управляемый матч (гид ONB-2 по интерфейсу и первому ходу).
  'onb.goal.collapse.title': 'Свернуть в трей',
  'onb.goal.mine': 'Подними металлодобычу',
  'onb.goal.tray.title': 'Цели первой сессии — развернуть',
  'onb.tour.home': 'Внизу откроется панель твоего домашнего мира: здания, гарнизон и стройка. Тапни свой мир, чтобы её открыть.',
  'onb.tour.mine': 'Начни с экономики: подними Металлодобычу — так вырастет доход металла, на который строится всё остальное.',

  // --- rail — Рельса инструментов в матче: подпись кнопки (.label) + подсказка (.title).
  'rail.chat.label': 'Чат',
  'rail.chat.title': 'Чат',
  'rail.constructor.label': 'Верфь',
  'rail.constructor.title': 'Конструктор — оснащение кораблей, эскадрилий, армии и героев',
  'rail.corp.label': 'Корп',
  'rail.corp.title': 'Корпорация',
  'rail.diplo.label': 'Дипло',
  'rail.diplo.title': 'Дипломатия',
  'rail.exit.label': 'Выйти',
  'rail.exit.title': 'Покинуть сессию',
  'rail.help.label': 'Справка',
  'rail.help.title': 'Справочник',
  'rail.log.label': 'Сводки',
  'rail.log.title': 'Сводки',
  'rail.market.label': 'Рынок',
  'rail.market.title': 'Рынок',
  'rail.msgs.label': 'Почта',
  'rail.msgs.title': 'Сообщения',
  'rail.settings.label': 'Настройки',
  'rail.settings.title': 'Настройки',
  'rail.steward.label': 'Сон',
  'rail.steward.title': 'Хранитель — передать ИИ на сон',
  'rail.tech.label': 'Наука',
  'rail.tech.title': 'Технологии',
  'rail.toggle.title': 'Инструменты',

  // --- seatpick — Выбор фракции и места перед входом в сетевой матч.
  'seatpick.cancel': 'Назад',
  'seatpick.go': 'ВЫБРАТЬ',
  'seatpick.sub': 'Выберите фракцию и стартовую позицию. Занятые места отмечены серым.',
  'seatpick.title': 'Выбор фракции',

  // --- setup — Экран «Настройка схватки»: домашний мир, боты, скорость времени.
  'setup.cancel': 'Назад',
  'setup.go': 'ЗАПУСК',
  'setup.map-hint': 'Тапните светящийся мир, чтобы выбрать старт',
  'setup.sandbox': '🧪 Песочница',
  'setup.speed.hint':
    '×1 — реальное время (час пути = час жизни, мир живёт и офлайн). Для быстрой партии выбери ×10–×100.',
  'setup.speed.label': 'Скорость времени',
  'setup.sub':
    'Выберите свой домашний мир на карте, задайте число соперников-ботов и запускайте. Пустые места займут боты — выключите место, чтобы командовать меньшим сектором, или выключите все ради мирной одиночной песочницы для знакомства с интерфейсом.',
  'setup.title': 'НАСТРОЙКА СХВАТКИ',

  // --- ship — Корабли: корпуса и модули (имя + описание).
  'ship.hull.cruiser': 'Крейсер',
  'ship.hull.dropship': 'Носитель',
  'ship.hull.scout_drone': 'Скаут-дрон',
  'ship.hull.siege_lance': 'Осадная ланса',
  'ship.module.battery.desc': '+30% к атаке.',
  'ship.module.battery.name': 'Батарея',
  'ship.module.plating.desc': '+25% HP корпуса.',
  'ship.module.plating.name': 'Броня',
  'ship.module.shield.desc': '+30% к обороне.',
  'ship.module.shield.name': 'Щит',
  'ship.module.targeting.desc': '+15% к атаке и обороне.',
  'ship.module.targeting.name': 'Наведение',
  'ship.module.thruster.desc': '+20% к скорости.',
  'ship.module.thruster.name': 'Двигатель',

  // --- side — Боковая панель матча: конвейеры, карточка флота, бой, досье мира, вкладки гарнизона.
  'side.arch.artillery': 'артиллерия',
  'side.arch.combat': 'боевые',
  'side.arch.flagship': 'флагман',
  'side.arch.scout': 'скауты',
  'side.arch.swarm': 'рой',
  'side.arch.transport': 'транспорты',
  'side.battle.attacker': 'атака',
  'side.battle.defender': 'оборона',
  'side.battle.next-round': 'следующий раунд через',
  'side.battle.phase.ground': 'высадка',
  'side.battle.phase.orbit': 'орбита',
  'side.battle.retreat': '⤺ Отступить',
  'side.battle.retreat.hint':
    'Отход стоит −40% ТЕКУЩЕГО корпуса и щита (израненный флот теряет 40% остатка — отход не добивает) и даёт рывок скорости для бегства. Десант в высадке отступить не может; с орбиты вне боя корабль уходит свободно.',
  'side.battle.side.fleet': 'флот',
  'side.battle.side.garrison': 'гарнизон',
  'side.battle.side.landing': 'десант',
  'side.battle.title': '⚔ Бой — {phase} · раунд {r}',
  'side.build.conveyor': 'Строительный конвейер',
  'side.build.enemy-hidden': 'Строительная телеметрия врага недоступна',
  'side.build.hp': 'оз',
  'side.build.upgrade': '▲ Улучшить {c}',
  'side.conveyor.cancel.title': 'Отменить — вернёт часть ресурсов и поставит на паузу',
  'side.conveyor.dequeue.title': 'Убрать из очереди',
  'side.conveyor.idle': 'Ожидание заказов',
  'side.conveyor.idle.sub': 'готов к следующему заказу',
  'side.conveyor.idle.tag': 'ПРОСТОЙ',
  'side.conveyor.now': 'СЕЙЧАС',
  'side.conveyor.paused': 'Приостановлено {n}%',
  'side.conveyor.queue-empty': 'очередь пуста',
  'side.conveyor.resume.title': 'Возобновить — доплатить остаток',
  'side.conveyor.waiting': 'Ждёт ресурсы: {c}',
  'side.empty': 'Тапните мир.',
  'side.fleet.bombarding': 'бомбардирует',
  'side.fleet.enroute': '↗ идёт к {dest} · прибытие через',
  'side.fleet.hero-aura': '— проекция · +5% атаки/обороны этому флоту',
  'side.fleet.hull-tag': 'корпус {p}%',
  'side.fleet.hunger': 'голод: −25% на земле',
  'side.fleet.in-orbit': 'на орбите',
  'side.fleet.on-lane': '⟜ стоит на трассе {lane} · {p}% пути',
  'side.fleet.repair.dock.title': 'Экспресс-ремонт у своего дока за металл',
  'side.fleet.repair.instant.title': 'Мгновенный ремонт всего корпуса за кредиты',
  'side.fleet.ships': 'Корабли — тап для характеристик',
  'side.fleet.sub': '{s} кораблей · {tr} десанта',
  'side.fleet.sub.pc': 'Корабли: {s} · Десант: {tr}',
  'side.fleet.tile.hint': 'тап — полное досье',
  'side.fleet.troops': 'Десант на борту',
  'side.garrison.plus-troops': '+{n} десанта',
  'side.garrison.select': 'Выбрать →',
  'side.garrison.ships': 'Корабли в гарнизоне',
  'side.garrison.wing': 'Авиагруппа в гарнизоне',
  'side.ground.conveyor': 'Наземный конвейер',
  'side.ground.empty': 'наземной армии здесь нет',
  'side.ground.hint':
    'Наземные части обороняют ваши миры. Их можно погрузить на флот для захвата вражеских миров.',
  'side.ground.load': '▲ Погрузить {u}',
  'side.ground.loading': '⏳ погрузка: {n} (≈1ч на единицу)',
  'side.ground.title': 'Наземная армия ⇄ гарнизон',
  'side.ground.units': 'Наземные части',
  'side.ground.unload': '▼ Выгрузить {u}',
  'side.group.clear': 'Снять выделение группы',
  'side.group.hint':
    'Нажмите «Курс» и тапните цель — все выбранные флоты пойдут туда (проложат маршрут и встанут). «Слить» сплавляет группу в один флот (дальние сначала подлетят). Shift- или Ctrl/⌘-клик по флоту добавляет его в группу; Shift-рамка по пустому месту выделяет несколько.',
  'side.group.sub': '{f} флот(ов) · {s} кораблей · {tr} десанта',
  'side.group.title': 'ОПЕРАТИВНАЯ ГРУППА',
  'side.neutral': 'Нейтрал',
  'side.none': 'нет',
  'side.notelemetry.hint':
    'Отправьте флот к этой системе (или расширьте радар), чтобы обнаружить её.',
  'side.notelemetry.sub': 'Не исследовано — вне сенсоров и радаров. Содержимое неизвестно.',
  'side.notelemetry.title': 'НЕТ ТЕЛЕМЕТРИИ',
  'side.scan.buildings': 'Постройки',
  'side.scan.garrison': 'Гарнизон на момент скана',
  'side.scan.hint': 'Обновите данные флотом или радаром.',
  'side.scan.no-buildings': 'построек не видели',
  'side.scan.owner': 'Владелец',
  'side.scan.spy': '🕵 Разведать мир · {c}¤',
  'side.scan.stale': 'Вне сенсорного охвата — последний скан (мог устареть).',
  'side.scan.title': 'ПОСЛЕДНИЕ ДАННЫЕ ✦',
  'side.shipyard.conveyor': 'Конвейер верфи',
  'side.shipyard.hint':
    'Флот -ваше оружие и защита. Здесь вы можете заказывать корабли для пополнения флота.',
  'side.stat.atk': 'АТК',
  'side.stat.def': 'ЗАЩ',
  'side.stat.spd': 'СКР',
  'side.strike.assault': '⚔ Штурм',
  'side.strike.bombard': '⊗ Бомбардировать',
  'side.strike.bombard.stop': '⊗ Прекратить бомбардировку',
  'side.strike.forecast':
    'Прогноз штурма: {v} · ~{r} р. · потери {a} дес. ({pa}%) / {d} гарн. ({pd}%)',
  'side.strike.forecast.attacker': 'десант возьмёт мир',
  'side.strike.forecast.defender': 'гарнизон устоит',
  'side.strike.forecast.draw': 'затяжной пат',
  'side.strike.forecast.hint':
    'Прогноз по видимым составам, без бонусов местности, укреплений и технологий — реальный бой может отличаться.',
  'side.strike.hint':
    'С орбиты можно бомбардировать (изнашивает здания и замораживает их выпуск), но ПВО гарнизона достаёт до вас. Штурм высаживает десант против гарнизона.',
  'side.strike.title': 'Удар',
  'side.summary.attack': 'Атака',
  'side.summary.back': '‹ Назад к карточке',
  'side.summary.cargo': 'Трюм',
  'side.summary.composition': 'Состав',
  'side.summary.day': 'день',
  'side.summary.defense': 'Защита',
  'side.summary.firing-cap': 'бьют {n} юнитов',
  'side.summary.forced-march': 'форс-марш',
  'side.summary.hull': 'Корпус',
  'side.summary.radar': 'Радар',
  'side.summary.retreat-haste': 'рывок отхода',
  'side.summary.shield': 'Щит',
  'side.summary.speed': 'Скорость',
  'side.summary.speed.note': 'по самому медленному; техи/фракция/местность — на переходе',
  'side.summary.title': 'Сводка армии',
  'side.summary.total': 'всего',
  'side.summary.troops': 'десант',
  'side.summary.upkeep': 'Содержание',
  'side.tab.buildings': 'Здания',
  'side.tab.fleet': 'Флот',
  'side.tab.ground': 'Земля',
  'side.tab.wings': 'Крылья',
  'side.unit.ground': 'земля',
  'side.unit.space': 'космос',
  'side.wing.conveyor': 'Верфь авиагруппы',
  'side.wing.fuel': 'топливо {n}',
  'side.wing.garrison.hint':
    'Носитель (◈) несёт эскадрильи (△). Запускайте авиагруппу из панели выбранного флота кнопкой «🛩 Запустить эскадрилью».',
  'side.wing.hint':
    'Отделяет эскадрильи в отдельный быстрый флот — уводите его на удар, а носитель остаётся в строю. Нужен хотя бы один не-эскадрильный корабль. Контрится орбитальным ПВО.',
  'side.wing.launch': '🛩 Запустить эскадрилью ({n})',
  'side.wing.patrol-on': '🛩 дежурный вылет: ВКЛ',
  'side.wing.radius': 'радиус {r}',
  'side.wing.rearming': 'перезарядка {n}',
  'side.wing.title': 'Авиагруппа',
  'side.world.blackout': 'блэкаут: радары и ПВО −50%',
  'side.world.bonus.defense': 'оборона',
  'side.world.bonus.production': 'произв.',
  'side.world.buildings': 'Постройки',
  'side.world.capital': 'Столица',
  'side.world.capital.note': '— здесь возродятся и сменят модули герои',
  'side.world.count.buildings': 'построек',
  'side.world.count.ground': 'наземных',
  'side.world.count.ships': 'кораблей',
  'side.world.count.squadrons': 'эскадрилий',
  'side.world.defense': 'оборона {p}',
  'side.world.designation': 'Обозначение',
  'side.world.fleet-ships': '{n} кораблей',
  'side.world.fleets': 'Флоты на орбите',
  'side.world.garrison': 'Гарнизон',
  'side.world.hold': '🚩 Держать',
  'side.world.hold.clear': 'Снять точку',
  'side.world.hold.set': '🚩 Назначить точкой удержания',
  'side.world.hold.title': 'Точка удержания',
  'side.world.kind': 'Вид / тип / местность',
  'side.world.make-capital': '★ Сделать столицей',
  'side.world.output': 'Базовый выход/ч',
  'side.world.output.note': '— перекос типа мира',
  'side.world.owner': 'Владелец',
  'side.world.ping': '📍 Пинг',
  'side.world.ping.long': '📍 Пинг — отметить и отправить…',
  'side.world.production': 'произв. {p}',
  'side.world.spy-window': '🕵 Окно разведки',
  'side.world.spy-window.left': 'ещё {left}',
  'side.world.stat.garrison': 'гарнизон',
  'side.world.summary': 'Сводка мира',
  'side.world.type': 'Тип: «{pt}» — {mods}',
  'side.world.type-bonuses': 'Бонусы типа',
  'side.world.type.long': 'Мир типа «{pt}» — {mods}',
  'side.world.vp': 'Очки победы',

  // --- speed — Панель времени: подсказки множителей, перезапуска и выхода.
  'speed.exit': 'Выход в меню',
  'speed.mult.half-hour': 'полчаса в секунду',
  'speed.mult.hour': 'час в секунду',
  'speed.mult.real': 'реальное время',
  'speed.mult.two-hours': 'два часа в секунду',
  'speed.restart': 'Перезапуск — к выбору ботов',

  // --- tech — Дерево технологий: названия веток.
  'tech.branch.command': 'Командование',
  'tech.branch.ground': 'Земля',
  'tech.branch.missile': 'Ракеты',
  'tech.branch.space': 'Космос',
  'tech.branch.squadron': 'Эскадрильи',

  // --- upd — Баннер обновления сборки (APK; в браузере не показывается).
  'upd.available': 'Доступна новая сборка',
  'upd.go': 'Обновить',
  'upd.later': 'Позже',

  // --- welcome — Экран приветствия: вход, регистрация, восстановление, список матчей, подвал.
  'welcome.apple': 'Войти через Apple',
  'welcome.back': '‹ назад',
  'welcome.browse.go': 'Обновить список',
  'welcome.browse.nick': 'Позывной',
  'welcome.browse.pass': 'Пароль',
  'welcome.browse.server': 'Сервер',
  'welcome.browse.sub': 'Выбери матч из списка и войди, или обнови список.',
  'welcome.browse.tab.active': 'Активные',
  'welcome.browse.tab.archived': 'Архив',
  'welcome.browse.tab.available': 'Доступные',
  'welcome.browse.title': 'МАТЧИ',
  'welcome.divider': 'войти через',
  'welcome.go': 'Войти',
  'welcome.google': 'Войти через Google',
  'welcome.imprint': 'Выходные данные',
  'welcome.login': 'Вход по позывному',
  'welcome.new': 'Новый командир',
  'welcome.nick.ph': 'позывной',
  'welcome.pass.again.ph': 'ещё раз',
  'welcome.pass.min.ph': 'минимум 8 символов',
  'welcome.pass.ph': 'пароль (аккаунт создастся сам)',
  'welcome.privacy': 'Политика конфиденциальности',
  'welcome.recover.go': 'Отправить ссылку',
  'welcome.recover.mail': 'Почта',
  'welcome.recover.sub': 'Укажи почту аккаунта — пришлём ссылку для сброса пароля.',
  'welcome.recover.title': 'Восстановление доступа',
  'welcome.register.go': 'Создать командира',
  'welcome.register.mail': 'Почта (для восстановления)',
  'welcome.register.nick': 'Имя командира',
  'welcome.register.pass': 'Пароль',
  'welcome.register.pass2': 'Повтор пароля',
  'welcome.register.recover': 'Восстановить доступ',
  'welcome.register.sub': 'Придумай позывной и пароль — так создаётся аккаунт.',
  'welcome.register.title': 'Новый командир',
  'welcome.reset.go': 'Сменить пароль',
  'welcome.reset.pass': 'Пароль',
  'welcome.reset.pass2': 'Повтор пароля',
  'welcome.reset.sub': 'Придумай новый пароль для входа.',
  'welcome.reset.title': 'Новый пароль',
  'welcome.solo': 'Одиночная игра',
  'welcome.sub': 'Добро пожаловать, командир. Флот ждёт приказа.',
  'welcome.support': 'Поддержка',
  'welcome.tagline': 'Грань пустоты',
  'welcome.terms': 'Условия',
  'welcome.testmode': '🧪 Тесты · режим разработчика',
  'welcome.update-check': 'Проверить обновления',

  // --- win — Заголовки окон матча (сводки, технологии, хранитель, конструкторы).
  'win.divdesign.title': 'КОНСТРУКТОР ДИВИЗИЙ',
  'win.log.recap': 'Сводка возвращения',
  'win.log.title': 'СВОДКИ',
  'win.scipick.back': '↩ В меню',
  'win.scipick.title': 'СОВЕТ УЧЁНЫХ',
  'win.steward.title': 'ХРАНИТЕЛЬ · ИИ НА СОН',
  'win.tech.title': 'ТЕХНОЛОГИИ',
};
